# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/tail_spin_r/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/tail_spin_r/keyframes/0
execute if entity @s[scores={AsaMatrix=1..8}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:reus/anim/tail_spin_r/keyframes/1
execute if entity @s[scores={AsaMatrix=9..18}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:reus/anim/tail_spin_r/keyframes/2
execute if entity @s[scores={AsaMatrix=19..23}] run tp @s ^0 ^-0.02 ^0 ~-20 ~
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:reus/anim/tail_spin_r/keyframes/3
execute if entity @s[scores={AsaMatrix=24..28}] run tp @s ^0 ^-0.01111111 ^0 ~-12 ~
execute if entity @s[scores={AsaMatrix=29..32}] run tp @s ^0 ^-0.01111111 ^0 ~-3 ~
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:reus/anim/tail_spin_r/keyframes/4
execute if entity @s[scores={AsaMatrix=33..42}] run tp @s ^0 ^0.02 ^0 ~-1 ~
execute if entity @s[scores={AsaMatrix=43..}] run function asa_animator:reus/anim/tail_spin_r/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model

execute if entity @s[scores={AsaMatrix=1}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=19}] run playsound entity.player.attack.sweep master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=19..26}] positioned ^ ^ ^-3 run function asa_animator:reus/anim/tail_spin_l/events/damage