# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:tiga/anim/death/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:tiga/anim/death/keyframes/0
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^0 ^0 ^-0.06
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:tiga/anim/death/keyframes/1
execute if entity @s[scores={AsaMatrix=6..10}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:tiga/anim/death/keyframes/2
execute if entity @s[scores={AsaMatrix=11..20}] run tp @s ^0 ^0.007999999 ^0.04
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:tiga/anim/death/keyframes/3
execute if entity @s[scores={AsaMatrix=21..30}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:tiga/anim/death/keyframes/4
execute if entity @s[scores={AsaMatrix=31..40}] run tp @s ^0 ^-0.028 ^0.02
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:tiga/anim/death/keyframes/5
execute if entity @s[scores={AsaMatrix=41..45}] run tp @s ^-0.06 ^-0.16 ^0.1
execute if entity @s[scores={AsaMatrix=46}] run function asa_animator:tiga/anim/death/keyframes/6
execute if entity @s[scores={AsaMatrix=46..70}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=71..}] run function asa_animator:tiga/anim/death/end
execute as @e[type=armor_stand,tag=TigaParts] run function #asa_matrix:animate
function asa_animator:tiga/model

execute if entity @s[scores={AsaMatrix=46}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.7

execute if entity @s[scores={AsaMatrix=1}] at @s positioned ~ ~5 ~ run tp @s ~ ~ ~
execute if entity @s[scores={AsaMatrix=1}] at @s positioned ~ ~5 ~ run function asa_animator:zinogre/manager/check_ground