# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:reus/normal/flying_charge/start
execute if score @s AsaMatrix matches 1 run function asa_animator:reus/normal/flying_charge/keyframes/0
execute if score @s AsaMatrix matches 1..8 run tp @s ^0 ^-0.05 ^-0.0625
execute if score @s AsaMatrix matches 9 run function asa_animator:reus/normal/flying_charge/keyframes/1
execute if score @s AsaMatrix matches 9..16 run tp @s ^0 ^0.2 ^-0.0625
execute if score @s AsaMatrix matches 17 run function asa_animator:reus/normal/flying_charge/keyframes/2
execute if score @s AsaMatrix matches 17..25 run tp @s ^0 ^-0.1777778 ^-0.05555556
execute if score @s AsaMatrix matches 26 run function asa_animator:reus/normal/flying_charge/keyframes/3
execute if score @s AsaMatrix matches 26..35 run tp @s ^0 ^0.04 ^0
execute if score @s AsaMatrix matches 36 run function asa_animator:reus/normal/flying_charge/keyframes/4
execute if score @s AsaMatrix matches 36..45 run tp @s ^0 ^-0.04 ^0
execute if score @s AsaMatrix matches 46 run function asa_animator:reus/normal/flying_charge/keyframes/5
execute if score @s AsaMatrix matches 46..55 run tp @s ^0 ^0.04 ^0
execute if score @s AsaMatrix matches 56 run function asa_animator:reus/normal/flying_charge/keyframes/6
execute if score @s AsaMatrix matches 56..65 run tp @s ^0 ^-0.04 ^0
execute if score @s AsaMatrix matches 66 run function asa_animator:reus/normal/flying_charge/keyframes/7
execute if score @s AsaMatrix matches 66..75 run tp @s ^0 ^0.14 ^-0.15
execute if score @s AsaMatrix matches 76 run function asa_animator:reus/normal/flying_charge/keyframes/8
execute if score @s AsaMatrix matches 76..85 run tp @s ^0 ^-0.08 ^-0.05
execute if score @s AsaMatrix matches 86 run function asa_animator:reus/normal/flying_charge/keyframes/9
execute if score @s AsaMatrix matches 86..95 run tp @s ^0 ^-0.1 ^-0.05
execute if score @s AsaMatrix matches 96 run function asa_animator:reus/normal/flying_charge/keyframes/10
execute if score @s AsaMatrix matches 96..110 run tp @s ^0 ^0.05333333 ^-0.03333334
execute if score @s AsaMatrix matches 111.. run function asa_animator:reus/normal/flying_charge/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model

# 敵を向く
execute if score @s AsaMatrix matches 1..60 run function asa_animator:reus/manager/rotate

# 攻撃
execute if score @s AsaMatrix matches 25..65 positioned as @e[type=armor_stand,tag=ReusParts,tag=HeadU] run function asa_animator:reus/normal/flying_charge/effect/particle
execute if score @s AsaMatrix matches 65 run function asa_animator:reus/normal/flying_charge/effect/attack_start
execute if score @s AsaMatrix matches 66..70 positioned as @e[type=armor_stand,tag=ReusParts,tag=HeadU] as @e[type=marker,tag=ReusChargeFPos] rotated as @s run function asa_animator:reus/normal/flying_charge/effect/attack
execute if score @s AsaMatrix matches 71 run kill @e[type=marker,tag=ReusChargeFPos]

# 効果音
execute if score @s AsaMatrix matches 8 run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
execute if score @s AsaMatrix matches 25 run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
execute if score @s AsaMatrix matches 45 run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
execute if score @s AsaMatrix matches 65 run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
execute if score @s AsaMatrix matches 95 run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7