# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:dyno/anim/destroy_head/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:dyno/anim/destroy_head/keyframes/0
execute if entity @s[scores={AsaMatrix=1..8}] run tp @s ^0 ^0.0375 ^-0.2 ~1 ~
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:dyno/anim/destroy_head/keyframes/1
execute if entity @s[scores={AsaMatrix=9..15}] run tp @s ^0 ^-0.04285714 ^0.01428571
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:dyno/anim/destroy_head/keyframes/2
execute if entity @s[scores={AsaMatrix=16..25}] run tp @s ^0 ^-0.03 ^-0.03
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:dyno/anim/destroy_head/keyframes/3
execute if entity @s[scores={AsaMatrix=26..30}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:dyno/anim/destroy_head/keyframes/4
execute if entity @s[scores={AsaMatrix=31..42}] run tp @s ^0 ^0.0125 ^0.0125
execute if entity @s[scores={AsaMatrix=43}] run function asa_animator:dyno/anim/destroy_head/keyframes/5
execute if entity @s[scores={AsaMatrix=43..55}] run tp @s ^0 ^0.01153846 ^0.01153846
execute if entity @s[scores={AsaMatrix=56..}] run function asa_animator:dyno/anim/destroy_head_heat/end
execute as @e[type=armor_stand,tag=DynoParts] run function #asa_matrix:animate
function asa_animator:dyno/model

execute at @s positioned ~ ~5 ~ run tp @s ~ ~ ~
execute at @s positioned ~ ~5 ~ run function asa_animator:zinogre/manager/check_ground
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:dyno/manager/particle/jump

execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:dyno/manager/model/change_to_normal_head
execute if entity @s[scores={AsaMatrix=9}] as @e[type=armor_stand,tag=DynoParts,tag=HeadU,distance=0..15] at @s run particle explosion_emitter ~ ~1.4 ~ 0 0 0 0 1
execute if entity @s[scores={AsaMatrix=9}] run playsound entity.generic.explode master @a ~ ~ ~ 2 0.7