# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:dyno/anim/bite_2/start
execute if score @s AsaMatrix matches 1 run function asa_animator:dyno/anim/bite_2/keyframes/0
execute if score @s AsaMatrix matches 1..5 run tp @s ^0 ^0 ^-0.1
execute if score @s AsaMatrix matches 6 run function asa_animator:dyno/anim/bite_2/keyframes/1
execute if score @s AsaMatrix matches 6..15 run tp @s ^0 ^0.01 ^0
execute if score @s AsaMatrix matches 16 run function asa_animator:dyno/anim/bite_2/keyframes/2
execute if score @s AsaMatrix matches 16..20 run tp @s ^0.1 ^-0.04 ^0
execute if score @s AsaMatrix matches 21 run function asa_animator:dyno/anim/bite_2/keyframes/3
execute if score @s AsaMatrix matches 21..27 run tp @s ^-0.07142857 ^0.02857143 ^0
execute if score @s AsaMatrix matches 28 run function asa_animator:dyno/anim/bite_2/keyframes/4
execute if score @s AsaMatrix matches 28..32 run tp @s ^-0.1 ^-0.04 ^0
execute if score @s AsaMatrix matches 33 run function asa_animator:dyno/anim/bite_2/keyframes/5
execute if score @s AsaMatrix matches 33..37 run tp @s ^0 ^-0.01 ^0.1
execute if score @s AsaMatrix matches 38 run function asa_animator:dyno/anim/bite_2/keyframes/6
execute if score @s AsaMatrix matches 38..42 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 43 run function asa_animator:dyno/anim/bite_2/keyframes/7
execute if score @s AsaMatrix matches 43..52 run tp @s ^0.05 ^0.015 ^-0.05 ~-0.5 ~
execute if score @s AsaMatrix matches 53.. run function asa_animator:dyno/anim/bite_2/end
execute as @e[type=armor_stand,tag=DynoParts] run function #asa_matrix:animate
function asa_animator:dyno/model

execute if score @s AsaMatrix matches 1..15 run function asa_animator:dyno/manager/rotate

execute if score @s AsaMatrix matches 5 run function asa_animator:dyno/manager/particle/jump
execute if score @s AsaMatrix matches 16 run function asa_animator:dyno/manager/particle/jump
execute if score @s AsaMatrix matches 28 run function asa_animator:dyno/manager/particle/jump

execute if score @s AsaMatrix matches 20 positioned ^ ^ ^6 run function asa_animator:dyno/anim/bite/events/damage
execute if score @s AsaMatrix matches 32 positioned ^ ^ ^6 run function asa_animator:dyno/anim/bite/events/damage

execute if score @s AsaMatrix matches 1..15 at @s if entity @e[distance=0..7,tag=DynoAttackTarget] run tp @s ^ ^ ^-0.3
execute if score @s AsaMatrix matches 21..32 at @s unless entity @e[distance=0..7,tag=DynoAttackTarget] run tp @s ^ ^ ^0.8