# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:ruko/anim/stay_stand/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:ruko/anim/stay_stand/keyframes/0
execute if entity @s[scores={AsaMatrix=1..20}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:ruko/anim/stay_stand/keyframes/1
execute if entity @s[scores={AsaMatrix=21..30}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:ruko/anim/stay_stand/keyframes/2
execute if entity @s[scores={AsaMatrix=31..50}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=51..}] run function asa_animator:ruko/anim/stay_stand/end
execute as @e[type=armor_stand,tag=RukoParts] run function #asa_matrix:animate
function asa_animator:ruko/model

execute at @s if block ~ ~-0.4 ~ #asa_animator:no_collision at @s run function asa_animator:zinogre/manager/check_ground
execute at @s unless block ~ ~-0.25 ~ #asa_animator:no_collision at @s run tp @s ~ ~0.05 ~ ~ ~