# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:nazuti/anim/breath_fog_v/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:nazuti/anim/breath_fog_v/keyframes/0
execute if entity @s[scores={AsaMatrix=1..6}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:nazuti/anim/breath_fog_v/keyframes/1
execute if entity @s[scores={AsaMatrix=7..14}] run tp @s ^0 ^0.01875 ^0
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:nazuti/anim/breath_fog_v/keyframes/2
execute if entity @s[scores={AsaMatrix=15..20}] run tp @s ^0 ^0.004166665 ^0
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:nazuti/anim/breath_fog_v/keyframes/3
execute if entity @s[scores={AsaMatrix=21..26}] run tp @s ^0 ^0.004166668 ^0
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:nazuti/anim/breath_fog_v/keyframes/4
execute if entity @s[scores={AsaMatrix=27..33}] run tp @s ^0 ^0.007142857 ^0
execute if entity @s[scores={AsaMatrix=34}] run function asa_animator:nazuti/anim/breath_fog_v/keyframes/5
execute if entity @s[scores={AsaMatrix=34..41}] run tp @s ^0 ^0.006250001 ^0
execute if entity @s[scores={AsaMatrix=42}] run function asa_animator:nazuti/anim/breath_fog_v/keyframes/6
execute if entity @s[scores={AsaMatrix=42..48}] run tp @s ^0 ^-0.01428572 ^0.02857143
execute if entity @s[scores={AsaMatrix=49}] run function asa_animator:nazuti/anim/breath_fog_v/keyframes/7
execute if entity @s[scores={AsaMatrix=49..57}] run tp @s ^0 ^0.01111111 ^-0.01111111
execute if entity @s[scores={AsaMatrix=58}] run function asa_animator:nazuti/anim/breath_fog_v/keyframes/8
execute if entity @s[scores={AsaMatrix=58..67}] run tp @s ^0 ^-0.01 ^-0.01
execute if entity @s[scores={AsaMatrix=68}] run function asa_animator:nazuti/anim/breath_fog_v/keyframes/9
execute if entity @s[scores={AsaMatrix=68..77}] run tp @s ^0 ^-0.02 ^0
execute if entity @s[scores={AsaMatrix=78}] run function asa_animator:nazuti/anim/breath_fog_v/keyframes/10
execute if entity @s[scores={AsaMatrix=78..92}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=93..}] run function asa_animator:nazuti/anim/counter_breath_v/end
execute as @e[type=armor_stand,tag=NazutiParts] run function #asa_matrix:animate
function asa_animator:nazuti/model

execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:nazuti/manager/particle/step
execute if entity @s[scores={AsaMatrix=77}] run function asa_animator:nazuti/manager/particle/step
execute if entity @s[scores={AsaMatrix=14..38}] run function asa_animator:nazuti/manager/rotate

execute if entity @s[scores={AsaMatrix=14}] run playsound entity.player.burp master @a ~ ~ ~ 3 0.5
execute if entity @s[scores={AsaMatrix=14}] run playsound item.bucket.empty_lava master @a ~ ~ ~ 2 0.5
execute if entity @s[scores={AsaMatrix=14}] run playsound item.bucket.empty_lava master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=14..50}] run playsound entity.player.breath master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=14..50}] run playsound entity.player.breath master @a ~ ~ ~ 2 0.9

execute if entity @s[scores={AsaMatrix=9}] run summon marker ~ ~ ~ {Tags:["NazutiMoveRotate"]}
execute if entity @s[scores={AsaMatrix=10}] run tp @e[type=marker,tag=NazutiMoveRotate,distance=0..5] ~ ~ ~ ~40 ~-5
execute if entity @s[scores={AsaMatrix=13}] store result score @e[type=marker,tag=NazutiMoveRotate,distance=0..5] AsaMatrix run data get entity @s Rotation[0] 100
execute if entity @s[scores={AsaMatrix=14..33}] as @e[type=marker,tag=NazutiMoveRotate,distance=0..5] rotated as @s run tp @s ~ ~ ~ ~-3 ~-0.5
execute if entity @s[scores={AsaMatrix=37..41}] as @e[type=marker,tag=NazutiMoveRotate,distance=0..5] rotated as @s run tp @s ~ ~ ~ ~2 ~-8
execute if entity @s[scores={AsaMatrix=41}] run data modify entity @e[type=marker,tag=NazutiMoveRotate,distance=0..5,limit=1] Rotation[0] set from entity @s Rotation[0]
execute if entity @s[scores={AsaMatrix=42..48}] as @e[type=marker,tag=NazutiMoveRotate,distance=0..5] rotated as @s run tp @s ~ ~ ~ ~ ~9
execute if entity @s[scores={AsaMatrix=49..57}] as @e[type=marker,tag=NazutiMoveRotate,distance=0..5] rotated as @s run tp @s ~ ~ ~ ~ ~-9
execute if entity @s[scores={AsaMatrix=58}] run kill @e[type=marker,tag=NazutiMoveRotate]

execute if entity @s[scores={AsaMatrix=14..57}] positioned as @e[type=armor_stand,tag=NazutiParts,tag=HeadU] positioned ^ ^1.2 ^1 rotated as @e[type=marker,tag=NazutiMoveRotate,distance=0..8] run function asa_animator:nazuti/anim/breath_fog_v/events/damage_f
execute if entity @s[scores={AsaMatrix=14..57}] run function asa_animator:nazuti/anim/breath_fog_v/events/rotate

execute if entity @s[scores={AsaMatrix=28}] run function asa_animator:nazuti/manager/model/stealth_lucent
execute if entity @s[scores={AsaMatrix=37}] run function asa_animator:nazuti/manager/model/stealth_end