# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:dyno/anim/destroy_tail/start
execute if score @s AsaMatrix matches 1 run function asa_animator:dyno/anim/destroy_tail/keyframes/0
execute if score @s AsaMatrix matches 1..8 run tp @s ^0 ^0.0375 ^0.4
execute if score @s AsaMatrix matches 9 run function asa_animator:dyno/anim/destroy_tail/keyframes/1
execute if score @s AsaMatrix matches 9..16 run tp @s ^0 ^-0.025 ^0.4 ~-3 ~
execute if score @s AsaMatrix matches 17 run function asa_animator:dyno/anim/destroy_tail/keyframes/2
execute if score @s AsaMatrix matches 17..24 run tp @s ^0 ^-0.025 ^0.4 ~-7 ~
execute if score @s AsaMatrix matches 25 run function asa_animator:dyno/anim/destroy_tail/keyframes/3
execute if score @s AsaMatrix matches 25..29 run tp @s ^0.1 ^-0.02 ^0.2 ~-18 ~
execute if score @s AsaMatrix matches 30..34 run tp @s ^0.1 ^-0.02 ^-0.05 ~-5 ~
execute if score @s AsaMatrix matches 35 run function asa_animator:dyno/anim/destroy_tail/keyframes/4
execute if score @s AsaMatrix matches 35..38 run tp @s ^0 ^0 ^-0.05 ~-1 ~
execute if score @s AsaMatrix matches 39 run function asa_animator:dyno/anim/destroy_tail/keyframes/5
execute if score @s AsaMatrix matches 39..55 run tp @s ^0 ^0.01764706 ^0.005882353
execute if score @s AsaMatrix matches 56.. run function asa_animator:dyno/anim/destroy_tail/end
execute as @e[type=armor_stand,tag=DynoParts] run function #asa_matrix:animate
function asa_animator:dyno/model

execute at @s positioned ~ ~5 ~ run tp @s ~ ~ ~
execute at @s positioned ~ ~5 ~ run function asa_animator:zinogre/manager/check_ground
execute if score @s AsaMatrix matches 17..34 run playsound block.grass.step master @a ~ ~ ~ 2 0.5
execute if score @s AsaMatrix matches 17..34 run particle block grass_block ~ ~ ~ 1 0.1 1 0 3