# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:kushala/anim/stride/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:kushala/anim/stride/keyframes/0
execute if entity @s[scores={AsaMatrix=1..7}] run tp @s ^0 ^-0.01428571 ^0.02857143 ~0.5 ~
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:kushala/anim/stride/keyframes/1
execute if entity @s[scores={AsaMatrix=8..20}] run tp @s ^0 ^0.03461538 ^-0.01538462
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:kushala/anim/stride/keyframes/2
execute if entity @s[scores={AsaMatrix=21..25}] run tp @s ^0 ^0 ^0 ~-0.5 ~
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:kushala/anim/stride/keyframes/3
execute if entity @s[scores={AsaMatrix=26..31}] run tp @s ^0 ^0.01666667 ^0
execute if entity @s[scores={AsaMatrix=32}] run function asa_animator:kushala/anim/stride/keyframes/4
execute if entity @s[scores={AsaMatrix=32..37}] run tp @s ^0 ^-0.01666667 ^0
execute if entity @s[scores={AsaMatrix=38}] run function asa_animator:kushala/anim/stride/keyframes/5
execute if entity @s[scores={AsaMatrix=38..42}] run tp @s ^0 ^0.01 ^0
execute if entity @s[scores={AsaMatrix=43}] run function asa_animator:kushala/anim/stride/keyframes/6
execute if entity @s[scores={AsaMatrix=43..47}] run tp @s ^0 ^0.009999996 ^0
execute if entity @s[scores={AsaMatrix=48}] run function asa_animator:kushala/anim/stride/keyframes/7
execute if entity @s[scores={AsaMatrix=48..53}] run tp @s ^0 ^-0.01666667 ^0
execute if entity @s[scores={AsaMatrix=54}] run function asa_animator:kushala/anim/stride/keyframes/8
execute if entity @s[scores={AsaMatrix=54..58}] run tp @s ^0 ^0.01 ^0
execute if entity @s[scores={AsaMatrix=59}] run function asa_animator:kushala/anim/stride/keyframes/9
execute if entity @s[scores={AsaMatrix=59..63}] run tp @s ^0 ^0.009999996 ^0
execute if entity @s[scores={AsaMatrix=64}] run function asa_animator:kushala/anim/stride/keyframes/10
execute if entity @s[scores={AsaMatrix=64..69}] run tp @s ^0 ^-0.01666667 ^0
execute if entity @s[scores={AsaMatrix=70}] run function asa_animator:kushala/anim/stride/keyframes/11
execute if entity @s[scores={AsaMatrix=70..74}] run tp @s ^0 ^0.01 ^0
execute if entity @s[scores={AsaMatrix=75}] run function asa_animator:kushala/anim/stride/keyframes/12
execute if entity @s[scores={AsaMatrix=75..79}] run tp @s ^0 ^0.009999996 ^0
execute if entity @s[scores={AsaMatrix=80}] run function asa_animator:kushala/anim/stride/keyframes/13
execute if entity @s[scores={AsaMatrix=80..85}] run tp @s ^0 ^-0.01666667 ^0
execute if entity @s[scores={AsaMatrix=86}] run function asa_animator:kushala/anim/stride/keyframes/14
execute if entity @s[scores={AsaMatrix=86..90}] run tp @s ^0 ^0.01 ^0
execute if entity @s[scores={AsaMatrix=91}] run function asa_animator:kushala/anim/stride/keyframes/15
execute if entity @s[scores={AsaMatrix=91..95}] run tp @s ^0 ^0.009999996 ^0
execute if entity @s[scores={AsaMatrix=96}] run function asa_animator:kushala/anim/stride/keyframes/16
execute if entity @s[scores={AsaMatrix=96..101}] run tp @s ^0 ^-0.01666667 ^0
execute if entity @s[scores={AsaMatrix=102..}] run function asa_animator:kushala/anim/stride/end
execute as @e[type=armor_stand,tag=KushalaParts] run function #asa_matrix:animate
function asa_animator:kushala/model

execute if entity @s[scores={AsaMatrix=1}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7

execute if entity @s[scores={AsaMatrix=26..101}] run tp @s ^ ^ ^0.1

execute if entity @s[scores={AsaMatrix=37}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=53}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=69}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=85}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=101}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7