# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:diablos/dash/start
execute if score @s AsaMatrix matches 1 run function asa_animator:diablos/dash/keyframes/0
execute if score @s AsaMatrix matches 1..4 run tp @s ^0 ^0.075 ^0.875
execute if score @s AsaMatrix matches 5 run function asa_animator:diablos/dash/keyframes/1
execute if score @s AsaMatrix matches 5..8 run tp @s ^0 ^-0.075 ^0.875
execute if score @s AsaMatrix matches 9 run function asa_animator:diablos/dash/keyframes/2
execute if score @s AsaMatrix matches 9..12 run tp @s ^0 ^0.075 ^0.875
execute if score @s AsaMatrix matches 13 run function asa_animator:diablos/dash/keyframes/3
execute if score @s AsaMatrix matches 13..16 run tp @s ^0 ^-0.075 ^0.875
execute if score @s AsaMatrix matches 17.. run function asa_animator:diablos/dash/end
execute as @e[type=armor_stand,tag=DiablosParts] run function #asa_matrix:animate
function asa_animator:diablos/model
