# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:zinogre/anim/destroy_tail/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:zinogre/anim/destroy_tail/keyframes/0
execute if entity @s[scores={AsaMatrix=1..7}] run tp @s ^0 ^0.02857143 ^0.8 ~-3 ~
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:zinogre/anim/destroy_tail/keyframes/1
execute if entity @s[scores={AsaMatrix=8..14}] run tp @s ^0 ^0 ^0.6 ~-3 ~
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:zinogre/anim/destroy_tail/keyframes/2
execute if entity @s[scores={AsaMatrix=15..22}] run tp @s ^-0.3 ^-0.025 ^0.1 ~-12 ~
execute if entity @s[scores={AsaMatrix=23}] run function asa_animator:zinogre/anim/destroy_tail/keyframes/3
execute if entity @s[scores={AsaMatrix=23..38}] run tp @s ^0 ^0 ^-0.2 ~-6 ~
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:zinogre/anim/destroy_tail/keyframes/4
execute if entity @s[scores={AsaMatrix=39..40}] run tp @s ^0 ^0 ^-0.1 ~-1 ~
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:zinogre/anim/destroy_tail/keyframes/5
execute if entity @s[scores={AsaMatrix=41..55}] run tp @s ^0 ^0 ^0.06666667
execute if entity @s[scores={AsaMatrix=56..}] run function asa_animator:zinogre/anim/destroy_tail/end
execute as @e[type=armor_stand,tag=ZinogreParts] run function #asa_matrix:animate
function asa_animator:zinogre/model

execute if entity @s[scores={AsaMatrix=1}] at @s positioned ~ ~5 ~ run tp @s ~ ~ ~
execute if entity @s[scores={AsaMatrix=1}] at @s positioned ~ ~5 ~ run function asa_animator:zinogre/manager/check_ground

execute if entity @s[scores={AsaMatrix=23..40}] run playsound block.grass.step master @a ~ ~ ~ 2 0.5
execute if entity @s[scores={AsaMatrix=23..40}] run particle block grass_block ~ ~ ~ 1 0.1 1 0 3