# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:narga/anim/move_start/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:narga/anim/move_start/keyframes/0
execute if entity @s[scores={AsaMatrix=1..8}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:narga/anim/move_start/keyframes/1
execute if entity @s[scores={AsaMatrix=9..15}] run tp @s ^0 ^0 ^0.2
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:narga/anim/move_start/keyframes/2
execute if entity @s[scores={AsaMatrix=16..20}] run tp @s ^0 ^0 ^0.8
execute if entity @s[scores={AsaMatrix=21..}] run function asa_animator:narga/anim/move_start/end
execute as @e[type=armor_stand,tag=NargaParts] run function #asa_matrix:animate
function asa_animator:narga/model

execute if entity @s[scores={AsaMatrix=1..8}] run function asa_animator:narga/manager/rotate
execute if entity @s[scores={AsaMatrix=14}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7

execute if entity @s[tag=MoveLeft] if entity @s[scores={AsaMatrix=9..15}] at @s run tp @s ~ ~ ~ ~5 ~
execute if entity @s[tag=MoveLeft] if entity @s[scores={AsaMatrix=16..20}] at @s run tp @s ~ ~ ~ ~10 ~
execute unless entity @s[tag=MoveLeft] if entity @s[scores={AsaMatrix=9..15}] at @s run tp @s ~ ~ ~ ~-5 ~
execute unless entity @s[tag=MoveLeft] if entity @s[scores={AsaMatrix=16..20}] at @s run tp @s ~ ~ ~ ~-10 ~