# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:reus/flyingbreath/start
execute if score @s AsaMatrix matches 1 run function asa_animator:reus/flyingbreath/keyframes/0
execute if score @s AsaMatrix matches 1..10 run tp @s ^0 ^0.04 ^0.02
execute if score @s AsaMatrix matches 11 run function asa_animator:reus/flyingbreath/keyframes/1
execute if score @s AsaMatrix matches 11..20 run tp @s ^0 ^0.04 ^-0.06
execute if score @s AsaMatrix matches 21 run function asa_animator:reus/flyingbreath/keyframes/2
execute if score @s AsaMatrix matches 21..30 run tp @s ^0 ^-0.12 ^0.06
execute if score @s AsaMatrix matches 31 run function asa_animator:reus/flyingbreath/keyframes/3
execute if score @s AsaMatrix matches 31..45 run tp @s ^0 ^0.02666667 ^-0.01333333
execute if score @s AsaMatrix matches 46.. run function asa_animator:reus/flyingbreath/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model

# 敵を向く
execute if score @s AsaMatrix matches 1..10 run function asa_animator:reus/manager/rotate_fast

# 発射位置決定
execute if score @s AsaMatrix matches 11 at @e[tag=ReusAttackTarget,limit=1] run summon marker ~ ~ ~ {Tags:["ReusBreathTarget"]}

# ブレス発射
execute if score @s AsaMatrix matches 25 positioned ^ ^3 ^4 facing entity @e[type=marker,tag=ReusBreathTarget,limit=1] feet run function asa_animator:reus/breath/effect/attack

# 効果音
execute if score @s AsaMatrix matches 10 run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
execute if score @s AsaMatrix matches 30 run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7