# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:narga/anim/tail_shot/start
execute if score @s AsaMatrix matches 1 run function asa_animator:narga/anim/tail_shot/keyframes/0
execute if score @s AsaMatrix matches 1..7 run tp @s ^0 ^0.4285714 ^-0.3
execute if score @s AsaMatrix matches 8 run function asa_animator:narga/anim/tail_shot/keyframes/1
execute if score @s AsaMatrix matches 8..13 run tp @s ^0.05555555 ^-0.52 ^-0.3333333
execute if score @s AsaMatrix matches 14 run function asa_animator:narga/anim/tail_shot/keyframes/2
execute if score @s AsaMatrix matches 14..20 run tp @s ^0 ^0 ^-0.02
execute if score @s AsaMatrix matches 21 run function asa_animator:narga/anim/tail_shot/keyframes/3
execute if score @s AsaMatrix matches 21..26 run tp @s ^0 ^-0.001666666 ^0
execute if score @s AsaMatrix matches 27 run function asa_animator:narga/anim/tail_shot/keyframes/4
execute if score @s AsaMatrix matches 27..33 run tp @s ^0 ^-0.001428572 ^0
execute if score @s AsaMatrix matches 34 run function asa_animator:narga/anim/tail_shot/keyframes/5
execute if score @s AsaMatrix matches 34..40 run tp @s ^-0.0452381 ^0.005 ^0 ~1 ~
execute if score @s AsaMatrix matches 41 run function asa_animator:narga/anim/tail_shot/keyframes/6
execute if score @s AsaMatrix matches 41..45 run tp @s ^-0.06333333 ^0.006999999 ^-0.1 ~1 ~
execute if score @s AsaMatrix matches 46 run function asa_animator:narga/anim/tail_shot/keyframes/7
execute if score @s AsaMatrix matches 46..50 run tp @s ^-0.04 ^0.514 ^0.3
execute if score @s AsaMatrix matches 51 run function asa_animator:narga/anim/tail_shot/keyframes/8
execute if score @s AsaMatrix matches 51..57 run tp @s ^-0.04285714 ^-0.3671429 ^0.1428571 ~1 ~
execute if score @s AsaMatrix matches 58 run function asa_animator:narga/anim/tail_shot/keyframes/9
execute if score @s AsaMatrix matches 58..62 run tp @s ^0 ^0 ^-0.04000001 ~1 ~
execute if score @s AsaMatrix matches 63 run function asa_animator:narga/anim/tail_shot/keyframes/10
execute if score @s AsaMatrix matches 63..72 run tp @s ^0.04 ^0.0035 ^-0.03 ~-0.5 ~
execute if score @s AsaMatrix matches 73 run function asa_animator:narga/anim/tail_shot/keyframes/11
execute if score @s AsaMatrix matches 73..80 run tp @s ^0.05 ^0.004375 ^-0.0625 ~-0.5 ~
execute if score @s AsaMatrix matches 81.. run function asa_animator:narga/anim/tail_shot/end
execute as @e[type=armor_stand,tag=NargaParts] run function #asa_matrix:animate
function asa_animator:narga/model

execute if score @s AsaMatrix matches 1..35 run function asa_animator:narga/manager/rotate
execute if score @s AsaMatrix matches 46..52 run function asa_animator:narga/manager/rotate_fast

execute if score @s AsaMatrix matches 20 run playsound entity.player.attack.sweep master @a ~ ~ ~ 3 0.5
execute if score @s AsaMatrix matches 35 run playsound entity.player.attack.sweep master @a ~ ~ ~ 3 0.7

execute if score @s AsaMatrix matches 1 run function asa_animator:narga/manager/particle/jump
execute if score @s AsaMatrix matches 14 run function asa_animator:narga/manager/particle/jump
execute if score @s AsaMatrix matches 46 run function asa_animator:narga/manager/particle/jump
execute if score @s AsaMatrix matches 58 run function asa_animator:narga/manager/particle/jump

execute unless entity @s[tag=IsAnger] if score @s AsaMatrix matches 1 run function asa_animator:narga/anim/tail_bitan/events/change_to_anger
execute unless entity @s[tag=IsAnger] if score @s AsaMatrix matches 73 run function asa_animator:narga/anim/tail_bitan/events/change_to_normal

execute if score @s AsaMatrix matches 45 run function asa_animator:narga/anim/tail_shot/events/set_position
execute if score @s AsaMatrix matches 45 positioned ^ ^7 ^2 facing entity @e[type=marker,tag=NargaShotTarget] feet run function asa_animator:narga/anim/tail_shot/events/shot_0
execute if score @s AsaMatrix matches 57 positioned ^ ^8 ^2 facing entity @e[type=marker,tag=NargaShotTarget] feet run function asa_animator:narga/anim/tail_shot/events/shot_1