# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reia/anim/charge/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reia/anim/charge/keyframes/0
execute if entity @s[scores={AsaMatrix=1..10}] run tp @s ^0 ^-0.01 ^-0.05
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:reia/anim/charge/keyframes/1
execute if entity @s[scores={AsaMatrix=11..20}] run tp @s ^0 ^0 ^-0.3
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:reia/anim/charge/keyframes/2
execute if entity @s[scores={AsaMatrix=21..30}] run tp @s ^0 ^0 ^-0.2
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:reia/anim/charge/keyframes/3
execute if entity @s[scores={AsaMatrix=31..35}] run tp @s ^0 ^0 ^-0.1
execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:reia/anim/charge/keyframes/4
execute if entity @s[scores={AsaMatrix=36..40}] run tp @s ^0 ^0.02 ^0
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:reia/anim/charge/keyframes/5
execute if entity @s[scores={AsaMatrix=41..60}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=61}] run function asa_animator:reia/anim/charge/keyframes/6
execute if entity @s[scores={AsaMatrix=61..75}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=76..}] run function asa_animator:reia/anim/charge/end
execute as @e[type=armor_stand,tag=ReiaParts] run function #asa_matrix:animate
function asa_animator:reia/model

# 敵を向く
execute if entity @s[scores={AsaMatrix=1..12}] run function asa_animator:reia/manager/rotate

# 発射位置決定
execute if entity @s[scores={AsaMatrix=13}] run summon marker ^ ^0.7 ^8 {Tags:["ReiaBreathTarget"]}
execute if entity @s[scores={AsaMatrix=13}] unless entity @e[distance=0..8,tag=ReiaAttackTarget] at @e[tag=ReiaAttackTarget,limit=1] run tp @e[type=marker,tag=ReiaBreathTarget] ~ ~ ~

execute if entity @s[scores={AsaMatrix=1}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=1}] run playsound entity.player.breath master @a ~ ~ ~ 2 0.9
execute if entity @s[scores={AsaMatrix=18}] run playsound entity.iron_golem.step master @a ~ ~ ~ 2 0.9
execute if entity @s[scores={AsaMatrix=28}] run playsound entity.iron_golem.step master @a ~ ~ ~ 2 0.9

execute if entity @s[scores={AsaMatrix=1..39}] as @e[distance=0..15,type=armor_stand,tag=ReiaParts,tag=HeadU] at @s positioned ^ ^1.2 ^0.2 run particle flame ~ ~ ~ 0 0 0 0.03 5

# ブレス発射
execute if entity @s[scores={AsaMatrix=41}] positioned ^ ^1 ^5 facing entity @e[type=marker,tag=ReiaBreathTarget,limit=1] feet run function asa_animator:reia/anim/charge/events/shot
execute if entity @s[scores={AsaMatrix=41}] as @e[type=marker,tag=ReiaCharge] at @s positioned ^ ^ ^4 run function asa_animator:reia/anim/charge/events/damage
execute if entity @s[scores={AsaMatrix=45}] as @e[type=marker,tag=ReiaCharge] at @s positioned ^-4 ^ ^2 run function asa_animator:reia/anim/charge/events/damage
execute if entity @s[scores={AsaMatrix=49}] as @e[type=marker,tag=ReiaCharge] at @s positioned ^2.5 ^ ^-4 run function asa_animator:reia/anim/charge/events/damage
execute if entity @s[scores={AsaMatrix=53}] as @e[type=marker,tag=ReiaCharge] at @s positioned ^4 ^ ^3 run function asa_animator:reia/anim/charge/events/damage
execute if entity @s[scores={AsaMatrix=57}] as @e[type=marker,tag=ReiaCharge] at @s positioned ^-2 ^ ^-2 run function asa_animator:reia/anim/charge/events/damage
execute if entity @s[scores={AsaMatrix=57}] run kill @e[type=marker,tag=ReiaCharge]