# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:ruko/anim/gravity/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:ruko/anim/gravity/keyframes/0
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^0 ^-0.02 ^0 ~0.5 ~
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:ruko/anim/gravity/keyframes/1
execute if entity @s[scores={AsaMatrix=6..12}] run tp @s ^0 ^0.01428571 ^0
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:ruko/anim/gravity/keyframes/2
execute if entity @s[scores={AsaMatrix=13..17}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=18}] run function asa_animator:ruko/anim/gravity/keyframes/3
execute if entity @s[scores={AsaMatrix=18..23}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:ruko/anim/gravity/keyframes/4
execute if entity @s[scores={AsaMatrix=24..30}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:ruko/anim/gravity/keyframes/5
execute if entity @s[scores={AsaMatrix=31..36}] run tp @s ^0 ^-0.03333334 ^0
execute if entity @s[scores={AsaMatrix=37..}] run function asa_animator:ruko/anim/gravity/end
execute as @e[type=armor_stand,tag=RukoParts] run function #asa_matrix:animate
function asa_animator:ruko/model

execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:ruko/manager/particle/step

execute if entity @s[scores={AsaMatrix=13..18}] run playsound minecraft:entity.phantom.death master @a ~ ~ ~ 3 1.5
execute if entity @s[scores={AsaMatrix=13..18}] run playsound minecraft:entity.phantom.death master @a ~ ~ ~ 3 0.5
execute if entity @s[scores={AsaMatrix=13..18}] run playsound entity.skeleton_horse.death master @a ~ ~ ~ 3 2
execute if entity @s[scores={AsaMatrix=13..18}] run playsound entity.skeleton_horse.death master @a ~ ~ ~ 3 1.6

execute if entity @s[scores={AsaMatrix=13}] run playsound entity.evoker.cast_spell master @a ~ ~ ~ 3 1
execute if entity @s[scores={AsaMatrix=13..36}] run function asa_animator:ruko/manager/particle/pull
execute if entity @s[scores={AsaMatrix=13..36}] as @a[distance=3..20] unless entity @s[scores={MhdpTAvoid=1..}] unless entity @s[scores={MhdpTDamage=1..}] at @s facing entity @e[type=armor_stand,tag=RukoRoot] feet rotated ~ 0 positioned ^ ^ ^0.4 rotated as @s run function asa_animator:ruko/anim/gravity/events/move