# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:diablos/anim/anger/startdash1/start
execute if score @s AsaMatrix matches 1 run function asa_animator:diablos/anim/anger/startdash1/keyframes/0
execute if score @s AsaMatrix matches 1..4 run tp @s ^0 ^0 ^-0.125
execute if score @s AsaMatrix matches 5 run function asa_animator:diablos/anim/anger/startdash1/keyframes/1
execute if score @s AsaMatrix matches 5..26 run tp @s ^0 ^-0.009090909 ^-0.01363636
execute if score @s AsaMatrix matches 27 run function asa_animator:diablos/anim/anger/startdash1/keyframes/2
execute if score @s AsaMatrix matches 27..33 run tp @s ^0 ^-0.01428572 ^-0.01428571
execute if score @s AsaMatrix matches 34.. run function asa_animator:diablos/anim/anger/startdash1/end
execute as @e[type=armor_stand,tag=DiablosParts] run function #asa_matrix:animate
function asa_animator:diablos/model

# 敵を向く
execute if score @s AsaMatrix matches 1..33 run function asa_animator:diablos/manager/rotate

execute if score @s AsaMatrix matches 33 run playsound block.sand.place master @a ~ ~ ~ 3 1