# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:reus/anim/flying_move_back/start
execute if score @s AsaMatrix matches 1 run function asa_animator:reus/anim/flying_move_back/keyframes/0
execute if score @s AsaMatrix matches 1..10 run tp @s ^0 ^0.2 ^-0.4
execute if score @s AsaMatrix matches 11 run function asa_animator:reus/anim/flying_move_back/keyframes/1
execute if score @s AsaMatrix matches 11..28 run tp @s ^0 ^-0.09444445 ^-0.1111111
execute if score @s AsaMatrix matches 29.. run function asa_animator:reus/anim/flying_move_back/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model

function asa_animator:reus/manager/rotate
execute if score @s AsaMatrix matches 8 run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7