# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:brachyr/anim/punch_large_r/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:brachyr/anim/punch_large_r/keyframes/0
execute if entity @s[scores={AsaMatrix=1..7}] run tp @s ^0 ^0.02857143 ^-0.07142857
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:brachyr/anim/punch_large_r/keyframes/1
execute if entity @s[scores={AsaMatrix=8..14}] run tp @s ^0 ^0.01428572 ^-0.01428572
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:brachyr/anim/punch_large_r/keyframes/2
execute if entity @s[scores={AsaMatrix=15..18}] run tp @s ^0 ^0 ^-0.03749999
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:brachyr/anim/punch_large_r/keyframes/3
execute if entity @s[scores={AsaMatrix=19..24}] run tp @s ^0 ^-0.1 ^0.125 ~1.6 ~
execute if entity @s[scores={AsaMatrix=25}] run function asa_animator:brachyr/anim/punch_large_r/keyframes/4
execute if entity @s[scores={AsaMatrix=25..28}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:brachyr/anim/punch_large_r/keyframes/5
execute if entity @s[scores={AsaMatrix=29..34}] run tp @s ^0 ^0 ^0.03333334
execute if entity @s[scores={AsaMatrix=35}] run function asa_animator:brachyr/anim/punch_large_r/keyframes/6
execute if entity @s[scores={AsaMatrix=35..40}] run tp @s ^0 ^0 ^0 ~-1.6 ~
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:brachyr/anim/punch_large_r/keyframes/7
execute if entity @s[scores={AsaMatrix=41..45}] run tp @s ^0 ^0 ^0 ~-1.6 ~
execute if entity @s[scores={AsaMatrix=46}] run function asa_animator:brachyr/anim/punch_large_r/keyframes/8
execute if entity @s[scores={AsaMatrix=46..50}] run tp @s ^0 ^0 ^0 ~-1.6 ~
execute if entity @s[scores={AsaMatrix=51}] run function asa_animator:brachyr/anim/punch_large_r/keyframes/9
execute if entity @s[scores={AsaMatrix=51..58}] run tp @s ^0 ^0 ^-0.0125 ~2 ~
execute if entity @s[scores={AsaMatrix=59}] run function asa_animator:brachyr/anim/punch_large_r/keyframes/10
execute if entity @s[scores={AsaMatrix=59..76}] run tp @s ^0 ^0.01666667 ^-0.02222222
execute if entity @s[scores={AsaMatrix=77..}] run function asa_animator:brachyr/anim/punch_large_r/end
execute as @e[type=armor_stand,tag=BrachyRParts] run function #asa_matrix:animate
function asa_animator:brachyr/model

execute if entity @s[scores={AsaMatrix=1..9}] run function asa_animator:brachyr/manager/rotate
execute if entity @s[scores={AsaMatrix=1..14}] if entity @e[tag=BrachyAttackTarget,distance=0..5] at @s run tp @s ^ ^ ^-0.3
execute if entity @s[scores={AsaMatrix=18..24}] unless entity @e[tag=BrachyAttackTarget,distance=0..4] at @s run tp @s ^ ^ ^0.5
execute if entity @s[scores={AsaMatrix=25}] rotated ~35 ~ positioned ^ ^ ^3.5 run function asa_animator:brachyr/anim/punch_r/events/damage
execute if entity @s[scores={AsaMatrix=35}] rotated ~0 ~ positioned ^ ^ ^3 run function asa_animator:brachyr/anim/punch_r/events/damage
execute if entity @s[scores={AsaMatrix=45}] rotated ~-35 ~ positioned ^ ^ ^3 run function asa_animator:brachyr/anim/punch_r/events/damage
execute unless predicate asa_animator:brachyr/combo if entity @s[scores={AsaMatrix=54}] run function asa_animator:brachyr/manager/cancel_animation

execute if entity @s[scores={AsaMatrix=35..45}] as @e[type=armor_stand,tag=BrachyRParts,tag=ArmR1,distance=0..15] at @s run particle block grass_block ~ ~-0.5 ~ 1 0.1 1 0 10
execute if entity @s[scores={AsaMatrix=35..45}] run playsound block.grass.step master @a ~ ~ ~ 2 0.5