# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:tiga/anim/shot_l/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:tiga/anim/shot_l/keyframes/0
execute if entity @s[scores={AsaMatrix=1..8}] run tp @s ^0 ^0 ^-0.0125
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:tiga/anim/shot_l/keyframes/1
execute if entity @s[scores={AsaMatrix=9..14}] run tp @s ^0 ^0.01666667 ^0
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:tiga/anim/shot_l/keyframes/2
execute if entity @s[scores={AsaMatrix=15..20}] run tp @s ^0 ^0.01666667 ^-0.03333334
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:tiga/anim/shot_l/keyframes/3
execute if entity @s[scores={AsaMatrix=21..24}] run tp @s ^0 ^-0.05 ^0.05
execute if entity @s[scores={AsaMatrix=25}] run function asa_animator:tiga/anim/shot_l/keyframes/4
execute if entity @s[scores={AsaMatrix=25..28}] run tp @s ^0 ^-0.025 ^0.025
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:tiga/anim/shot_l/keyframes/5
execute if entity @s[scores={AsaMatrix=29..32}] run tp @s ^0 ^0 ^0.05
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:tiga/anim/shot_l/keyframes/6
execute if entity @s[scores={AsaMatrix=33..42}] run tp @s ^0 ^0 ^0.02 ~-0.5 ~
execute if entity @s[scores={AsaMatrix=43}] run function asa_animator:tiga/anim/shot_l/keyframes/7
execute if entity @s[scores={AsaMatrix=43..57}] run tp @s ^0 ^0.006666667 ^-0.06 ~0.5 ~
execute if entity @s[scores={AsaMatrix=58..}] run function asa_animator:tiga/anim/shot_l/end
execute as @e[type=armor_stand,tag=TigaParts] run function #asa_matrix:animate
function asa_animator:tiga/model

execute if entity @s[scores={AsaMatrix=1..8}] run function asa_animator:tiga/manager/rotate
execute if entity @s[scores={AsaMatrix=1}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=24}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=28}] run playsound entity.wither.break_block master @a ~ ~ ~ 2 0.5
execute if entity @s[scores={AsaMatrix=24..28}] positioned ^3 ^ ^5 run function asa_animator:tiga/anim/shot_l/events/damage
execute if entity @s[scores={AsaMatrix=28}] positioned ^3 ^ ^5 facing entity @e[tag=TigaAttackTarget] eyes run function asa_animator:tiga/anim/shot_l/events/shot/start