# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:diablos/anim/anger/dash_attack/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:diablos/anim/anger/dash_attack/keyframes/0
execute if entity @s[scores={AsaMatrix=1..4}] run tp @s ^0 ^0 ^0.5
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:diablos/anim/anger/dash_attack/keyframes/1
execute if entity @s[scores={AsaMatrix=5..8}] run tp @s ^0 ^0 ^0.25
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:diablos/anim/anger/dash_attack/keyframes/2
execute if entity @s[scores={AsaMatrix=9..14}] run tp @s ^0 ^0 ^0.03333334
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:diablos/anim/anger/dash_attack/keyframes/3
execute if entity @s[scores={AsaMatrix=15..19}] run tp @s ^0 ^0 ^-0.04000001
execute if entity @s[scores={AsaMatrix=20}] run function asa_animator:diablos/anim/anger/dash_attack/keyframes/4
execute if entity @s[scores={AsaMatrix=20..30}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:diablos/anim/anger/dash_attack/keyframes/5
execute if entity @s[scores={AsaMatrix=31..39}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=40}] run function asa_animator:diablos/anim/anger/dash_attack/keyframes/6
execute if entity @s[scores={AsaMatrix=40..47}] run tp @s ^0 ^0.0375 ^-0.0625
execute if entity @s[scores={AsaMatrix=48..}] run function asa_animator:diablos/anim/anger/dash_attack/end
execute as @e[type=armor_stand,tag=DiablosParts] run function #asa_matrix:animate
function asa_animator:diablos/model
