# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:brachy/anim/head_bomb/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:brachy/anim/head_bomb/keyframes/0
execute if entity @s[scores={AsaMatrix=1..10}] run tp @s ^0 ^0.03 ^-0.02
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:brachy/anim/head_bomb/keyframes/1
execute if entity @s[scores={AsaMatrix=11..20}] run tp @s ^0 ^0.01 ^-0.02
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:brachy/anim/head_bomb/keyframes/2
execute if entity @s[scores={AsaMatrix=21..23}] run tp @s ^0 ^0.05 ^0.1166667
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:brachy/anim/head_bomb/keyframes/3
execute if entity @s[scores={AsaMatrix=24..26}] run tp @s ^0 ^-0.15 ^0.15
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:brachy/anim/head_bomb/keyframes/4
execute if entity @s[scores={AsaMatrix=27..28}] run tp @s ^0 ^0.05 ^0.1
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:brachy/anim/head_bomb/keyframes/5
execute if entity @s[scores={AsaMatrix=29..35}] run tp @s ^0 ^-0.04285714 ^-0.05714286
execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:brachy/anim/head_bomb/keyframes/6
execute if entity @s[scores={AsaMatrix=36..47}] run tp @s ^0 ^0.004166667 ^-0.1 ~0.5 ~
execute if entity @s[scores={AsaMatrix=48}] run function asa_animator:brachy/anim/head_bomb/keyframes/7
execute if entity @s[scores={AsaMatrix=48..59}] run tp @s ^0 ^0.004166667 ^0.0125 ~-0.5 ~
execute if entity @s[scores={AsaMatrix=60..}] run function asa_animator:brachy/anim/head_bomb/end
execute as @e[type=armor_stand,tag=BrachyParts] run function #asa_matrix:animate
function asa_animator:brachy/model

execute if entity @s[scores={AsaMatrix=1}] run playsound block.grass.step master @a ~ ~ ~ 2 0.5

execute if entity @s[scores={AsaMatrix=1..10}] run function asa_animator:brachy/manager/rotate
execute if entity @s[scores={AsaMatrix=1..5}] if entity @e[tag=BrachyAttackTarget,distance=0..5] at @s run tp @s ^ ^ ^-0.5
execute if entity @s[scores={AsaMatrix=16..25}] unless entity @e[tag=BrachyAttackTarget,distance=0..4] at @s run tp @s ^ ^ ^0.3

execute if entity @s[scores={AsaMatrix=26}] positioned ^ ^ ^3.5 run function asa_animator:brachy/anim/head_bomb/events/damage

execute if entity @s[scores={AsaMatrix=47..}] run function asa_animator:brachy/manager/ground