# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:tiga/anim/anger/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:tiga/anim/anger/keyframes/0
execute if entity @s[scores={AsaMatrix=1..4}] run tp @s ^0 ^0.025 ^-0.025
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:tiga/anim/anger/keyframes/1
execute if entity @s[scores={AsaMatrix=5..8}] run tp @s ^0 ^-0.025 ^-0.025
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:tiga/anim/anger/keyframes/2
execute if entity @s[scores={AsaMatrix=9..12}] run tp @s ^0 ^0.025 ^-0.025
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:tiga/anim/anger/keyframes/3
execute if entity @s[scores={AsaMatrix=13..16}] run tp @s ^0 ^-0.025 ^-0.025
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:tiga/anim/anger/keyframes/4
execute if entity @s[scores={AsaMatrix=17..27}] run tp @s ^0 ^0.01818182 ^-0.01818182
execute if entity @s[scores={AsaMatrix=28}] run function asa_animator:tiga/anim/anger/keyframes/5
execute if entity @s[scores={AsaMatrix=28..33}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=34}] run function asa_animator:tiga/anim/anger/keyframes/6
execute if entity @s[scores={AsaMatrix=34..38}] run tp @s ^0 ^0.02 ^0
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:tiga/anim/anger/keyframes/7
execute if entity @s[scores={AsaMatrix=39..60}] run tp @s ^0 ^0.004545454 ^0
execute if entity @s[scores={AsaMatrix=61}] run function asa_animator:tiga/anim/anger/keyframes/8
execute if entity @s[scores={AsaMatrix=61..75}] run tp @s ^0 ^-0.02666667 ^0.04
execute if entity @s[scores={AsaMatrix=76..}] run function asa_animator:tiga/anim/voice_2/end
execute as @e[type=armor_stand,tag=TigaParts] run function #asa_matrix:animate
function asa_animator:tiga/model

execute if entity @s[scores={AsaMatrix=8}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=16}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=27}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7

execute if entity @s[scores={AsaMatrix=38..60}] positioned ^ ^5.2 ^4.5 run particle flash ~ ~ ~ 0 0 0 0 1
execute if entity @s[scores={AsaMatrix=38..70}] run playsound entity.hoglin.attack master @a ~ ~ ~ 3 2
execute if entity @s[scores={AsaMatrix=38..70}] run playsound entity.hoglin.attack master @a ~ ~ ~ 3 1.2
execute if entity @s[scores={AsaMatrix=38..70}] run playsound entity.hoglin.attack master @a ~ ~ ~ 3 0.7
execute if entity @s[scores={AsaMatrix=38..40}] run playsound entity.ender_dragon.growl master @a ~ ~ ~ 3 0.9
execute if entity @s[scores={AsaMatrix=38..40}] run playsound entity.ender_dragon.growl master @a ~ ~ ~ 3 0.7

execute if entity @s[scores={AsaMatrix=38}] run function asa_animator:tiga/anim/voice/events/damage