# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/hard_jump_to_bjb/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/hard_jump_to_bjb/keyframes/0
execute if entity @s[scores={AsaMatrix=1..10}] run tp @s ^0 ^0 ^-0.01
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:reus/anim/hard_jump_to_bjb/keyframes/1
execute if entity @s[scores={AsaMatrix=11..15}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:reus/anim/hard_jump_to_bjb/keyframes/2
execute if entity @s[scores={AsaMatrix=16..25}] run tp @s ^0 ^0.5 ^-0.59
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:reus/anim/hard_jump_to_bjb/keyframes/3
execute if entity @s[scores={AsaMatrix=26..35}] run tp @s ^0 ^-0.25 ^-0.05
execute if entity @s[scores={AsaMatrix=36..}] run function asa_animator:reus/anim/hard_jump_to_bjb/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model

# 移動
    execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/manager/model/change_to_fly
    execute if entity @s[scores={AsaMatrix=1..12}] run function asa_animator:reus/manager/rotate

# 演出
    execute if entity @s[scores={AsaMatrix=23}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7

# 攻撃
    execute if entity @s[scores={AsaMatrix=13}] run summon marker ^ ^5 ^12 {Tags:["ReusBreathTarget"]}
    execute if entity @s[scores={AsaMatrix=13}] as @e[type=marker,tag=ReusBreathTarget] at @s run function asa_animator:zinogre/manager/check_ground
    execute if entity @s[scores={AsaMatrix=16}] positioned ^ ^ ^3 as @a[distance=0..5] run function mh_dp:player/knockback/start_wind
    execute if entity @s[scores={AsaMatrix=18}] positioned ^ ^4 ^3 facing entity @e[type=marker,tag=ReusBreathTarget,limit=1] feet run function asa_animator:reus/anim/breath/events/shot
