# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:reus/anim/bjb/start
execute if score @s AsaMatrix matches 1 run function asa_animator:reus/anim/bjb/keyframes/0
execute if score @s AsaMatrix matches 1..5 run tp @s ^0 ^0 ^-0.02
execute if score @s AsaMatrix matches 6 run function asa_animator:reus/anim/bjb/keyframes/1
execute if score @s AsaMatrix matches 6..15 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 16 run function asa_animator:reus/anim/bjb/keyframes/2
execute if score @s AsaMatrix matches 16..25 run tp @s ^0 ^0.5 ^-0.59
execute if score @s AsaMatrix matches 26 run function asa_animator:reus/anim/bjb/keyframes/3
execute if score @s AsaMatrix matches 26..35 run tp @s ^0 ^-0.25 ^-0.05
execute if score @s AsaMatrix matches 36.. run function asa_animator:reus/anim/bjb/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model

# 敵を向く
execute if score @s AsaMatrix matches 1..12 run function asa_animator:reus/manager/rotate

# 発射位置決定
execute if score @s AsaMatrix matches 13 run summon marker ^ ^0.7 ^8 {Tags:["ReusBreathTarget"]}
execute if score @s AsaMatrix matches 13 unless entity @e[distance=0..8,tag=ReusAttackTarget] at @e[tag=ReusAttackTarget,limit=1] run tp @e[type=marker,tag=ReusBreathTarget] ~ ~ ~

# ブレス発射
execute if score @s AsaMatrix matches 18 positioned ^ ^4 ^3 facing entity @e[type=marker,tag=ReusBreathTarget,limit=1] feet run function asa_animator:reus/anim/breath/events/shot
execute if score @s AsaMatrix matches 23 run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7