# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:diablos/anim/normal/tackle/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:diablos/anim/normal/tackle/keyframes/0
execute if entity @s[scores={AsaMatrix=1..12}] run tp @s ^0 ^-0.025 ^-0.04166667
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:diablos/anim/normal/tackle/keyframes/1
execute if entity @s[scores={AsaMatrix=13..26}] run tp @s ^0 ^-0.007142857 ^-0.02142857
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:diablos/anim/normal/tackle/keyframes/2
execute if entity @s[scores={AsaMatrix=27..32}] run tp @s ^0.1666667 ^0 ^0.9666667
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:diablos/anim/normal/tackle/keyframes/3
execute if entity @s[scores={AsaMatrix=33..38}] run tp @s ^0 ^0 ^0.6666667
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:diablos/anim/normal/tackle/keyframes/4
execute if entity @s[scores={AsaMatrix=39..48}] run tp @s ^0 ^-0.01 ^0.05
execute if entity @s[scores={AsaMatrix=49}] run function asa_animator:diablos/anim/normal/tackle/keyframes/5
execute if entity @s[scores={AsaMatrix=49..65}] run tp @s ^-0.05882353 ^0.02941176 ^-0.02941176 ~-1 ~
execute if entity @s[scores={AsaMatrix=66..}] run function asa_animator:diablos/anim/normal/tackle/end
execute as @e[type=armor_stand,tag=DiablosParts] run function #asa_matrix:animate
function asa_animator:diablos/model

execute if entity @s[scores={AsaMatrix=1..12}] run function asa_animator:diablos/manager/rotate

execute if entity @s[scores={AsaMatrix=32}] run playsound entity.iron_golem.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=38}] run playsound entity.iron_golem.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=44}] run playsound entity.iron_golem.step master @a ~ ~ ~ 2 0.7

execute if entity @s[scores={AsaMatrix=27..48}] run function asa_animator:diablos/anim/normal/tackle/events/damage