# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:ruko/anim/sp_damage/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:ruko/anim/sp_damage/keyframes/0
execute if entity @s[scores={AsaMatrix=1..7}] run tp @s ^0 ^-0.01428571 ^0 ~0.5 ~
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:ruko/anim/sp_damage/keyframes/1
execute if entity @s[scores={AsaMatrix=8..20}] run tp @s ^0 ^0.007692308 ^0
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:ruko/anim/sp_damage/keyframes/2
execute if entity @s[scores={AsaMatrix=21..27}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=28}] run function asa_animator:ruko/anim/sp_damage/keyframes/3
execute if entity @s[scores={AsaMatrix=28..38}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:ruko/anim/sp_damage/keyframes/4
execute if entity @s[scores={AsaMatrix=39..55}] run tp @s ^0 ^-0.08235294 ^0.01176471 ~-5 ~
execute if entity @s[scores={AsaMatrix=56}] run function asa_animator:ruko/anim/sp_damage/keyframes/5
execute if entity @s[scores={AsaMatrix=56..63}] run tp @s ^0 ^0 ^0 ~-1 ~
execute if entity @s[scores={AsaMatrix=64}] run function asa_animator:ruko/anim/sp_damage/keyframes/6
execute if entity @s[scores={AsaMatrix=64..88}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=89}] run function asa_animator:ruko/anim/sp_damage/keyframes/7
execute if entity @s[scores={AsaMatrix=89..99}] run tp @s ^0 ^0.07272727 ^-0.009090909 ~4 ~
execute if entity @s[scores={AsaMatrix=100}] run function asa_animator:ruko/anim/sp_damage/keyframes/8
execute if entity @s[scores={AsaMatrix=100..110}] run tp @s ^0 ^0.03636364 ^-0.009090909 ~2 ~
execute if entity @s[scores={AsaMatrix=111}] run function asa_animator:ruko/anim/sp_damage/keyframes/9
execute if entity @s[scores={AsaMatrix=111..122}] run tp @s ^0 ^0.01666667 ^0 ~1 ~
execute if entity @s[scores={AsaMatrix=123..}] run function asa_animator:ruko/anim/sp_damage/end
execute as @e[type=armor_stand,tag=RukoParts] run function #asa_matrix:animate
function asa_animator:ruko/model

execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:ruko/manager/particle/step
execute if entity @s[scores={AsaMatrix=39}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=55}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=89}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7

execute if entity @s[scores={AsaMatrix=15..20}] run playsound minecraft:entity.phantom.death master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=15..20}] run playsound entity.skeleton_horse.death master @a ~ ~ ~ 3 1.5
execute if entity @s[scores={AsaMatrix=15..20}] run playsound entity.skeleton_horse.death master @a ~ ~ ~ 3 1.7