# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:tiga/anim_anger/dash_turn_r_n/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:tiga/anim_anger/dash_turn_r_n/keyframes/0
execute if entity @s[scores={AsaMatrix=1..4}] run tp @s ^0 ^-0.025 ^0
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:tiga/anim_anger/dash_turn_r_n/keyframes/1
execute if entity @s[scores={AsaMatrix=5..10}] run tp @s ^0 ^0 ^-0.1666667 ~-0.1 ~
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:tiga/anim_anger/dash_turn_r_n/keyframes/2
execute if entity @s[scores={AsaMatrix=11..19}] run tp @s ^0 ^0 ^-0.05555556 ~-0.1 ~
execute if entity @s[scores={AsaMatrix=20}] run function asa_animator:tiga/anim_anger/dash_turn_r_n/keyframes/3
execute if entity @s[scores={AsaMatrix=20..22}] run tp @s ^0 ^0.02222222 ^0.1666667
execute if entity @s[scores={AsaMatrix=23}] run function asa_animator:tiga/anim_anger/dash_turn_r_n/keyframes/4
execute if entity @s[scores={AsaMatrix=23..25}] run tp @s ^0 ^0.02222222 ^0.1666667
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:tiga/anim_anger/dash_turn_r_n/keyframes/5
execute if entity @s[scores={AsaMatrix=26..29}] run tp @s ^0 ^0.01666667 ^0.125
execute if entity @s[scores={AsaMatrix=30}] run function asa_animator:tiga/anim_anger/dash_turn_r_n/keyframes/6
execute if entity @s[scores={AsaMatrix=30..32}] run tp @s ^0 ^-0.03333334 ^0
execute if entity @s[scores={AsaMatrix=33..}] run function asa_animator:tiga/anim/dash_turn_r_n/end
execute as @e[type=armor_stand,tag=TigaParts] run function #asa_matrix:animate
function asa_animator:tiga/model

function asa_animator:tiga/manager/rotate

execute if entity @s[scores={AsaMatrix=1..10}] at @s run tp @s ^ ^ ^-0.5
execute if entity @s[scores={AsaMatrix=11..19}] at @s run tp @s ^ ^ ^-0.2
execute if entity @s[scores={AsaMatrix=1..19}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7

particle block grass_block ~ ~0.3 ~ 1 0 1 0 5
execute if entity @s[scores={AsaMatrix=25}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.5
execute if entity @s[scores={AsaMatrix=32}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.5