# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:nazuti/anim/tongue_c/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:nazuti/anim/tongue_c/keyframes/0
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:nazuti/anim/tongue_c/keyframes/1
execute if entity @s[scores={AsaMatrix=6..15}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:nazuti/anim/tongue_c/keyframes/2
execute if entity @s[scores={AsaMatrix=16..20}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:nazuti/anim/tongue_c/keyframes/3
execute if entity @s[scores={AsaMatrix=21..25}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:nazuti/anim/tongue_c/keyframes/4
execute if entity @s[scores={AsaMatrix=26..30}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:nazuti/anim/tongue_c/keyframes/5
execute if entity @s[scores={AsaMatrix=31..40}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=41..}] run function asa_animator:nazuti/anim/tongue_c/end
execute as @e[type=armor_stand,tag=NazutiParts] run function #asa_matrix:animate
function asa_animator:nazuti/model

execute if entity @s[scores={AsaMatrix=1..20}] at @s run function asa_animator:nazuti/manager/rotate
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:nazuti/anim/tongue_l/events/start