# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:tiga/anim/jump/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:tiga/anim/jump/keyframes/0
execute if entity @s[scores={AsaMatrix=1..7}] run tp @s ^0 ^0 ^-0.02857143
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:tiga/anim/jump/keyframes/1
execute if entity @s[scores={AsaMatrix=8..15}] run tp @s ^0 ^0 ^-0.0125
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:tiga/anim/jump/keyframes/2
execute if entity @s[scores={AsaMatrix=16..20}] run tp @s ^0 ^1 ^0
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:tiga/anim/jump/keyframes/3
execute if entity @s[scores={AsaMatrix=21..25}] run tp @s ^0 ^0.6 ^0
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:tiga/anim/jump/keyframes/4
execute if entity @s[scores={AsaMatrix=26..30}] run tp @s ^0 ^-0.66 ^0
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:tiga/anim/jump/keyframes/5
execute if entity @s[scores={AsaMatrix=31..35}] run tp @s ^0 ^-1.06 ^0
execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:tiga/anim/jump/keyframes/6
execute if entity @s[scores={AsaMatrix=36..43}] run tp @s ^0 ^0 ^0.4 ~-0.5 ~
execute if entity @s[scores={AsaMatrix=44}] run function asa_animator:tiga/anim/jump/keyframes/7
execute if entity @s[scores={AsaMatrix=44..52}] run tp @s ^0 ^0 ^0.1
execute if entity @s[scores={AsaMatrix=53}] run function asa_animator:tiga/anim/jump/keyframes/8
execute if entity @s[scores={AsaMatrix=53..62}] run tp @s ^0 ^0.06 ^-0.07
execute if entity @s[scores={AsaMatrix=63..}] run function asa_animator:tiga/anim/jump/end
execute as @e[type=armor_stand,tag=TigaParts] run function #asa_matrix:animate
function asa_animator:tiga/model

execute if entity @s[scores={AsaMatrix=1}] run playsound block.grass.step master @a ~ ~ ~ 2 0.5
execute if entity @s[scores={AsaMatrix=1..10}] run function asa_animator:tiga/manager/rotate
execute if entity @s[scores={AsaMatrix=10}] run function asa_animator:tiga/anim/jump/events/pos/set_pos
execute if entity @s[scores={AsaMatrix=15}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=15}] run particle block grass_block ~ ~0.1 ~ 1 0.1 1 0 30
execute if entity @s[scores={AsaMatrix=15..34}] run function asa_animator:tiga/anim/jump/events/pos/offset
execute if entity @s[scores={AsaMatrix=35}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=35}] run particle block grass_block ~ ~0.1 ~ 1 0.1 1 0 30
execute if entity @s[scores={AsaMatrix=35..42}] run playsound block.grass.step master @a ~ ~ ~ 2 0.5
execute if entity @s[scores={AsaMatrix=18..42}] run function asa_animator:tiga/anim/jump/events/damage

execute if entity @s[scores={AsaMatrix=15}] run playsound entity.hoglin.attack master @a ~ ~ ~ 3 2
execute if entity @s[scores={AsaMatrix=15}] run playsound entity.hoglin.attack master @a ~ ~ ~ 3 1.2
execute if entity @s[scores={AsaMatrix=15}] run playsound entity.hoglin.attack master @a ~ ~ ~ 3 0.7