# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:kushala/anim/breath_up_2/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:kushala/anim/breath_up_2/keyframes/0
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^0 ^-0.02 ^0.04
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:kushala/anim/breath_up_2/keyframes/1
execute if entity @s[scores={AsaMatrix=6..15}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:kushala/anim/breath_up_2/keyframes/2
execute if entity @s[scores={AsaMatrix=16..21}] run tp @s ^0 ^0.01666667 ^0
execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:kushala/anim/breath_up_2/keyframes/3
execute if entity @s[scores={AsaMatrix=22..29}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=30}] run function asa_animator:kushala/anim/breath_up_2/keyframes/4
execute if entity @s[scores={AsaMatrix=30..34}] run tp @s ^0 ^-0.02 ^0
execute if entity @s[scores={AsaMatrix=35}] run function asa_animator:kushala/anim/breath_up_2/keyframes/5
execute if entity @s[scores={AsaMatrix=35..40}] run tp @s ^0 ^0.01666667 ^0
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:kushala/anim/breath_up_2/keyframes/6
execute if entity @s[scores={AsaMatrix=41..48}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=49}] run function asa_animator:kushala/anim/breath_up_2/keyframes/7
execute if entity @s[scores={AsaMatrix=49..62}] run tp @s ^0 ^0 ^-0.01428571
execute if entity @s[scores={AsaMatrix=63..}] run function asa_animator:kushala/anim/breath_up_2/end
execute as @e[type=armor_stand,tag=KushalaParts] run function #asa_matrix:animate
function asa_animator:kushala/model

execute if entity @s[scores={AsaMatrix=1..16}] run function asa_animator:kushala/manager/rotate

execute if entity @s[scores={AsaMatrix=22}] positioned ^ ^6 ^4 run function asa_animator:kushala/anim/breath_up/events/shot
execute if entity @s[scores={AsaMatrix=41}] positioned ^ ^6 ^4 run function asa_animator:kushala/anim/breath_up/events/shot