# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:dyno/anim/slash_large_l/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:dyno/anim/slash_large_l/keyframes/0
execute if entity @s[scores={AsaMatrix=1..4}] run tp @s ^0 ^0 ^0 ~-1 ~
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:dyno/anim/slash_large_l/keyframes/1
execute if entity @s[scores={AsaMatrix=5..8}] run tp @s ^0.025 ^-0.025 ^0 ~-1 ~
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:dyno/anim/slash_large_l/keyframes/2
execute if entity @s[scores={AsaMatrix=9..20}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:dyno/anim/slash_large_l/keyframes/3
execute if entity @s[scores={AsaMatrix=21..25}] run tp @s ^-0.02 ^0.05 ^0 ~22 ~
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:dyno/anim/slash_large_l/keyframes/4
execute if entity @s[scores={AsaMatrix=26..30}] run tp @s ^-0.02 ^0.03 ^0 ~4 ~
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:dyno/anim/slash_large_l/keyframes/5
execute if entity @s[scores={AsaMatrix=31..40}] run tp @s ^0 ^0.01 ^-0.05 ~3 ~
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:dyno/anim/slash_large_l/keyframes/6
execute if entity @s[scores={AsaMatrix=41..45}] run tp @s ^0.05 ^0 ^0 ~2 ~
execute if entity @s[scores={AsaMatrix=46}] run function asa_animator:dyno/anim/slash_large_l/keyframes/7
execute if entity @s[scores={AsaMatrix=46..60}] run tp @s ^0.005 ^-0.02 ^0.025 ~1 ~
execute if entity @s[scores={AsaMatrix=61}] run function asa_animator:dyno/anim/slash_large_l/keyframes/8
execute if entity @s[scores={AsaMatrix=61..70}] run tp @s ^0.005 ^-0.02 ^0.025
execute if entity @s[scores={AsaMatrix=71..}] run function asa_animator:dyno/anim/slash_large_l/end
execute as @e[type=armor_stand,tag=DynoParts] run function #asa_matrix:animate
function asa_animator:dyno/model

execute if entity @s[scores={AsaMatrix=20}] run playsound item.trident.throw master @a ~ ~ ~ 2 0.5

execute if entity @s[scores={AsaMatrix=21..40}] run function asa_animator:dyno/manager/particle/jump
execute if entity @s[scores={AsaMatrix=21..30}] at @s run tp @s ^0.3 ^ ^-0.5
execute if entity @s[scores={AsaMatrix=31..35}] at @s run tp @s ^0.1 ^ ^-0.3
execute if entity @s[scores={AsaMatrix=36..40}] at @s run tp @s ^0.05 ^ ^-0.1

execute if entity @s[scores={AsaMatrix=21}] positioned ^ ^2 ^ run function asa_animator:dyno/anim/slash_large_l/events/particle
execute if entity @s[tag=IsHeatTail] if entity @s[scores={AsaMatrix=21}] positioned ^ ^2 ^ run function asa_animator:dyno/anim/slash_large_l/events/particle_heat
execute if entity @s[tag=IsHeatTail] if entity @s[scores={AsaMatrix=21}] positioned ^ ^2 ^ run function asa_animator:dyno/anim/slash_large_l/events/particle_round
execute if entity @s[scores={AsaMatrix=21}] positioned ^ ^ ^-5 run function asa_animator:dyno/anim/slash_large_l/events/damage
execute if entity @s[scores={AsaMatrix=23}] positioned ^5 ^ ^ run function asa_animator:dyno/anim/slash_large_l/events/damage