# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:reus/flying/start
execute if score @s AsaMatrix matches 1 run function asa_animator:reus/flying/keyframes/0
execute if score @s AsaMatrix matches 16 run function asa_animator:reus/flying/keyframes/1
execute if score @s AsaMatrix matches 31.. run function asa_animator:reus/flying_height/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model

# ターゲットとの高度差を計算
function asa_animator:reus/flying_height/effect/move

# 効果音
execute if score @s AsaMatrix matches 15 run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7