# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:narga/anim/jump_move_l_anger/start
execute if score @s AsaMatrix matches 1 run function asa_animator:narga/anim/jump_move_l_anger/keyframes/0
execute if score @s AsaMatrix matches 1..5 run tp @s ^-0.06666666 ^-0.024 ^-0.1
execute if score @s AsaMatrix matches 6 run function asa_animator:narga/anim/jump_move_l_anger/keyframes/1
execute if score @s AsaMatrix matches 6..11 run tp @s ^0.05555555 ^0.52 ^0.08333334
execute if score @s AsaMatrix matches 12 run function asa_animator:narga/anim/jump_move_l_anger/keyframes/2
execute if score @s AsaMatrix matches 12..15 run tp @s ^0 ^-0.375 ^0
execute if score @s AsaMatrix matches 16 run function asa_animator:narga/anim/jump_move_l_anger/keyframes/3
execute if score @s AsaMatrix matches 16..20 run tp @s ^0.05 ^-0.318 ^-0.1
execute if score @s AsaMatrix matches 21 run function asa_animator:narga/anim/jump_move_l_anger/keyframes/4
execute if score @s AsaMatrix matches 21..28 run tp @s ^0.03125 ^-0.01125 ^-0.0625
execute if score @s AsaMatrix matches 29.. run function asa_animator:narga/anim/jump_move_l_anger/end
execute as @e[type=armor_stand,tag=NargaParts] run function #asa_matrix:animate
function asa_animator:narga/model

function asa_animator:narga/manager/rotate
execute if score @s AsaMatrix matches 6 run function asa_animator:narga/manager/particle/jump
execute if score @s AsaMatrix matches 21 run function asa_animator:narga/manager/particle/jump
execute if score @s AsaMatrix matches 5 run function asa_animator:narga/anim/jump_move_l/events/pos/set_pos
execute if score @s AsaMatrix matches 6..20 run function asa_animator:narga/anim/jump_move_l/events/pos/offset

execute if score @s AsaMatrix matches 20 run function asa_animator:narga/anim/blade_r_anger/events/pos/set_pos