# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:ruko/anim/breath_2/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:ruko/anim/breath_2/keyframes/0
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^0 ^0.06 ^0
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:ruko/anim/breath_2/keyframes/1
execute if entity @s[scores={AsaMatrix=6..12}] run tp @s ^0 ^-0.02857143 ^0
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:ruko/anim/breath_2/keyframes/2
execute if entity @s[scores={AsaMatrix=13..22}] run tp @s ^0 ^-0.01 ^-0.1
execute if entity @s[scores={AsaMatrix=23}] run function asa_animator:ruko/anim/breath_2/keyframes/3
execute if entity @s[scores={AsaMatrix=23..31}] run tp @s ^0 ^0.01111111 ^-0.2
execute if entity @s[scores={AsaMatrix=32}] run function asa_animator:ruko/anim/breath_2/keyframes/4
execute if entity @s[scores={AsaMatrix=32..37}] run tp @s ^0 ^-0.03333334 ^-0.05
execute if entity @s[scores={AsaMatrix=38}] run function asa_animator:ruko/anim/breath_2/keyframes/5
execute if entity @s[scores={AsaMatrix=38..44}] run tp @s ^0 ^0.05714286 ^0
execute if entity @s[scores={AsaMatrix=45}] run function asa_animator:ruko/anim/breath_2/keyframes/6
execute if entity @s[scores={AsaMatrix=45..51}] run tp @s ^0 ^-0.02857143 ^-0.1
execute if entity @s[scores={AsaMatrix=52}] run function asa_animator:ruko/anim/breath_2/keyframes/7
execute if entity @s[scores={AsaMatrix=52..61}] run tp @s ^0 ^-0.01 ^-0.2
execute if entity @s[scores={AsaMatrix=62}] run function asa_animator:ruko/anim/breath_2/keyframes/8
execute if entity @s[scores={AsaMatrix=62..71}] run tp @s ^0 ^0.01 ^-0.05
execute if entity @s[scores={AsaMatrix=72}] run function asa_animator:ruko/anim/breath_2/keyframes/9
execute if entity @s[scores={AsaMatrix=72..77}] run tp @s ^0 ^-0.03333334 ^0.06666667
execute if entity @s[scores={AsaMatrix=78}] run function asa_animator:ruko/anim/breath_2/keyframes/10
execute if entity @s[scores={AsaMatrix=78..79}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=80}] run function asa_animator:ruko/anim/breath_2/keyframes/11
execute if entity @s[scores={AsaMatrix=80..94}] run tp @s ^0 ^0.006666667 ^-0.04
execute if entity @s[scores={AsaMatrix=95..}] run function asa_animator:ruko/anim/breath_2/end
execute as @e[type=armor_stand,tag=RukoParts] run function #asa_matrix:animate
function asa_animator:ruko/model

execute at @s if block ~ ~-0.1 ~ #asa_animator:no_collision at @s run function asa_animator:zinogre/manager/check_ground
execute at @s unless block ~ ~0.1 ~ #asa_animator:no_collision at @s run tp @s ~ ~0.1 ~ ~ ~

execute if entity @s[scores={AsaMatrix=1..19}] run function asa_animator:ruko/manager/rotate

execute if entity @s[scores={AsaMatrix=4}] run playsound entity.lightning_bolt.thunder master @a ~ ~ ~ 3 0.7
execute if entity @s[scores={AsaMatrix=4}] run playsound entity.lightning_bolt.thunder master @a ~ ~ ~ 3 0.5
execute if entity @s[scores={AsaMatrix=4}] run playsound entity.lightning_bolt.impact master @a ~ ~ ~ 3 0.5
execute if entity @s[scores={AsaMatrix=6}] as @e[type=armor_stand,tag=RukoParts,tag=HeadU,distance=0..7] at @s run function asa_animator:ruko/anim/breath/events/attack_start

execute if entity @s[scores={AsaMatrix=6..31}] run playsound entity.lightning_bolt.thunder master @a ~ ~ ~ 2 2
execute if entity @s[scores={AsaMatrix=6..21}] as @e[type=marker,tag=RukoBreathPos,distance=0..7] run function asa_animator:ruko/anim/breath/events/attack_0
execute if entity @s[scores={AsaMatrix=22..32}] as @e[type=marker,tag=RukoBreathPos,distance=0..7] at @s run function asa_animator:ruko/anim/breath/events/attack_rotate
execute if entity @s[scores={AsaMatrix=33..35}] as @e[type=marker,tag=RukoBreathPos,distance=0..7] at @s run function asa_animator:ruko/anim/breath/events/attack_1

execute if entity @s[scores={AsaMatrix=38..48}] run function asa_animator:ruko/manager/rotate

execute if entity @s[scores={AsaMatrix=43}] run playsound entity.lightning_bolt.thunder master @a ~ ~ ~ 3 0.7
execute if entity @s[scores={AsaMatrix=43}] run playsound entity.lightning_bolt.thunder master @a ~ ~ ~ 3 0.5
execute if entity @s[scores={AsaMatrix=43}] run playsound entity.lightning_bolt.impact master @a ~ ~ ~ 3 0.5
execute if entity @s[scores={AsaMatrix=45..70}] run playsound entity.lightning_bolt.thunder master @a ~ ~ ~ 2 2
execute if entity @s[scores={AsaMatrix=45..60}] as @e[type=marker,tag=RukoBreathPos,distance=0..7] run function asa_animator:ruko/anim/breath/events/attack_0
execute if entity @s[scores={AsaMatrix=61..71}] as @e[type=marker,tag=RukoBreathPos,distance=0..7] at @s run function asa_animator:ruko/anim/breath/events/attack_rotate
execute if entity @s[scores={AsaMatrix=72..74}] as @e[type=marker,tag=RukoBreathPos,distance=0..7] at @s run function asa_animator:ruko/anim/breath/events/attack_1

execute if entity @s[scores={AsaMatrix=75}] run kill @e[type=marker,tag=RukoBreathPos]

execute if entity @s[scores={AsaMatrix=1}] if score #mhdp_ruko_lv AsaMatrix matches 1.. run playsound entity.evoker.cast_spell master @a ~ ~ ~ 3 1
execute if entity @s[scores={AsaMatrix=1..17}] if score #mhdp_ruko_lv AsaMatrix matches 1.. run function asa_animator:ruko/manager/particle/push
execute if entity @s[scores={AsaMatrix=1..17}] if score #mhdp_ruko_lv AsaMatrix matches 1.. as @a[distance=..16] unless entity @s[scores={MhdpTAvoid=1..}] unless entity @s[scores={MhdpTDamage=1..}] at @s facing entity @e[type=armor_stand,tag=RukoRoot] feet rotated ~ 0 positioned ^ ^ ^-0.4 rotated as @s run function asa_animator:ruko/anim/gravity/events/move