# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:diablos/attack/start
execute if score @s AsaMatrix matches 1 run function asa_animator:diablos/attack/keyframes/0
execute if score @s AsaMatrix matches 1..10 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 11 run function asa_animator:diablos/attack/keyframes/1
execute if score @s AsaMatrix matches 11..15 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 16 run function asa_animator:diablos/attack/keyframes/2
execute if score @s AsaMatrix matches 16..22 run tp @s ^0.07142857 ^0 ^0.4285714
execute if score @s AsaMatrix matches 23 run function asa_animator:diablos/attack/keyframes/3
execute if score @s AsaMatrix matches 23..29 run tp @s ^-0.02857143 ^0 ^-0.07142857
execute if score @s AsaMatrix matches 30 run function asa_animator:diablos/attack/keyframes/4
execute if score @s AsaMatrix matches 30..31 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 32 run function asa_animator:diablos/attack/keyframes/5
execute if score @s AsaMatrix matches 32..38 run tp @s ^-0.1142857 ^0 ^0.3571429
execute if score @s AsaMatrix matches 39 run function asa_animator:diablos/attack/keyframes/6
execute if score @s AsaMatrix matches 39..47 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 48 run function asa_animator:diablos/attack/keyframes/7
execute if score @s AsaMatrix matches 48..65 run tp @s ^0.02777778 ^0 ^-0.05555556
execute if score @s AsaMatrix matches 66.. run function asa_animator:diablos/attack/end
execute as @e[type=armor_stand,tag=DiablosParts] run function #asa_matrix:animate
function asa_animator:diablos/model
