# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/tail_spin/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/tail_spin/keyframes/0
execute if entity @s[scores={AsaMatrix=1..8}] run tp @s ^0 ^-0.0125 ^0.025
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:reus/anim/tail_spin/keyframes/1
execute if entity @s[scores={AsaMatrix=9..16}] run tp @s ^0 ^0 ^-0.025
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:reus/anim/tail_spin/keyframes/2
execute if entity @s[scores={AsaMatrix=17..26}] run tp @s ^0 ^-0.02 ^0 ~20 ~
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:reus/anim/tail_spin/keyframes/3
execute if entity @s[scores={AsaMatrix=27..34}] run tp @s ^0 ^0.025 ^0.025 ~3 ~
execute if entity @s[scores={AsaMatrix=35}] run function asa_animator:reus/anim/tail_spin/keyframes/4
execute if entity @s[scores={AsaMatrix=35..42}] run tp @s ^0 ^0 ^-0.025 ~-1 ~
execute if entity @s[scores={AsaMatrix=43}] run function asa_animator:reus/anim/tail_spin/keyframes/5
execute if entity @s[scores={AsaMatrix=43..52}] run tp @s ^0 ^-0.02 ^0 ~20 ~
execute if entity @s[scores={AsaMatrix=53}] run function asa_animator:reus/anim/tail_spin/keyframes/6
execute if entity @s[scores={AsaMatrix=53..62}] run tp @s ^0 ^0.03 ^0 ~-3 ~
execute if entity @s[scores={AsaMatrix=63..}] run function asa_animator:reus/anim/tail_spin/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model

execute if entity @s[scores={AsaMatrix=17}] run playsound entity.player.attack.sweep master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=17..26}] at @e[type=armor_stand,distance=0..10,tag=ReusParts,tag=Tail2] run function asa_animator:reus/anim/tail_spin/events/damage
execute if entity @s[scores={AsaMatrix=43}] run playsound entity.player.attack.sweep master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=43..52}] at @e[type=armor_stand,distance=0..10,tag=ReusParts,tag=Tail2] run function asa_animator:reus/anim/tail_spin/events/damage