# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:brachyr/anim/punch_l/start
execute if score @s AsaMatrix matches 1 run function asa_animator:brachyr/anim/punch_l/keyframes/0
execute if score @s AsaMatrix matches 1..7 run tp @s ^0 ^0.02857143 ^-0.07142857
execute if score @s AsaMatrix matches 8 run function asa_animator:brachyr/anim/punch_l/keyframes/1
execute if score @s AsaMatrix matches 8..15 run tp @s ^0 ^0.0125 ^-0.0125
execute if score @s AsaMatrix matches 16 run function asa_animator:brachyr/anim/punch_l/keyframes/2
execute if score @s AsaMatrix matches 16..20 run tp @s ^0 ^0 ^-0.03
execute if score @s AsaMatrix matches 21 run function asa_animator:brachyr/anim/punch_l/keyframes/3
execute if score @s AsaMatrix matches 21..26 run tp @s ^0 ^-0.06666667 ^0.125
execute if score @s AsaMatrix matches 27 run function asa_animator:brachyr/anim/punch_l/keyframes/4
execute if score @s AsaMatrix matches 27..30 run tp @s ^0 ^0.1 ^0.05
execute if score @s AsaMatrix matches 31 run function asa_animator:brachyr/anim/punch_l/keyframes/5
execute if score @s AsaMatrix matches 31..47 run tp @s ^0 ^-0.02352941 ^-0.01176471
execute if score @s AsaMatrix matches 48 run function asa_animator:brachyr/anim/punch_l/keyframes/6
execute if score @s AsaMatrix matches 48..62 run tp @s ^0 ^0.006666667 ^-0.03333334
execute if score @s AsaMatrix matches 63.. run function asa_animator:brachyr/anim/punch_l/end
execute as @e[type=armor_stand,tag=BrachyRParts] run function #asa_matrix:animate
function asa_animator:brachyr/model
