# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:dyno/anim/slash_large_r/start
execute if score @s AsaMatrix matches 1 run function asa_animator:dyno/anim/slash_large_r/keyframes/0
execute if score @s AsaMatrix matches 1..4 run tp @s ^0 ^0 ^0 ~1 ~
execute if score @s AsaMatrix matches 5 run function asa_animator:dyno/anim/slash_large_r/keyframes/1
execute if score @s AsaMatrix matches 5..8 run tp @s ^-0.025 ^-0.025 ^0 ~1 ~
execute if score @s AsaMatrix matches 9 run function asa_animator:dyno/anim/slash_large_r/keyframes/2
execute if score @s AsaMatrix matches 9..20 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 21 run function asa_animator:dyno/anim/slash_large_r/keyframes/3
execute if score @s AsaMatrix matches 21..25 run tp @s ^0.02 ^0.05 ^0 ~-22 ~
execute if score @s AsaMatrix matches 26 run function asa_animator:dyno/anim/slash_large_r/keyframes/4
execute if score @s AsaMatrix matches 26..30 run tp @s ^0.02 ^0.03 ^0 ~-4 ~
execute if score @s AsaMatrix matches 31 run function asa_animator:dyno/anim/slash_large_r/keyframes/5
execute if score @s AsaMatrix matches 31..40 run tp @s ^0 ^0.01 ^-0.05 ~-3 ~
execute if score @s AsaMatrix matches 41 run function asa_animator:dyno/anim/slash_large_r/keyframes/6
execute if score @s AsaMatrix matches 41..45 run tp @s ^-0.05 ^0 ^0 ~-2 ~
execute if score @s AsaMatrix matches 46 run function asa_animator:dyno/anim/slash_large_r/keyframes/7
execute if score @s AsaMatrix matches 46..60 run tp @s ^-0.005 ^-0.02 ^0.025 ~-1 ~
execute if score @s AsaMatrix matches 61 run function asa_animator:dyno/anim/slash_large_r/keyframes/8
execute if score @s AsaMatrix matches 61..70 run tp @s ^-0.005 ^-0.02 ^0.025
execute if score @s AsaMatrix matches 71.. run function asa_animator:dyno/anim/slash_large_r/end
execute as @e[type=armor_stand,tag=DynoParts] run function #asa_matrix:animate
function asa_animator:dyno/model

execute if score @s AsaMatrix matches 20 run playsound item.trident.throw master @a ~ ~ ~ 2 0.5

execute if score @s AsaMatrix matches 21..40 run function asa_animator:dyno/manager/particle/jump
execute if score @s AsaMatrix matches 21..30 at @s run tp @s ^-0.3 ^ ^-0.5
execute if score @s AsaMatrix matches 31..35 at @s run tp @s ^-0.1 ^ ^-0.3
execute if score @s AsaMatrix matches 36..40 at @s run tp @s ^-0.05 ^ ^-0.1

execute if score @s AsaMatrix matches 21 positioned ^ ^2 ^ run function asa_animator:dyno/anim/slash_large_l/events/particle
execute if score @s AsaMatrix matches 21 positioned ^ ^ ^-5 run function asa_animator:dyno/anim/slash_large_l/events/damage
execute if score @s AsaMatrix matches 23 positioned ^-5 ^ ^ run function asa_animator:dyno/anim/slash_large_l/events/damage