# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:narga/anim/stay/start
execute if score @s AsaMatrix matches 1 run function asa_animator:narga/anim/stay/keyframes/0
execute if score @s AsaMatrix matches 1..8 run tp @s ^0 ^-0.0125 ^-0.01875
execute if score @s AsaMatrix matches 9 run function asa_animator:narga/anim/stay/keyframes/1
execute if score @s AsaMatrix matches 9..13 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 14 run function asa_animator:narga/anim/stay/keyframes/2
execute if score @s AsaMatrix matches 14..18 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 19 run function asa_animator:narga/anim/stay/keyframes/3
execute if score @s AsaMatrix matches 19..23 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 24 run function asa_animator:narga/anim/stay/keyframes/4
execute if score @s AsaMatrix matches 24..33 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 34 run function asa_animator:narga/anim/stay/keyframes/5
execute if score @s AsaMatrix matches 34..45 run tp @s ^0 ^0.008333334 ^0.0125
execute if score @s AsaMatrix matches 46.. run function asa_animator:narga/anim/stay/end
execute as @e[type=armor_stand,tag=NargaParts] run function #asa_matrix:animate
function asa_animator:narga/model
