# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:reus/normal/start_fly/start
execute if score @s AsaMatrix matches 1 run function asa_animator:reus/normal/start_fly/keyframes/0
execute if score @s AsaMatrix matches 1..5 run tp @s ^0 ^-0.06 ^0.2
execute if score @s AsaMatrix matches 6 run function asa_animator:reus/normal/start_fly/keyframes/1
execute if score @s AsaMatrix matches 6..10 run tp @s ^0 ^0.36 ^0.2
execute if score @s AsaMatrix matches 11 run function asa_animator:reus/normal/start_fly/keyframes/2
execute if score @s AsaMatrix matches 11..20 run tp @s ^0 ^0.1 ^0.1
execute if score @s AsaMatrix matches 21.. run function asa_animator:reus/normal/start_fly/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model
execute if score @s AsaMatrix matches 6 run tag @s add IsFlying

# 効果音
execute if score @s AsaMatrix matches 10 run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7