# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:teo/anim/end_fly/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:teo/anim/end_fly/keyframes/0
execute if entity @s[scores={AsaMatrix=1..11}] run tp @s ^0 ^0.1 ^0
execute if entity @s[scores={AsaMatrix=12}] run function asa_animator:teo/anim/end_fly/keyframes/1
execute if entity @s[scores={AsaMatrix=12..21}] run tp @s ^0 ^ ^-0.02
execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:teo/anim/end_fly/keyframes/2
execute if entity @s[scores={AsaMatrix=22..29}] run tp @s ^0 ^ ^0
execute if entity @s[scores={AsaMatrix=30}] run function asa_animator:teo/anim/end_fly/keyframes/3
execute if entity @s[scores={AsaMatrix=30..37}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=38}] run function asa_animator:teo/anim/end_fly/keyframes/4
execute if entity @s[scores={AsaMatrix=38..47}] run tp @s ^0 ^0 ^0.02
execute if entity @s[scores={AsaMatrix=48..}] run function asa_animator:teo/anim/end_fly/end
execute as @e[type=armor_stand,tag=TeoParts] run function #asa_matrix:animate
function asa_animator:teo/model

execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:teo/anim/end_fly/events/pos/set_pos
execute if entity @s[scores={AsaMatrix=12..29}] run function asa_animator:teo/anim/end_fly/events/pos/offset
execute if entity @s[scores={AsaMatrix=38}] run function asa_animator:teo/manager/model/change_to_normal

execute if entity @s[scores={AsaMatrix=11}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:teo/manager/particle/step