# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:tiga/anim/dash_stop/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:tiga/anim/dash_stop/keyframes/0
execute if entity @s[scores={AsaMatrix=1..8}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:tiga/anim/dash_stop/keyframes/1
execute if entity @s[scores={AsaMatrix=9..15}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:tiga/anim/dash_stop/keyframes/2
execute if entity @s[scores={AsaMatrix=16..20}] run tp @s ^0 ^0.02 ^0
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:tiga/anim/dash_stop/keyframes/3
execute if entity @s[scores={AsaMatrix=21..25}] run tp @s ^0 ^-0.02 ^0
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:tiga/anim/dash_stop/keyframes/4
execute if entity @s[scores={AsaMatrix=26..30}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:tiga/anim/dash_stop/keyframes/5
execute if entity @s[scores={AsaMatrix=31..35}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:tiga/anim/dash_stop/keyframes/6
execute if entity @s[scores={AsaMatrix=36..45}] run tp @s ^0 ^0 ^-0.04
execute if entity @s[scores={AsaMatrix=46..}] run function asa_animator:tiga/anim/dash_stop/end
execute as @e[type=armor_stand,tag=TigaParts] run function #asa_matrix:animate
function asa_animator:tiga/model

execute at @s positioned ~ ~5 ~ run tp @s ~ ~ ~
execute at @s positioned ~ ~5 ~ run function asa_animator:zinogre/manager/check_ground

execute if entity @s[scores={AsaMatrix=9..30}] run tp @s ^ ^ ^-0.3
execute if entity @s[scores={AsaMatrix=31..35}] run tp @s ^ ^ ^-0.1

execute if entity @s[scores={AsaMatrix=9..30}] run function asa_animator:tiga/manager/rotate_lr

execute if entity @s[scores={AsaMatrix=1}] run playsound entity.hoglin.attack master @a ~ ~ ~ 3 1.7
execute if entity @s[scores={AsaMatrix=1}] run playsound entity.hoglin.attack master @a ~ ~ ~ 3 1.2
execute if entity @s[scores={AsaMatrix=1}] run playsound entity.hoglin.attack master @a ~ ~ ~ 3 0.7

execute if entity @s[scores={AsaMatrix=8}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=25}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=35}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.7