# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:narga/anim/blade_r_combo/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:narga/anim/blade_r_combo/keyframes/0
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^0 ^0.8 ^-0.2
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:narga/anim/blade_r_combo/keyframes/1
execute if entity @s[scores={AsaMatrix=6..11}] run tp @s ^0.05555555 ^-0.6866667 ^-0.1666667
execute if entity @s[scores={AsaMatrix=12}] run function asa_animator:narga/anim/blade_r_combo/keyframes/2
execute if entity @s[scores={AsaMatrix=12..20}] run tp @s ^0.01851852 ^-0.006666668 ^-0.04444446
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:narga/anim/blade_r_combo/keyframes/3
execute if entity @s[scores={AsaMatrix=21..25}] run tp @s ^-0.1 ^0.636 ^0.48
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:narga/anim/blade_r_combo/keyframes/4
execute if entity @s[scores={AsaMatrix=26..33}] run tp @s ^0.03125 ^-0.3625 ^0.0625
execute if entity @s[scores={AsaMatrix=34}] run function asa_animator:narga/anim/blade_r_combo/keyframes/5
execute if entity @s[scores={AsaMatrix=34..38}] run tp @s ^0.05 ^-0.02 ^-0.3
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:narga/anim/blade_r_combo/keyframes/6
execute if entity @s[scores={AsaMatrix=39..45}] run tp @s ^-0.04285714 ^-0.01785714 ^-0.07142857
execute if entity @s[scores={AsaMatrix=46..}] run function asa_animator:narga/anim/blade_r_combo/end
execute as @e[type=armor_stand,tag=NargaParts] run function #asa_matrix:animate
function asa_animator:narga/model

execute if entity @s[scores={AsaMatrix=1..16}] run function asa_animator:narga/manager/rotate
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:narga/anim/blade_r/events/pos/set_pos
execute if entity @s[scores={AsaMatrix=21..32}] run function asa_animator:narga/anim/blade_r/events/pos/offset
execute if entity @s[scores={AsaMatrix=34..}] run function asa_animator:narga/manager/rotate

execute if entity @s[scores={AsaMatrix=1}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=1}] run particle block grass_block ~ ~ ~ 1 0.1 1 0 10

execute if entity @s[scores={AsaMatrix=21}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=21}] run particle block grass_block ~ ~ ~ 1 0.1 1 0 10

execute if entity @s[scores={AsaMatrix=33}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=33}] run particle block grass_block ~ ~ ~ 1 0.1 1 0 10
execute if entity @s[scores={AsaMatrix=35}] run playsound item.trident.throw master @a ~ ~ ~ 2 1.1
execute if entity @s[scores={AsaMatrix=35}] rotated ~10 ~ positioned ^ ^1.2 ^1 run function asa_animator:narga/anim/blade_r/events/particle

execute if entity @s[scores={AsaMatrix=21..30}] run function asa_animator:narga/anim/blade_l/events/damage_jump
execute if entity @s[scores={AsaMatrix=35}] positioned ^-4 ^ ^3 run function asa_animator:narga/anim/blade_l/events/damage