# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:nazuti/anim/wind_spread/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:nazuti/anim/wind_spread/keyframes/0
execute if entity @s[scores={AsaMatrix=1..6}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:nazuti/anim/wind_spread/keyframes/1
execute if entity @s[scores={AsaMatrix=7..16}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:nazuti/anim/wind_spread/keyframes/2
execute if entity @s[scores={AsaMatrix=17..23}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:nazuti/anim/wind_spread/keyframes/3
execute if entity @s[scores={AsaMatrix=24..32}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:nazuti/anim/wind_spread/keyframes/4
execute if entity @s[scores={AsaMatrix=33..47}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=48..}] run function asa_animator:nazuti/anim/wind_spread/end
execute as @e[type=armor_stand,tag=NazutiParts] run function #asa_matrix:animate
function asa_animator:nazuti/model

execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:nazuti/manager/model/change_to_open
execute if entity @s[scores={AsaMatrix=40}] run function asa_animator:nazuti/manager/model/change_to_normal

execute if entity @s[scores={AsaMatrix=23}] run function asa_animator:nazuti/manager/poison/move_start
execute if entity @s[scores={AsaMatrix=23}] as @a[distance=..6] run function mh_dp:player/knockback/start_dwind
execute if entity @s[scores={AsaMatrix=23}] run particle block grass_block ~ ~0.5 ~ 3 0 3 0 50