# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:ruko/anim/step_b_breath/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:ruko/anim/step_b_breath/keyframes/0
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^0 ^-0.02 ^0.04
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:ruko/anim/step_b_breath/keyframes/1
execute if entity @s[scores={AsaMatrix=6..12}] run tp @s ^0 ^0.03571429 ^-0.04285714
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:ruko/anim/step_b_breath/keyframes/2
execute if entity @s[scores={AsaMatrix=13..21}] run tp @s ^0 ^0 ^-0.01111111
execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:ruko/anim/step_b_breath/keyframes/3
execute if entity @s[scores={AsaMatrix=22..27}] run tp @s ^0 ^-0.025 ^0.03333334
execute if entity @s[scores={AsaMatrix=28}] run function asa_animator:ruko/anim/step_b_breath/keyframes/4
execute if entity @s[scores={AsaMatrix=28..32}] run tp @s ^0 ^-0.02 ^0.04
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:ruko/anim/step_b_breath/keyframes/5
execute if entity @s[scores={AsaMatrix=33..50}] run tp @s ^0 ^0.005555556 ^-0.01111111
execute if entity @s[scores={AsaMatrix=51..}] run function asa_animator:ruko/anim/step_b_breath/end
execute as @e[type=armor_stand,tag=RukoParts] run function #asa_matrix:animate
function asa_animator:ruko/model

execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:ruko/manager/particle/step
execute if entity @s[scores={AsaMatrix=12}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:ruko/manager/particle/step

execute if entity @s[scores={AsaMatrix=1..16}] run function asa_animator:ruko/manager/rotate
execute if entity @s[scores={AsaMatrix=16}] run summon marker ^ ^0.7 ^20 {Tags:["RukoBreathTarget"]}
execute if entity @s[scores={AsaMatrix=16}] unless entity @e[tag=RukoAttackTarget,distance=0..8] at @e[tag=RukoAttackTarget,limit=1] run tp @e[type=marker,tag=RukoBreathTarget] ~ ~ ~
execute if entity @s[scores={AsaMatrix=16}] as @e[type=marker,tag=RukoBreathTarget] at @s run function asa_animator:zinogre/manager/check_ground

execute if entity @s[scores={AsaMatrix=32}] run playsound entity.lightning_bolt.thunder master @a ~ ~ ~ 3 0.7
execute if entity @s[scores={AsaMatrix=32}] run playsound entity.lightning_bolt.thunder master @a ~ ~ ~ 3 0.5
execute if entity @s[scores={AsaMatrix=32}] run playsound entity.lightning_bolt.impact master @a ~ ~ ~ 3 0.5
execute if entity @s[scores={AsaMatrix=32}] run function asa_animator:ruko/anim/step_b_breath/events/attack