# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/flying_breath_charge/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/0
execute if entity @s[scores={AsaMatrix=1..8}] run tp @s ^-0.0625 ^0.125 ^-0.125
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/1
execute if entity @s[scores={AsaMatrix=9..16}] run tp @s ^-0.025 ^0 ^0
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/2
execute if entity @s[scores={AsaMatrix=17..19}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=20}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/3
execute if entity @s[scores={AsaMatrix=20..26}] run tp @s ^-0.08571428 ^0.1428571 ^-0.07142857
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/4
execute if entity @s[scores={AsaMatrix=27..38}] run tp @s ^0 ^0.008333325 ^0
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/5
execute if entity @s[scores={AsaMatrix=39..53}] run tp @s ^0 ^-0.00666666 ^0
execute if entity @s[scores={AsaMatrix=54}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/6
execute if entity @s[scores={AsaMatrix=54..58}] run tp @s ^0 ^0.1 ^-0.1
execute if entity @s[scores={AsaMatrix=59}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/7
execute if entity @s[scores={AsaMatrix=59..65}] run tp @s ^0.1142857 ^0.07142857 ^-0.1428571
execute if entity @s[scores={AsaMatrix=66}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/8
execute if entity @s[scores={AsaMatrix=66..75}] run tp @s ^0.05 ^-0.15 ^-0.1
execute if entity @s[scores={AsaMatrix=76}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/9
execute if entity @s[scores={AsaMatrix=76..85}] run tp @s ^0 ^-0.05 ^-0.2
execute if entity @s[scores={AsaMatrix=86}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/10
execute if entity @s[scores={AsaMatrix=86..95}] run tp @s ^0 ^0.02000001 ^-0.03000002
execute if entity @s[scores={AsaMatrix=96}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/11
execute if entity @s[scores={AsaMatrix=96..100}] run tp @s ^0 ^-0.24 ^0
execute if entity @s[scores={AsaMatrix=101}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/12
execute if entity @s[scores={AsaMatrix=101..105}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=106}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/13
execute if entity @s[scores={AsaMatrix=106..110}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=111}] run function asa_animator:reus/anim/flying_breath_charge/keyframes/14
execute if entity @s[scores={AsaMatrix=111..125}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=126..}] run function asa_animator:reus/anim/flying_breath_charge/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model

execute if entity @s[scores={AsaMatrix=..50}] run function asa_animator:reus/manager/rotate

execute if entity @s[scores={AsaMatrix=1}] run playsound entity.player.breath master @a ~ ~ ~ 2 0.8
execute if entity @s[scores={AsaMatrix=14}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=93}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7

execute if entity @s[scores={AsaMatrix=25}] as @e[type=armor_stand,distance=0..7,tag=ReusParts,tag=HeadU] at @s run function asa_animator:reus/anim/flying_breath_charge/events/attack_start
execute if entity @s[scores={AsaMatrix=26..52}] as @e[type=marker,distance=0..7,tag=ReusChargeFPos] at @s run function asa_animator:reus/anim/flying_breath_charge/events/attack
execute if entity @s[scores={AsaMatrix=53..64}] as @e[type=marker,distance=0..7,tag=ReusChargeFPos] at @s run function asa_animator:reus/anim/flying_breath_charge/events/attack_rotate
execute if entity @s[scores={AsaMatrix=64}] run kill @e[type=marker,tag=ReusChargeFPos]

execute if entity @s[scores={AsaMatrix=85}] run function asa_animator:reus/anim/flying_breath_charge/events/set_pos
execute if entity @s[scores={AsaMatrix=86..105}] run function asa_animator:reus/anim/end_fly/events/offset