# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:diablos/anim_anger/short_dash/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:diablos/anim_anger/short_dash/keyframes/0
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^0 ^0.1 ^-0.4
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:diablos/anim_anger/short_dash/keyframes/1
execute if entity @s[scores={AsaMatrix=6..10}] run tp @s ^0 ^0 ^-0.04
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:diablos/anim_anger/short_dash/keyframes/2
execute if entity @s[scores={AsaMatrix=11..16}] run tp @s ^0 ^-0.1 ^0.03333333
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:diablos/anim_anger/short_dash/keyframes/3
execute if entity @s[scores={AsaMatrix=17..20}] run tp @s ^0 ^0 ^0.7
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:diablos/anim_anger/short_dash/keyframes/4
execute if entity @s[scores={AsaMatrix=21..24}] run tp @s ^0 ^0.1 ^0.8
execute if entity @s[scores={AsaMatrix=25}] run function asa_animator:diablos/anim_anger/short_dash/keyframes/5
execute if entity @s[scores={AsaMatrix=25..27}] run tp @s ^0 ^-0.1 ^1.0
execute if entity @s[scores={AsaMatrix=28}] run function asa_animator:diablos/anim_anger/short_dash/keyframes/6
execute if entity @s[scores={AsaMatrix=28..30}] run tp @s ^0 ^0.1 ^1.1
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:diablos/anim_anger/short_dash/keyframes/7
execute if entity @s[scores={AsaMatrix=31..34}] run tp @s ^0 ^-0.075 ^1.1
execute if entity @s[scores={AsaMatrix=35}] run function asa_animator:diablos/anim_anger/short_dash/keyframes/8
execute if entity @s[scores={AsaMatrix=35..37}] run tp @s ^0 ^0.1 ^0.7
execute if entity @s[scores={AsaMatrix=38}] run function asa_animator:diablos/anim_anger/short_dash/keyframes/9
execute if entity @s[scores={AsaMatrix=38..42}] run tp @s ^0 ^-0.04 ^0.4
execute if entity @s[scores={AsaMatrix=43}] run function asa_animator:diablos/anim_anger/short_dash/keyframes/10
execute if entity @s[scores={AsaMatrix=43..50}] run tp @s ^0 ^0.0125 ^0.1
execute if entity @s[scores={AsaMatrix=51}] run function asa_animator:diablos/anim_anger/short_dash/keyframes/11
execute if entity @s[scores={AsaMatrix=51..63}] run tp @s ^0 ^-0.01538462 ^0.05384615 ~0.5 ~
execute if entity @s[scores={AsaMatrix=64..}] run function asa_animator:diablos/anim_anger/short_dash/end
execute as @e[type=armor_stand,tag=DiablosParts] run function #asa_matrix:animate
function asa_animator:diablos/model

# 高度調整
execute if entity @s[scores={AsaMatrix=17..42}] at @s positioned ~ ~5 ~ run tp @s ~ ~ ~
execute if entity @s[scores={AsaMatrix=17..42}] at @s positioned ~ ~5 ~ run function asa_animator:zinogre/manager/check_ground

execute if entity @s[scores={AsaMatrix=1..12}] run function asa_animator:diablos/manager/rotate

execute if entity @s[scores={AsaMatrix=1}] run playsound block.grass.step master @a ~ ~ ~ 2 0.8

execute if entity @s[scores={AsaMatrix=20..42}] run particle block sand ~ ~0.5 ~ 1 0.5 1 0 5

execute if entity @s[scores={AsaMatrix=20}] run playsound entity.iron_golem.step master @a ~ ~ ~ 3 0.7
execute if entity @s[scores={AsaMatrix=27}] run playsound entity.iron_golem.step master @a ~ ~ ~ 3 0.7
execute if entity @s[scores={AsaMatrix=34}] run playsound entity.iron_golem.step master @a ~ ~ ~ 3 0.7
execute if entity @s[scores={AsaMatrix=42}] run playsound entity.iron_golem.step master @a ~ ~ ~ 3 0.7
execute if entity @s[scores={AsaMatrix=40}] run playsound entity.player.attack.sweep master @a ~ ~ ~ 3 0.5

execute if entity @s[scores={AsaMatrix=20..41}] run function asa_animator:diablos/anim/short_dash/events/damage
execute if entity @s[scores={AsaMatrix=42}] run function asa_animator:diablos/anim/short_dash/events/damage_head
