# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:teo/anim/dash_start/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:teo/anim/dash_start/keyframes/0
execute if entity @s[scores={AsaMatrix=1..8}] run tp @s ^0 ^0.01875 ^-0.0875
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:teo/anim/dash_start/keyframes/1
execute if entity @s[scores={AsaMatrix=9..18}] run tp @s ^0 ^-0.015 ^-0.11
execute if entity @s[scores={AsaMatrix=19..}] run function asa_animator:teo/anim/dash_start/end
execute as @e[type=armor_stand,tag=TeoParts] run function #asa_matrix:animate
function asa_animator:teo/model

execute if entity @s[scores={AsaMatrix=1}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=1..10}] run function asa_animator:teo/manager/rotate
execute if entity @s[scores={AsaMatrix=18}] run summon marker ^ ^ ^10 {Tags:["TeoDashTarget"]}
execute if entity @s[scores={AsaMatrix=18}] positioned as @e[tag=TeoAttackTarget] as @e[type=marker,tag=TeoDashTarget] run tp @s ~ ~ ~