# This function was generated by ArmorstandAnimator

execute if entity @s[scores={AsaMatrix=1}] at @s positioned ~ ~10 ~ run function asa_animator:zinogre/manager/check_ground
execute if entity @s[scores={AsaMatrix=1}] at @s run tp @s ~ ~-10 ~

scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:brachyr/anim/summon/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:brachyr/anim/summon/keyframes/0
execute if entity @s[scores={AsaMatrix=1..10}] run tp @s ^0 ^0.6 ^0
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:brachyr/anim/summon/keyframes/1
execute if entity @s[scores={AsaMatrix=11..20}] run tp @s ^0 ^0.3 ^0
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:brachyr/anim/summon/keyframes/2
execute if entity @s[scores={AsaMatrix=21..30}] run tp @s ^0 ^0.1 ^0
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:brachyr/anim/summon/keyframes/3
execute if entity @s[scores={AsaMatrix=31..40}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=41..}] run function asa_animator:brachyr/anim/summon/end
execute as @e[type=armor_stand,tag=BrachyRParts] run function #asa_matrix:animate
function asa_animator:brachyr/model

execute if entity @s[scores={AsaMatrix=1}] run playsound block.grass.break master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=11}] run playsound block.grass.break master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=21}] run playsound block.grass.break master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=31..40}] run function asa_animator:brachy/manager/ground