# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:brachy/anim/voice/start
execute if score @s AsaMatrix matches 1 run function asa_animator:brachy/anim/voice/keyframes/0
execute if score @s AsaMatrix matches 1..7 run tp @s ^0 ^0.07142857 ^0
execute if score @s AsaMatrix matches 8 run function asa_animator:brachy/anim/voice/keyframes/1
execute if score @s AsaMatrix matches 8..14 run tp @s ^0 ^-0.05714286 ^0
execute if score @s AsaMatrix matches 15 run function asa_animator:brachy/anim/voice/keyframes/2
execute if score @s AsaMatrix matches 15..19 run tp @s ^0 ^-0.04 ^0
execute if score @s AsaMatrix matches 20 run function asa_animator:brachy/anim/voice/keyframes/3
execute if score @s AsaMatrix matches 20..26 run tp @s ^0 ^0.08571429 ^0
execute if score @s AsaMatrix matches 27 run function asa_animator:brachy/anim/voice/keyframes/4
execute if score @s AsaMatrix matches 27..33 run tp @s ^0 ^-0.05714286 ^0
execute if score @s AsaMatrix matches 34 run function asa_animator:brachy/anim/voice/keyframes/5
execute if score @s AsaMatrix matches 34..38 run tp @s ^0 ^-0.04 ^0
execute if score @s AsaMatrix matches 39 run function asa_animator:brachy/anim/voice/keyframes/6
execute if score @s AsaMatrix matches 39..48 run tp @s ^0 ^0.02 ^0
execute if score @s AsaMatrix matches 49 run function asa_animator:brachy/anim/voice/keyframes/7
execute if score @s AsaMatrix matches 49..53 run tp @s ^0 ^-0.04 ^0
execute if score @s AsaMatrix matches 54 run function asa_animator:brachy/anim/voice/keyframes/8
execute if score @s AsaMatrix matches 54..58 run tp @s ^0 ^0.04 ^0
execute if score @s AsaMatrix matches 59 run function asa_animator:brachy/anim/voice/keyframes/9
execute if score @s AsaMatrix matches 59..73 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 74 run function asa_animator:brachy/anim/voice/keyframes/10
execute if score @s AsaMatrix matches 74..88 run tp @s ^0 ^-0.006666667 ^0
execute if score @s AsaMatrix matches 89.. run function asa_animator:brachy/anim/voice/end
execute as @e[type=armor_stand,tag=BrachyParts] run function #asa_matrix:animate
function asa_animator:brachy/model

execute if score @s AsaMatrix matches 1 run function asa_animator:brachy/manager/change_target
execute if score @s AsaMatrix matches 1..38 run function asa_animator:brachy/manager/rotate

execute if score @s AsaMatrix matches 1 run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if score @s AsaMatrix matches 20 run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if score @s AsaMatrix matches 38 run playsound block.grass.step master @a ~ ~ ~ 2 0.7

execute if score @s AsaMatrix matches 54..81 as @e[distance=0..10,type=armor_stand,tag=BrachyParts,tag=HeadU] at @s positioned ~ ~1.4 ~ run particle flash ~ ~ ~ 0 0 0 0 1

execute if score @s AsaMatrix matches 54 run playsound entity.blaze.death master @a ~ ~ ~ 2 0.8
execute if score @s AsaMatrix matches 54 run playsound entity.blaze.death master @a ~ ~ ~ 2 0.7