# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:dyno/anim/breath/start
execute if score @s AsaMatrix matches 1 run function asa_animator:dyno/anim/breath/keyframes/0
execute if score @s AsaMatrix matches 1..5 run tp @s ^0 ^0 ^-0.06
execute if score @s AsaMatrix matches 6 run function asa_animator:dyno/anim/breath/keyframes/1
execute if score @s AsaMatrix matches 6..10 run tp @s ^0 ^-0.01 ^0
execute if score @s AsaMatrix matches 11 run function asa_animator:dyno/anim/breath/keyframes/2
execute if score @s AsaMatrix matches 11..15 run tp @s ^0 ^0.01 ^0
execute if score @s AsaMatrix matches 16 run function asa_animator:dyno/anim/breath/keyframes/3
execute if score @s AsaMatrix matches 16..22 run tp @s ^0 ^0 ^0.05714286
execute if score @s AsaMatrix matches 23 run function asa_animator:dyno/anim/breath/keyframes/4
execute if score @s AsaMatrix matches 23..29 run tp @s ^0 ^0.01428571 ^-0.007142856
execute if score @s AsaMatrix matches 30 run function asa_animator:dyno/anim/breath/keyframes/5
execute if score @s AsaMatrix matches 30..37 run tp @s ^0 ^-0.0125 ^-0.006250001
execute if score @s AsaMatrix matches 38.. run function asa_animator:dyno/anim/breath/end
execute as @e[type=armor_stand,tag=DynoParts] run function #asa_matrix:animate
function asa_animator:dyno/model

execute if score @s AsaMatrix matches 1..10 run function asa_animator:dyno/manager/rotate

execute if score @s AsaMatrix matches 11 run summon marker ^ ^0.7 ^8 {Tags:["DynoBreathTarget"]}
execute if score @s AsaMatrix matches 11 unless entity @e[distance=0..8,tag=DynoAttackTarget] at @e[tag=DynoAttackTarget,limit=1] run tp @e[type=marker,tag=DynoBreathTarget] ~ ~ ~
execute if score @s AsaMatrix matches 14 run playsound entity.iron_golem.hurt master @a ~ ~ ~ 2 0.5
execute if score @s AsaMatrix matches 15 positioned ^ ^2 ^6 run function asa_animator:dyno/anim/breath/events/shot