# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/hard_flying_jump/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/hard_flying_jump/keyframes/0
execute if entity @s[scores={AsaMatrix=1..8}] run tp @s ^0 ^0.125 ^-0.075
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:reus/anim/hard_flying_jump/keyframes/1
execute if entity @s[scores={AsaMatrix=9..16}] run tp @s ^0 ^-0.125 ^0.175
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:reus/anim/hard_flying_jump/keyframes/2
execute if entity @s[scores={AsaMatrix=17..30}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:reus/anim/hard_flying_jump/keyframes/3
execute if entity @s[scores={AsaMatrix=31..35}] run tp @s ^0 ^-0.08 ^-0.16
execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:reus/anim/hard_flying_jump/keyframes/4
execute if entity @s[scores={AsaMatrix=36..40}] run tp @s ^0 ^1.48 ^-0.04
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:reus/anim/hard_flying_jump/keyframes/5
execute if entity @s[scores={AsaMatrix=41..50}] run tp @s ^0 ^0.05 ^-0.03
execute if entity @s[scores={AsaMatrix=51}] run function asa_animator:reus/anim/hard_flying_jump/keyframes/6
execute if entity @s[scores={AsaMatrix=51..55}] run tp @s ^0 ^-1.58 ^0.1
execute if entity @s[scores={AsaMatrix=56}] run function asa_animator:reus/anim/hard_flying_jump/keyframes/7
execute if entity @s[scores={AsaMatrix=56..78}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=79..}] run function asa_animator:reus/anim/hard_flying_jump/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model

# 移動
    execute if entity @s[scores={AsaMatrix=1..35}] run function asa_animator:reus/manager/rotate
    execute if entity @s[scores={AsaMatrix=10..35}] at @s unless entity @e[tag=ReusAttackTarget,distance=0..7] facing entity @e[tag=ReusAttackTarget] feet run tp @s ^ ^ ^0.7
    execute if entity @s[scores={AsaMatrix=10..35}] at @s if entity @e[tag=ReusAttackTarget,distance=0..7] run tp @s ^ ^ ^0.1
    execute if entity @s[scores={AsaMatrix=6}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=35}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7

# 演出
    execute if entity @s[scores={AsaMatrix=28}] run function asa_animator:reus/anim/hard_flying_jump/events/pos/set_pos
    execute if entity @s[scores={AsaMatrix=36..55}] at @s run function asa_animator:reus/anim/hard_flying_jump/events/pos/offset

# 攻撃
    execute if entity @s[scores={AsaMatrix=56}] positioned ^ ^ ^1 run function asa_animator:reus/anim/jump/events/damage

# 高度調整
    execute if entity @s[scores={AsaMatrix=56..}] at @s if block ~ ~-0.2 ~ #asa_animator:no_collision at @s run function asa_animator:zinogre/manager/check_ground
    execute if entity @s[scores={AsaMatrix=56..}] at @s unless block ~ ~ ~ #asa_animator:no_collision at @s run tp @s ~ ~0.1 ~ ~ ~