# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/hard_fjb/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/hard_fjb/keyframes/0
execute if entity @s[scores={AsaMatrix=1..12}] run tp @s ^0 ^-0.0125 ^0.04166667
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:reus/anim/hard_fjb/keyframes/1
execute if entity @s[scores={AsaMatrix=13..25}] run tp @s ^0 ^-0.01153846 ^0.03846154
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:reus/anim/hard_fjb/keyframes/2
execute if entity @s[scores={AsaMatrix=26..30}] run tp @s ^0 ^0.36 ^-0.2
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:reus/anim/hard_fjb/keyframes/3
execute if entity @s[scores={AsaMatrix=31..40}] run tp @s ^0 ^0.2 ^0
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:reus/anim/hard_fjb/keyframes/4
execute if entity @s[scores={AsaMatrix=41..45}] run tp @s ^-0.26 ^-0.1 ^0.1
execute if entity @s[scores={AsaMatrix=46}] run function asa_animator:reus/anim/hard_fjb/keyframes/5
execute if entity @s[scores={AsaMatrix=46..50}] run tp @s ^0.26 ^0.3 ^-0.1
execute if entity @s[scores={AsaMatrix=51}] run function asa_animator:reus/anim/hard_fjb/keyframes/6
execute if entity @s[scores={AsaMatrix=51..60}] run tp @s ^0 ^0.05 ^-0.1
execute if entity @s[scores={AsaMatrix=61}] run function asa_animator:reus/anim/hard_fjb/keyframes/7
execute if entity @s[scores={AsaMatrix=61..65}] run tp @s ^0 ^0 ^-0.1
execute if entity @s[scores={AsaMatrix=66}] run function asa_animator:reus/anim/hard_fjb/keyframes/8
execute if entity @s[scores={AsaMatrix=66..85}] run tp @s ^0 ^-0.125 ^-0.075
execute if entity @s[scores={AsaMatrix=86..}] run function asa_animator:reus/anim/hard_fjb/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model

# 移動
    execute if entity @s[scores={AsaMatrix=1..35}] run function asa_animator:reus/manager/rotate
    execute if entity @s[scores={AsaMatrix=30}] run function asa_animator:reus/anim/hard_fjb/events/pos/set_pos
    execute if entity @s[scores={AsaMatrix=31..40}] at @s run function asa_animator:reus/anim/hard_fjb/events/pos/offset

# 演出
    execute if entity @s[scores={AsaMatrix=1}] run playsound entity.player.breath master @a ~ ~ ~ 2 0.8
    execute if entity @s[scores={AsaMatrix=30}] run function asa_animator:reus/manager/model/change_to_fly

# 攻撃
    execute if entity @s[scores={AsaMatrix=45}] as @e[type=armor_stand,tag=ReusParts,tag=HeadU,distance=0..7] at @s run function asa_animator:reus/anim/flying_breath_charge/events/attack_start
    execute if entity @s[scores={AsaMatrix=45}] as @e[type=marker,tag=ReusChargeFPos] at @s run tp @s ~ ~ ~ ~ 90
    execute if entity @s[scores={AsaMatrix=45..56}] as @e[type=marker,tag=ReusChargeFPos,distance=0..7] at @s positioned as @e[type=armor_stand,tag=ReusParts,tag=HeadU,distance=0..7] run function asa_animator:reus/anim/flying_breath_charge/events/attack_rotate
    execute if entity @s[scores={AsaMatrix=57}] run kill @e[type=marker,tag=ReusChargeFPos]