# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:brachyr/anim/dozer/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:brachyr/anim/dozer/keyframes/0
execute if entity @s[scores={AsaMatrix=1..8}] run tp @s ^0 ^0 ^-0.025
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:brachyr/anim/dozer/keyframes/1
execute if entity @s[scores={AsaMatrix=9..16}] run tp @s ^0 ^-0.0125 ^-0.0375
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:brachyr/anim/dozer/keyframes/2
execute if entity @s[scores={AsaMatrix=17..21}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:brachyr/anim/dozer/keyframes/3
execute if entity @s[scores={AsaMatrix=22..26}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:brachyr/anim/dozer/keyframes/4
execute if entity @s[scores={AsaMatrix=27..31}] run tp @s ^0 ^0.14 ^0
execute if entity @s[scores={AsaMatrix=32}] run function asa_animator:brachyr/anim/dozer/keyframes/5
execute if entity @s[scores={AsaMatrix=32..36}] run tp @s ^0 ^-0.14 ^0
execute if entity @s[scores={AsaMatrix=37}] run function asa_animator:brachyr/anim/dozer/keyframes/6
execute if entity @s[scores={AsaMatrix=37..41}] run tp @s ^0 ^0.02 ^-0.3
execute if entity @s[scores={AsaMatrix=42}] run function asa_animator:brachyr/anim/dozer/keyframes/7
execute if entity @s[scores={AsaMatrix=42..51}] run tp @s ^0 ^-0.01 ^-0.1
execute if entity @s[scores={AsaMatrix=52}] run function asa_animator:brachyr/anim/dozer/keyframes/8
execute if entity @s[scores={AsaMatrix=52..56}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=57}] run function asa_animator:brachyr/anim/dozer/keyframes/9
execute if entity @s[scores={AsaMatrix=57..61}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=62}] run function asa_animator:brachyr/anim/dozer/keyframes/10
execute if entity @s[scores={AsaMatrix=62..66}] run tp @s ^0 ^0.14 ^0
execute if entity @s[scores={AsaMatrix=67}] run function asa_animator:brachyr/anim/dozer/keyframes/11
execute if entity @s[scores={AsaMatrix=67..71}] run tp @s ^0 ^-0.14 ^0
execute if entity @s[scores={AsaMatrix=72}] run function asa_animator:brachyr/anim/dozer/keyframes/12
execute if entity @s[scores={AsaMatrix=72..76}] run tp @s ^0 ^0.02 ^-0.3
execute if entity @s[scores={AsaMatrix=77}] run function asa_animator:brachyr/anim/dozer/keyframes/13
execute if entity @s[scores={AsaMatrix=77..89}] run tp @s ^0 ^-0.007692308 ^-0.1
execute if entity @s[scores={AsaMatrix=90}] run function asa_animator:brachyr/anim/dozer/keyframes/14
execute if entity @s[scores={AsaMatrix=90..94}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=95}] run function asa_animator:brachyr/anim/dozer/keyframes/15
execute if entity @s[scores={AsaMatrix=95..99}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=100}] run function asa_animator:brachyr/anim/dozer/keyframes/16
execute if entity @s[scores={AsaMatrix=100..104}] run tp @s ^0 ^0.14 ^0
execute if entity @s[scores={AsaMatrix=105}] run function asa_animator:brachyr/anim/dozer/keyframes/17
execute if entity @s[scores={AsaMatrix=105..109}] run tp @s ^0 ^-0.14 ^0 ~-6 ~
execute if entity @s[scores={AsaMatrix=110}] run function asa_animator:brachyr/anim/dozer/keyframes/18
execute if entity @s[scores={AsaMatrix=110..114}] run tp @s ^0 ^0 ^0 ~-3 ~
execute if entity @s[scores={AsaMatrix=115}] run function asa_animator:brachyr/anim/dozer/keyframes/19
execute if entity @s[scores={AsaMatrix=115..119}] run tp @s ^0 ^0.01 ^0.03 ~6 ~
execute if entity @s[scores={AsaMatrix=120}] run function asa_animator:brachyr/anim/dozer/keyframes/20
execute if entity @s[scores={AsaMatrix=120..129}] run tp @s ^0 ^0.005 ^0.015 ~3 ~
execute if entity @s[scores={AsaMatrix=130}] run function asa_animator:brachyr/anim/dozer/keyframes/21
execute if entity @s[scores={AsaMatrix=130..139}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=140}] run function asa_animator:brachyr/anim/dozer/keyframes/22
execute if entity @s[scores={AsaMatrix=140..149}] run tp @s ^0 ^-0.02 ^0 ~-1 ~
execute if entity @s[scores={AsaMatrix=150}] run function asa_animator:brachyr/anim/dozer/keyframes/23
execute if entity @s[scores={AsaMatrix=150..159}] run tp @s ^0 ^0.02 ^0.02
execute if entity @s[scores={AsaMatrix=160..}] run function asa_animator:brachyr/anim/dozer/end
execute as @e[type=armor_stand,tag=BrachyRParts] run function #asa_matrix:animate
function asa_animator:brachyr/model

execute if entity @s[scores={AsaMatrix=1..11}] run function asa_animator:brachyr/manager/rotate
execute if entity @s[scores={AsaMatrix=36..46}] run function asa_animator:brachyr/manager/rotate
execute if entity @s[scores={AsaMatrix=71..81}] run function asa_animator:brachyr/manager/rotate

execute if entity @s[scores={AsaMatrix=1}] run playsound block.grass.step master @a ~ ~ ~ 2 0.5
execute if entity @s[scores={AsaMatrix=31}] run playsound block.grass.step master @a ~ ~ ~ 2 0.5
execute if entity @s[scores={AsaMatrix=66}] run playsound block.grass.step master @a ~ ~ ~ 2 0.5
execute if entity @s[scores={AsaMatrix=104}] run playsound block.grass.step master @a ~ ~ ~ 2 0.5
execute if entity @s[scores={AsaMatrix=140}] run playsound block.grass.step master @a ~ ~ ~ 2 0.5

execute if entity @s[scores={AsaMatrix=21}] positioned ^ ^ ^5 run particle block grass_block ~ ~ ~ 1 0.1 1 0 30
execute if entity @s[scores={AsaMatrix=21}] positioned ^ ^ ^5 run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.5
execute if entity @s[scores={AsaMatrix=21..36}] positioned ^ ^ ^5 run function asa_animator:brachyr/anim/dozer/events/damage
execute if entity @s[scores={AsaMatrix=36}] positioned ^ ^ ^5 run function asa_animator:brachyr/anim/dozer/events/set

execute if entity @s[scores={AsaMatrix=56}] positioned ^ ^ ^5 run particle block grass_block ~ ~ ~ 1 0.1 1 0 30
execute if entity @s[scores={AsaMatrix=56}] positioned ^ ^ ^5 run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.5
execute if entity @s[scores={AsaMatrix=56..71}] positioned ^ ^ ^5 run function asa_animator:brachyr/anim/dozer/events/damage
execute if entity @s[scores={AsaMatrix=71}] positioned ^ ^ ^5 run function asa_animator:brachyr/anim/dozer/events/set

execute if entity @s[scores={AsaMatrix=72..89}] at @s if entity @e[tag=BrachyRAttackTarget,distance=0..10] run tp @s ^0 ^ ^-0.4

execute if entity @s[scores={AsaMatrix=94}] positioned ^ ^ ^5 run particle block grass_block ~ ~ ~ 1 0.1 1 0 30
execute if entity @s[scores={AsaMatrix=94}] positioned ^ ^ ^5 run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.5
execute if entity @s[scores={AsaMatrix=94..109}] positioned ^ ^ ^5 run function asa_animator:brachyr/anim/dozer/events/damage
execute if entity @s[scores={AsaMatrix=112}] rotated ~-10 ~ positioned ^ ^ ^5 run function asa_animator:brachyr/anim/head_bomb/events/damage
execute if entity @s[scores={AsaMatrix=119}] rotated ~10 ~ positioned ^ ^ ^5 run function asa_animator:brachyr/anim/head_bomb/events/damage
execute if entity @s[scores={AsaMatrix=112}] rotated ~10 ~ positioned ^ ^ ^6 run function asa_animator:brachyr/anim/dozer/events/set
execute if entity @s[scores={AsaMatrix=113}] run function asa_animator:brachyr/anim/dozer/events/rotate

execute at @s if block ~ ~-0.2 ~ #asa_animator:no_collision at @s run function asa_animator:zinogre/manager/check_ground
execute at @s unless block ~ ~ ~ #asa_animator:no_collision at @s run tp @s ~ ~0.1 ~ ~ ~