# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:nazuti/anim/flying_damage/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:nazuti/anim/flying_damage/keyframes/0
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^0 ^0.04 ^-0.06
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:nazuti/anim/flying_damage/keyframes/1
execute if entity @s[scores={AsaMatrix=6..10}] run tp @s ^0 ^0.2 ^0.06
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:nazuti/anim/flying_damage/keyframes/2
execute if entity @s[scores={AsaMatrix=11..15}] run tp @s ^0 ^-0.31 ^0
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:nazuti/anim/flying_damage/keyframes/3
execute if entity @s[scores={AsaMatrix=16..20}] run tp @s ^0 ^-0.01 ^0
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:nazuti/anim/flying_damage/keyframes/4
execute if entity @s[scores={AsaMatrix=21..32}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:nazuti/anim/flying_damage/keyframes/5
execute if entity @s[scores={AsaMatrix=33..42}] run tp @s ^0 ^0.02 ^0
execute if entity @s[scores={AsaMatrix=43}] run function asa_animator:nazuti/anim/flying_damage/keyframes/6
execute if entity @s[scores={AsaMatrix=43..49}] run tp @s ^0 ^0.01428571 ^0
execute if entity @s[scores={AsaMatrix=50}] run function asa_animator:nazuti/anim/flying_damage/keyframes/7
execute if entity @s[scores={AsaMatrix=50..57}] run tp @s ^0 ^0.0125 ^0
execute if entity @s[scores={AsaMatrix=58..}] run function asa_animator:nazuti/anim/flying_damage/end
execute as @e[type=armor_stand,tag=NazutiParts] run function #asa_matrix:animate
function asa_animator:nazuti/model

execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:nazuti/manager/model/change_to_normal
execute if entity @s[scores={AsaMatrix=10}] at @s run function asa_animator:nazuti/anim/flying_damage/events/pos/set_pos
execute if entity @s[scores={AsaMatrix=11..20}] run function asa_animator:nazuti/anim/flying_damage/events/pos/offset
execute if entity @s[scores={AsaMatrix=10}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=21}] positioned ~ ~1.5 ~ run function asa_animator:nazuti/manager/particle/step
execute if entity @s[scores={AsaMatrix=32}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=49}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7