# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:zinogre/anim/destroy_arm_l/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:zinogre/anim/destroy_arm_l/keyframes/0
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^-0.5 ^0.03 ^-0.06 ~2 ~
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:zinogre/anim/destroy_arm_l/keyframes/1
execute if entity @s[scores={AsaMatrix=6..10}] run tp @s ^-0.2 ^0.03 ^-0.06 ~2 ~
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:zinogre/anim/destroy_arm_l/keyframes/2
execute if entity @s[scores={AsaMatrix=11..15}] run tp @s ^-0.05 ^0.06 ^0
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:zinogre/anim/destroy_arm_l/keyframes/3
execute if entity @s[scores={AsaMatrix=16..23}] run tp @s ^0 ^-0.1 ^0.05
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:zinogre/anim/destroy_arm_l/keyframes/4
execute if entity @s[scores={AsaMatrix=24..32}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:zinogre/anim/destroy_arm_l/keyframes/5
execute if entity @s[scores={AsaMatrix=33..50}] run tp @s ^-0.1 ^0.01538462 ^0.01538462 ~-1 ~
execute if entity @s[scores={AsaMatrix=51..}] run function asa_animator:zinogre/anim/destroy_arm_l/end
execute as @e[type=armor_stand,tag=ZinogreParts] run function #asa_matrix:animate
function asa_animator:zinogre/model

# 演出
    execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:zinogre/manager/particle/step
    execute if entity @s[scores={AsaMatrix=23}] run function asa_animator:zinogre/manager/particle/step
    execute if entity @s[scores={AsaMatrix=23}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.7
    execute if entity @s[scores={AsaMatrix=32}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7

# 高度調整
    execute if entity @s[scores={AsaMatrix=1}] at @s positioned ~ ~5 ~ run tp @s ~ ~ ~
    execute if entity @s[scores={AsaMatrix=1}] at @s positioned ~ ~5 ~ run function asa_animator:zinogre/manager/check_ground
    execute if entity @s[scores={AsaMatrix=23..32}] if block ~ ~0.1 ~ #asa_animator:no_collision run function asa_animator:zinogre/manager/check_ground
    execute if entity @s[scores={AsaMatrix=23..32}] unless block ~ ~0.3 ~ #asa_animator:no_collision run tp @s ~ ~0.1 ~
    execute if entity @s[scores={AsaMatrix=44..}] if block ~ ~-0.2 ~ #asa_animator:no_collision run function asa_animator:zinogre/manager/check_ground
    execute if entity @s[scores={AsaMatrix=44..}] unless block ~ ~ ~ #asa_animator:no_collision run tp @s ~ ~0.1 ~