# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:narga/anim/jump_move_r_anger/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:narga/anim/jump_move_r_anger/keyframes/0
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^0.06666666 ^-0.024 ^-0.1
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:narga/anim/jump_move_r_anger/keyframes/1
execute if entity @s[scores={AsaMatrix=6..11}] run tp @s ^-0.05555555 ^0.52 ^0.08333334
execute if entity @s[scores={AsaMatrix=12}] run function asa_animator:narga/anim/jump_move_r_anger/keyframes/2
execute if entity @s[scores={AsaMatrix=12..15}] run tp @s ^0 ^-0.375 ^0
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:narga/anim/jump_move_r_anger/keyframes/3
execute if entity @s[scores={AsaMatrix=16..20}] run tp @s ^-0.05 ^-0.318 ^-0.1
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:narga/anim/jump_move_r_anger/keyframes/4
execute if entity @s[scores={AsaMatrix=21..28}] run tp @s ^-0.03125 ^-0.01125 ^-0.0625
execute if entity @s[scores={AsaMatrix=29..}] run function asa_animator:narga/anim/jump_move_r_anger/end
execute as @e[type=armor_stand,tag=NargaParts] run function #asa_matrix:animate
function asa_animator:narga/model

function asa_animator:narga/manager/rotate
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:narga/manager/particle/jump
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:narga/manager/particle/jump
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:narga/anim/jump_move_r/events/pos/set_pos
execute if entity @s[scores={AsaMatrix=6..20}] run function asa_animator:narga/anim/jump_move_r/events/pos/offset

execute if entity @s[scores={AsaMatrix=20}] run function asa_animator:narga/anim/blade_r_anger/events/pos/set_pos
execute if entity @s[scores={AsaMatrix=21..}] run function asa_animator:narga/manager/ground