# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:narga/anim/move/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:narga/anim/move/keyframes/0
execute if entity @s[scores={AsaMatrix=1..3}] run tp @s ^0 ^0.05 ^0
execute if entity @s[scores={AsaMatrix=4}] run function asa_animator:narga/anim/move/keyframes/1
execute if entity @s[scores={AsaMatrix=4..6}] run tp @s ^0 ^-0.05 ^0
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:narga/anim/move/keyframes/2
execute if entity @s[scores={AsaMatrix=7..9}] run tp @s ^0 ^0.05 ^0
execute if entity @s[scores={AsaMatrix=10}] run function asa_animator:narga/anim/move/keyframes/3
execute if entity @s[scores={AsaMatrix=10..12}] run tp @s ^0 ^-0.05 ^0
execute if entity @s[scores={AsaMatrix=13..}] run function asa_animator:narga/anim/move/end
execute as @e[type=armor_stand,tag=NargaParts] run function #asa_matrix:animate
function asa_animator:narga/model

execute at @s if block ^ ^ ^1 #asa_animator:no_collision run tp @s ^ ^ ^1 ~ ~
execute at @s unless block ^ ^ ^1 #asa_animator:no_collision if block ^ ^1 ^1 #asa_animator:no_collision run tp @s ^ ^1 ^1 ~ ~
execute if entity @s[tag=MoveLeft] at @s run tp @s ^ ^ ^ ~-6 ~
execute unless entity @s[tag=MoveLeft] at @s run tp @s ^ ^ ^ ~6 ~
function asa_animator:narga/manager/ground

particle block grass_block ~ ~ ~ 1 0.1 1 0 5
execute if entity @s[scores={AsaMatrix=3}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=9}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7