# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:kushala/anim/step_turn_r/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:kushala/anim/step_turn_r/keyframes/0
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:kushala/anim/step_turn_r/keyframes/1
execute if entity @s[scores={AsaMatrix=6..10}] run tp @s ^0 ^0.44 ^0
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:kushala/anim/step_turn_r/keyframes/2
execute if entity @s[scores={AsaMatrix=11..16}] run tp @s ^0 ^0.06666664 ^0
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:kushala/anim/step_turn_r/keyframes/3
execute if entity @s[scores={AsaMatrix=17..23}] run tp @s ^0 ^-0.3714285 ^0.3
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:kushala/anim/step_turn_r/keyframes/4
execute if entity @s[scores={AsaMatrix=24..28}] run tp @s ^-0.04 ^0 ^0
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:kushala/anim/step_turn_r/keyframes/5
execute if entity @s[scores={AsaMatrix=29..33}] run tp @s ^-0.04 ^0 ^0
execute if entity @s[scores={AsaMatrix=34..}] run function asa_animator:kushala/anim/step_turn_r/end
execute as @e[type=armor_stand,tag=KushalaParts] run function #asa_matrix:animate
function asa_animator:kushala/model

execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:kushala/manager/model/change_to_open
execute if entity @s[scores={AsaMatrix=33}] run function asa_animator:kushala/manager/model/change_to_normal
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:kushala/manager/particle/step
execute if entity @s[scores={AsaMatrix=23}] run function asa_animator:kushala/manager/particle/step
execute if entity @s[scores={AsaMatrix=23..30}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=11}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7

execute if entity @s[scores={AsaMatrix=..5}] run function asa_animator:kushala/anim/step_turn_l/events/rotate
execute if entity @s[scores={AsaMatrix=1}] at @s run function asa_animator:kushala/anim/step_turn_r/events/pos/set_pos
execute if entity @s[scores={AsaMatrix=6}] run kill @e[type=marker,tag=KushalaMovePos]
execute if entity @s[scores={AsaMatrix=6..23}] run function asa_animator:kushala/anim/step_turn_l/events/pos/offset

execute if entity @s[scores={AsaMatrix=17..}] at @s run function asa_animator:kushala/manager/rotate

execute if entity @s[scores={AsaMatrix=23..}] at @s if block ~ ~-0.2 ~ #asa_animator:no_collision at @s run function asa_animator:zinogre/manager/check_ground
execute if entity @s[scores={AsaMatrix=23..}] at @s unless block ~ ~ ~ #asa_animator:no_collision at @s run tp @s ~ ~0.1 ~ ~ ~