# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:diablos/anim/normal/move/start
execute if score @s AsaMatrix matches 1 run function asa_animator:diablos/anim/normal/move/keyframes/0
execute if score @s AsaMatrix matches 1..5 run tp @s ^0 ^0.06 ^0.8
execute if score @s AsaMatrix matches 6 run function asa_animator:diablos/anim/normal/move/keyframes/1
execute if score @s AsaMatrix matches 6..10 run tp @s ^0 ^-0.06 ^0.8
execute if score @s AsaMatrix matches 11 run function asa_animator:diablos/anim/normal/move/keyframes/2
execute if score @s AsaMatrix matches 11..15 run tp @s ^0 ^0.06 ^0.8
execute if score @s AsaMatrix matches 16 run function asa_animator:diablos/anim/normal/move/keyframes/3
execute if score @s AsaMatrix matches 16..20 run tp @s ^0 ^-0.06 ^0.8
execute if score @s AsaMatrix matches 21.. run function asa_animator:diablos/anim/normal/move/end
execute as @e[type=armor_stand,tag=DiablosParts] run function #asa_matrix:animate
function asa_animator:diablos/model

# 敵の方向を向く
function asa_animator:diablos/manager/rotate

# 高度調整
execute at @s if block ~ ~-0.2 ~ #asa_animator:no_collision at @s run function asa_animator:zinogre/manager/check_ground
execute at @s unless block ~ ~ ~ #asa_animator:no_collision at @s run tp @s ~ ~0.1 ~ ~ ~

# 敵に十分近づいた場合，噛みつきに遷移
execute positioned ^ ^ ^4 if entity @e[tag=DiablosAttackTarget,distance=0..4] run function asa_animator:diablos/anim/normal/move/events/change

execute if score @s AsaMatrix matches 6 run playsound entity.iron_golem.step master @a ~ ~ ~ 2 0.7
execute if score @s AsaMatrix matches 16 run playsound entity.iron_golem.step master @a ~ ~ ~ 2 0.7