# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:diablos/anim/anger/stay/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:diablos/anim/anger/stay/keyframes/0
execute if entity @s[scores={AsaMatrix=1..8}] run tp @s ^0 ^-0.00625 ^-0.0125
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:diablos/anim/anger/stay/keyframes/1
execute if entity @s[scores={AsaMatrix=9..13}] run tp @s ^0 ^0.01 ^0.02
execute if entity @s[scores={AsaMatrix=14}] run function asa_animator:diablos/anim/anger/stay/keyframes/2
execute if entity @s[scores={AsaMatrix=14..17}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=18}] run function asa_animator:diablos/anim/anger/stay/keyframes/3
execute if entity @s[scores={AsaMatrix=18..21}] run tp @s ^0 ^-0.0125 ^0.05
execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:diablos/anim/anger/stay/keyframes/4
execute if entity @s[scores={AsaMatrix=22..34}] run tp @s ^0 ^0.003846154 ^0.01538462
execute if entity @s[scores={AsaMatrix=35}] run function asa_animator:diablos/anim/anger/stay/keyframes/5
execute if entity @s[scores={AsaMatrix=35..47}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=48}] run function asa_animator:diablos/anim/anger/stay/keyframes/6
execute if entity @s[scores={AsaMatrix=48..56}] run tp @s ^0 ^0 ^-0.04444445
execute if entity @s[scores={AsaMatrix=57..}] run function asa_animator:diablos/anim/normal/stay/end
execute as @e[type=armor_stand,tag=DiablosParts] run function #asa_matrix:animate
function asa_animator:diablos/model

execute if entity @s[scores={AsaMatrix=1}] if score #mhdp_diablos_actcount AsaMatrix matches 1.. run function asa_animator:diablos/anim/normal/stay/events/change

execute at @s if block ~ ~-0.2 ~ #asa_animator:no_collision at @s run function asa_animator:zinogre/manager/check_ground
execute at @s unless block ~ ~ ~ #asa_animator:no_collision at @s run tp @s ~ ~0.1 ~ ~ ~