# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:dyno/anim/destroy_leg_l/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:dyno/anim/destroy_leg_l/keyframes/0
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^-0.3 ^0.08 ^-0.1 ~-11 ~
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:dyno/anim/destroy_leg_l/keyframes/1
execute if entity @s[scores={AsaMatrix=6..10}] run tp @s ^-0.1 ^-0.02 ^-0.1 ~-8 ~
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:dyno/anim/destroy_leg_l/keyframes/2
execute if entity @s[scores={AsaMatrix=11..18}] run tp @s ^-0.125 ^-0.075 ^-0.1
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:dyno/anim/destroy_leg_l/keyframes/3
execute if entity @s[scores={AsaMatrix=19..23}] run tp @s ^0 ^0 ^-0.1 ~-1 ~
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:dyno/anim/destroy_leg_l/keyframes/4
execute if entity @s[scores={AsaMatrix=24..38}] run tp @s ^0.06666667 ^0.01 ^0.01 ~1 ~
execute if entity @s[scores={AsaMatrix=39}] run function asa_animator:dyno/anim/destroy_leg_l/keyframes/5
execute if entity @s[scores={AsaMatrix=39..55}] run tp @s ^0 ^0.00882353 ^0.00882353
execute if entity @s[scores={AsaMatrix=56..}] run function asa_animator:dyno/anim/destroy_leg_l/end
execute as @e[type=armor_stand,tag=DynoParts] run function #asa_matrix:animate
function asa_animator:dyno/model

execute if entity @s[scores={AsaMatrix=18..}] at @s positioned ~ ~5 ~ run tp @s ~ ~ ~
execute if entity @s[scores={AsaMatrix=18..}] at @s positioned ~ ~5 ~ run function asa_animator:zinogre/manager/check_ground
execute if entity @s[scores={AsaMatrix=18}] run function asa_animator:dyno/manager/particle/jump