# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:zinogre/anim/hand_3/start
execute if score @s AsaMatrix matches 1 run function asa_animator:zinogre/anim/hand_3/keyframes/0
execute if score @s AsaMatrix matches 1..5 run tp @s ^0 ^0.16 ^0
execute if score @s AsaMatrix matches 6 run function asa_animator:zinogre/anim/hand_3/keyframes/1
execute if score @s AsaMatrix matches 6..10 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 11 run function asa_animator:zinogre/anim/hand_3/keyframes/2
execute if score @s AsaMatrix matches 11..16 run tp @s ^0 ^-0.1833333 ^0
execute if score @s AsaMatrix matches 17 run function asa_animator:zinogre/anim/hand_3/keyframes/3
execute if score @s AsaMatrix matches 17..18 run tp @s ^0 ^0.15 ^0
execute if score @s AsaMatrix matches 19 run function asa_animator:zinogre/anim/hand_3/keyframes/4
execute if score @s AsaMatrix matches 19..25 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 26 run function asa_animator:zinogre/anim/hand_3/keyframes/5
execute if score @s AsaMatrix matches 26..30 run tp @s ^0 ^0.16 ^0
execute if score @s AsaMatrix matches 31 run function asa_animator:zinogre/anim/hand_3/keyframes/6
execute if score @s AsaMatrix matches 31..35 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 36 run function asa_animator:zinogre/anim/hand_3/keyframes/7
execute if score @s AsaMatrix matches 36..40 run tp @s ^0 ^-0.22 ^0
execute if score @s AsaMatrix matches 41 run function asa_animator:zinogre/anim/hand_3/keyframes/8
execute if score @s AsaMatrix matches 41..43 run tp @s ^0 ^0.1 ^0
execute if score @s AsaMatrix matches 44 run function asa_animator:zinogre/anim/hand_3/keyframes/9
execute if score @s AsaMatrix matches 44..50 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 51 run function asa_animator:zinogre/anim/hand_3/keyframes/10
execute if score @s AsaMatrix matches 51..55 run tp @s ^0 ^0.16 ^0
execute if score @s AsaMatrix matches 56 run function asa_animator:zinogre/anim/hand_3/keyframes/11
execute if score @s AsaMatrix matches 56..60 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 61 run function asa_animator:zinogre/anim/hand_3/keyframes/12
execute if score @s AsaMatrix matches 61..65 run tp @s ^0 ^-0.22 ^0
execute if score @s AsaMatrix matches 66 run function asa_animator:zinogre/anim/hand_3/keyframes/13
execute if score @s AsaMatrix matches 66..68 run tp @s ^0 ^0.1 ^0
execute if score @s AsaMatrix matches 69 run function asa_animator:zinogre/anim/hand_3/keyframes/14
execute if score @s AsaMatrix matches 69..80 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 81 run function asa_animator:zinogre/anim/hand_3/keyframes/15
execute if score @s AsaMatrix matches 81..95 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 96.. run function asa_animator:zinogre/anim/hand_3/end
execute as @e[type=armor_stand,tag=ZinogreParts] run function #asa_matrix:animate
function asa_animator:zinogre/model

execute if score @s AsaMatrix matches 0..8 run function asa_animator:zinogre/manager/rotate_fast
execute if score @s AsaMatrix matches 0..10 at @s unless entity @e[tag=ZinogreAttackTarget,distance=0..4] run tp @s ^ ^ ^0.8 ~ ~
execute if score @s AsaMatrix matches 15 at @s positioned ^-2 ^ ^3 run function asa_animator:zinogre/anim/hand_3/events/damage

execute if score @s AsaMatrix matches 25..33 run function asa_animator:zinogre/manager/rotate_fast
execute if score @s AsaMatrix matches 25..35 at @s unless entity @e[tag=ZinogreAttackTarget,distance=0..4] run tp @s ^ ^ ^0.8 ~ ~
execute if score @s AsaMatrix matches 40 at @s positioned ^2 ^ ^3 run function asa_animator:zinogre/anim/hand_3/events/damage

execute if score @s AsaMatrix matches 50..58 run function asa_animator:zinogre/manager/rotate_fast
execute if score @s AsaMatrix matches 50..60 at @s unless entity @e[tag=ZinogreAttackTarget,distance=0..4] run tp @s ^ ^ ^0.8 ~ ~
execute if score @s AsaMatrix matches 65 at @s positioned ^-2 ^ ^3 run function asa_animator:zinogre/anim/hand_3/events/damage

execute if block ~ ~-1 ~ #asa_animator:no_collision run function asa_animator:zinogre/manager/check_ground
execute unless block ~ ~ ~ #asa_animator:no_collision run tp @s ~ ~0.5 ~ ~ ~