# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:kushala/anim/flying_anger/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:kushala/anim/flying_anger/keyframes/0
execute if entity @s[scores={AsaMatrix=1..8}] run tp @s ^0 ^-0.0625 ^0 ~0.5 ~
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:kushala/anim/flying_anger/keyframes/1
execute if entity @s[scores={AsaMatrix=9..18}] run tp @s ^0 ^0.01 ^0
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:kushala/anim/flying_anger/keyframes/2
execute if entity @s[scores={AsaMatrix=19..28}] run tp @s ^0 ^-0.01 ^0
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:kushala/anim/flying_anger/keyframes/3
execute if entity @s[scores={AsaMatrix=29..38}] run tp @s ^0 ^0.05 ^0
execute if entity @s[scores={AsaMatrix=39..}] run function asa_animator:kushala/anim/flying_anger/end
execute as @e[type=armor_stand,tag=KushalaParts] run function #asa_matrix:animate
function asa_animator:kushala/model

execute if entity @s[scores={AsaMatrix=8}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=28}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7

execute if entity @s[scores={AsaMatrix=1..5}] run playsound minecraft:entity.phantom.death master @a ~ ~ ~ 2 0.8
execute if entity @s[scores={AsaMatrix=1..5}] run playsound minecraft:entity.phantom.death master @a ~ ~ ~ 2 0.6