# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:narga/anim/tail_bitan/start
execute if score @s AsaMatrix matches 1 run function asa_animator:narga/anim/tail_bitan/keyframes/0
execute if score @s AsaMatrix matches 1..5 run tp @s ^0 ^0.02 ^0.04
execute if score @s AsaMatrix matches 6 run function asa_animator:narga/anim/tail_bitan/keyframes/1
execute if score @s AsaMatrix matches 6..10 run tp @s ^0.04 ^-0.04 ^0.06
execute if score @s AsaMatrix matches 11 run function asa_animator:narga/anim/tail_bitan/keyframes/2
execute if score @s AsaMatrix matches 11..17 run tp @s ^0 ^-0.001785714 ^0
execute if score @s AsaMatrix matches 18 run function asa_animator:narga/anim/tail_bitan/keyframes/3
execute if score @s AsaMatrix matches 18..24 run tp @s ^0 ^-0.001785715 ^0
execute if score @s AsaMatrix matches 25 run function asa_animator:narga/anim/tail_bitan/keyframes/4
execute if score @s AsaMatrix matches 25..30 run tp @s ^0 ^-0.002083334 ^0
execute if score @s AsaMatrix matches 31 run function asa_animator:narga/anim/tail_bitan/keyframes/5
execute if score @s AsaMatrix matches 31..37 run tp @s ^0 ^0.3053572 ^0
execute if score @s AsaMatrix matches 38 run function asa_animator:narga/anim/tail_bitan/keyframes/6
execute if score @s AsaMatrix matches 38..44 run tp @s ^-0.1428571 ^0.5714286 ^-0.1857143 ~1 ~
execute if score @s AsaMatrix matches 45 run function asa_animator:narga/anim/tail_bitan/keyframes/7
execute if score @s AsaMatrix matches 45..51 run tp @s ^0.07142857 ^-0.4285714 ^-0.05714286 ~0.5 ~
execute if score @s AsaMatrix matches 52 run function asa_animator:narga/anim/tail_bitan/keyframes/8
execute if score @s AsaMatrix matches 52..58 run tp @s ^0 ^-0.4714286 ^-0.02857142
execute if score @s AsaMatrix matches 59 run function asa_animator:narga/anim/tail_bitan/keyframes/9
execute if score @s AsaMatrix matches 59..70 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 71 run function asa_animator:narga/anim/tail_bitan/keyframes/10
execute if score @s AsaMatrix matches 71..75 run tp @s ^0 ^0.01 ^-0.008000016
execute if score @s AsaMatrix matches 76 run function asa_animator:narga/anim/tail_bitan/keyframes/11
execute if score @s AsaMatrix matches 76..80 run tp @s ^0 ^-0.01 ^0.008000016
execute if score @s AsaMatrix matches 81 run function asa_animator:narga/anim/tail_bitan/keyframes/12
execute if score @s AsaMatrix matches 81..90 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 91 run function asa_animator:narga/anim/tail_bitan/keyframes/13
execute if score @s AsaMatrix matches 91..95 run tp @s ^0 ^0.01 ^-0.008000016
execute if score @s AsaMatrix matches 96 run function asa_animator:narga/anim/tail_bitan/keyframes/14
execute if score @s AsaMatrix matches 96..100 run tp @s ^0 ^-0.01 ^0.008000016
execute if score @s AsaMatrix matches 101 run function asa_animator:narga/anim/tail_bitan/keyframes/15
execute if score @s AsaMatrix matches 101..105 run tp @s ^0.14 ^0.08000001 ^-0.02000001
execute if score @s AsaMatrix matches 106 run function asa_animator:narga/anim/tail_bitan/keyframes/16
execute if score @s AsaMatrix matches 106..109 run tp @s ^0.025 ^0.025 ^0 ~-0.5 ~
execute if score @s AsaMatrix matches 110 run function asa_animator:narga/anim/tail_bitan/keyframes/17
execute if score @s AsaMatrix matches 110..116 run tp @s ^-0.03571429 ^-0.01428571 ^-0.2857143 ~-0.5 ~
execute if score @s AsaMatrix matches 117 run function asa_animator:narga/anim/tail_bitan/keyframes/18
execute if score @s AsaMatrix matches 117..125 run tp @s ^-0.02777778 ^-0.01111111 ^-0.2777778 ~-0.5 ~
execute if score @s AsaMatrix matches 126 run function asa_animator:narga/anim/tail_bitan/keyframes/19
execute if score @s AsaMatrix matches 126..130 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 131.. run function asa_animator:narga/anim/tail_bitan/end
execute as @e[type=armor_stand,tag=NargaParts] run function #asa_matrix:animate
function asa_animator:narga/model

execute if score @s AsaMatrix matches 10 run playsound entity.player.attack.sweep master @a ~ ~ ~ 2 0.7
execute if score @s AsaMatrix matches 25 run playsound entity.player.attack.sweep master @a ~ ~ ~ 2 0.85
execute if score @s AsaMatrix matches 36 run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if score @s AsaMatrix matches 36 run particle block grass_block ~ ~ ~ 1 0.1 1 0 10

execute if score @s AsaMatrix matches 58 run playsound entity.wither.break_block master @a ~ ~ ~ 2 0.8
execute if score @s AsaMatrix matches 74 run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if score @s AsaMatrix matches 94 run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if score @s AsaMatrix matches 94 run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if score @s AsaMatrix matches 101 run playsound block.grass.break master @a ~ ~ ~ 2 0.7
execute if score @s AsaMatrix matches 101 run particle block grass_block ^ ^ ^6 1 0.1 1 0 10

execute if score @s AsaMatrix matches 1 run function asa_animator:narga/anim/tail_bitan/events/change_to_anger
execute if score @s AsaMatrix matches 111 run function asa_animator:narga/anim/tail_bitan/events/change_to_normal

execute if score @s AsaMatrix matches 39..58 run function asa_animator:narga/anim/tail_bitan/events/particle_jump
execute if score @s AsaMatrix matches 58 run function asa_animator:narga/anim/tail_bitan/events/particle_attack