# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:tiga/anim/turn_r/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:tiga/anim/turn_r/keyframes/0
execute if entity @s[scores={AsaMatrix=1..4}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:tiga/anim/turn_r/keyframes/1
execute if entity @s[scores={AsaMatrix=5..8}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:tiga/anim/turn_r/keyframes/2
execute if entity @s[scores={AsaMatrix=9..12}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:tiga/anim/turn_r/keyframes/3
execute if entity @s[scores={AsaMatrix=13..16}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:tiga/anim/turn_r/keyframes/4
execute if entity @s[scores={AsaMatrix=17..24}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=25..}] run function asa_animator:tiga/anim/turn_r/end
execute as @e[type=armor_stand,tag=TigaParts] run function #asa_matrix:animate
function asa_animator:tiga/model

execute if entity @s[scores={AsaMatrix=4..}] run function asa_animator:tiga/manager/rotate
execute if entity @s[scores={AsaMatrix=4}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=12}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.7