# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:reus/anger/bite/start
execute if score @s AsaMatrix matches 1 run function asa_animator:reus/anger/bite/keyframes/0
execute if score @s AsaMatrix matches 6 run function asa_animator:reus/anger/bite/keyframes/1
execute if score @s AsaMatrix matches 6..8 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 9 run function asa_animator:reus/anger/bite/keyframes/2
execute if score @s AsaMatrix matches 9..14 run tp @s ^0 ^0 ^0.1333333
execute if score @s AsaMatrix matches 15 run function asa_animator:reus/anger/bite/keyframes/3
execute if score @s AsaMatrix matches 15..22 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 23 run function asa_animator:reus/anger/bite/keyframes/4
execute if score @s AsaMatrix matches 23..33 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 34.. run function asa_animator:reus/anger/bite/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model

# ダメージ
execute if score @s AsaMatrix matches 10 positioned ^ ^ ^5 run function asa_animator:reus/normal/bite/effect/damage

# 敵を向く
execute if score @s AsaMatrix matches 1..5 run function asa_animator:reus/manager/rotate_fast

# 効果音
execute if score @s AsaMatrix matches 1 run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7