# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:brachyr/anim/charge_large_bomb/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:brachyr/anim/charge_large_bomb/keyframes/0
execute if entity @s[scores={AsaMatrix=1..10}] run tp @s ^0 ^0.02 ^0
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:brachyr/anim/charge_large_bomb/keyframes/1
execute if entity @s[scores={AsaMatrix=11..25}] run tp @s ^0 ^0.02 ^-0.01333333
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:brachyr/anim/charge_large_bomb/keyframes/2
execute if entity @s[scores={AsaMatrix=26..40}] run tp @s ^0 ^-0.02666667 ^-0.01333333
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:brachyr/anim/charge_large_bomb/keyframes/3
execute if entity @s[scores={AsaMatrix=41..47}] run tp @s ^0 ^-0.007142857 ^0.02857143
execute if entity @s[scores={AsaMatrix=48}] run function asa_animator:brachyr/anim/charge_large_bomb/keyframes/4
execute if entity @s[scores={AsaMatrix=48..48}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=49}] run function asa_animator:brachyr/anim/charge_large_bomb/keyframes/5
execute if entity @s[scores={AsaMatrix=49..55}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=56}] run function asa_animator:brachyr/anim/charge_large_bomb/keyframes/6
execute if entity @s[scores={AsaMatrix=56..62}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=63}] run function asa_animator:brachyr/anim/charge_large_bomb/keyframes/7
execute if entity @s[scores={AsaMatrix=63..67}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=68}] run function asa_animator:brachyr/anim/charge_large_bomb/keyframes/8
execute if entity @s[scores={AsaMatrix=68..87}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=88}] run function asa_animator:brachyr/anim/charge_large_bomb/keyframes/9
execute if entity @s[scores={AsaMatrix=88..97}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=98}] run function asa_animator:brachyr/anim/charge_large_bomb/keyframes/10
execute if entity @s[scores={AsaMatrix=98..104}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=105}] run function asa_animator:brachyr/anim/charge_large_bomb/keyframes/11
execute if entity @s[scores={AsaMatrix=105..109}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=110}] run function asa_animator:brachyr/anim/charge_large_bomb/keyframes/12
execute if entity @s[scores={AsaMatrix=110..129}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=130}] run function asa_animator:brachyr/anim/charge_large_bomb/keyframes/13
execute if entity @s[scores={AsaMatrix=130..137}] run tp @s ^0 ^-0.003125 ^0.0125
execute if entity @s[scores={AsaMatrix=138}] run function asa_animator:brachyr/anim/charge_large_bomb/keyframes/14
execute if entity @s[scores={AsaMatrix=138..147}] run tp @s ^0 ^0.0275 ^-0.04
execute if entity @s[scores={AsaMatrix=148}] run function asa_animator:brachyr/anim/charge_large_bomb/keyframes/15
execute if entity @s[scores={AsaMatrix=148..157}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=158}] run function asa_animator:brachyr/anim/charge_large_bomb/keyframes/16
execute if entity @s[scores={AsaMatrix=158..160}] run tp @s ^0 ^0.08333334 ^0.2166667
execute if entity @s[scores={AsaMatrix=161}] run function asa_animator:brachyr/anim/charge_large_bomb/keyframes/17
execute if entity @s[scores={AsaMatrix=161..163}] run tp @s ^0 ^-0.2166667 ^0.15
execute if entity @s[scores={AsaMatrix=164}] run function asa_animator:brachyr/anim/charge_large_bomb/keyframes/18
execute if entity @s[scores={AsaMatrix=164..166}] run tp @s ^0 ^0 ^-0.06666667
execute if entity @s[scores={AsaMatrix=167}] run function asa_animator:brachyr/anim/charge_large_bomb/keyframes/19
execute if entity @s[scores={AsaMatrix=167..181}] run tp @s ^0 ^-0.01333333 ^0
execute if entity @s[scores={AsaMatrix=182}] run function asa_animator:brachyr/anim/charge_large_bomb/keyframes/20
execute if entity @s[scores={AsaMatrix=182..196}] run tp @s ^0 ^0.01666667 ^-0.03666667
execute if entity @s[scores={AsaMatrix=197}] run function asa_animator:brachyr/anim/charge_large_bomb/keyframes/21
execute if entity @s[scores={AsaMatrix=197..211}] run tp @s ^0 ^0.003333333 ^0.01
execute if entity @s[scores={AsaMatrix=212..}] run function asa_animator:brachyr/anim/charge_large_bomb/end
execute as @e[type=armor_stand,tag=BrachyRParts] run function #asa_matrix:animate
function asa_animator:brachyr/model

execute if entity @s[scores={AsaMatrix=1}] run playsound block.grass.step master @a ~ ~ ~ 2 0.5
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:brachyr/anim/charge_large_bomb/events/active
execute if entity @s[scores={AsaMatrix=11..48}] as @e[type=armor_stand,tag=BrachyRParts,tag=HeadU,distance=0..10] at @s positioned ~ ~1.4 ~ run particle flash ~ ~ ~ 0 0 0 0 1
execute if entity @s[scores={AsaMatrix=11}] run playsound entity.blaze.death master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=11}] run playsound entity.blaze.death master @a ~ ~ ~ 2 0.6
execute if entity @s[scores={AsaMatrix=11}] run particle block grass_block ^ ^ ^2 2 0.1 2 0 30

execute if entity @s[scores={AsaMatrix=67}] positioned ^-2 ^ ^4 run function asa_animator:brachyr/anim/punch_r/events/damage
execute if entity @s[scores={AsaMatrix=67..87}] positioned ^-2 ^ ^4 run function asa_animator:brachyr/anim/charge_large_bomb/events/shot_r

execute if entity @s[scores={AsaMatrix=109}] positioned ^2 ^ ^4 run function asa_animator:brachyr/anim/punch_l/events/damage
execute if entity @s[scores={AsaMatrix=109..129}] positioned ^2 ^ ^4 run function asa_animator:brachyr/anim/charge_large_bomb/events/shot_l

execute if entity @s[scores={AsaMatrix=163}] positioned ^ ^ ^6 run function asa_animator:brachyr/anim/head_bomb/events/damage
execute if entity @s[scores={AsaMatrix=163..183}] positioned ^ ^ ^6 run function asa_animator:brachyr/anim/charge_large_bomb/events/shot_h


execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:brachyr/anim/voice/events/damage