# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/flying_jump/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:reus/anim/flying_jump/keyframes/0
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^0 ^0.02 ^0
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:reus/anim/flying_jump/keyframes/1
execute if entity @s[scores={AsaMatrix=6..10}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:reus/anim/flying_jump/keyframes/2
execute if entity @s[scores={AsaMatrix=11..30}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:reus/anim/flying_jump/keyframes/3
execute if entity @s[scores={AsaMatrix=31..35}] run tp @s ^0 ^-0.1 ^0
execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:reus/anim/flying_jump/keyframes/4
execute if entity @s[scores={AsaMatrix=36..40}] run tp @s ^0 ^1.48 ^-0.04
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:reus/anim/flying_jump/keyframes/5
execute if entity @s[scores={AsaMatrix=41..50}] run tp @s ^0 ^0.05 ^-0.03
execute if entity @s[scores={AsaMatrix=51}] run function asa_animator:reus/anim/flying_jump/keyframes/6
execute if entity @s[scores={AsaMatrix=51..55}] run tp @s ^0 ^-1.58 ^0.1
execute if entity @s[scores={AsaMatrix=56}] run function asa_animator:reus/anim/flying_jump/keyframes/7
execute if entity @s[scores={AsaMatrix=56..63}] run tp @s ^0 ^0 ^0 ~-0.5 ~
execute if entity @s[scores={AsaMatrix=64}] run function asa_animator:reus/anim/flying_jump/keyframes/8
execute if entity @s[scores={AsaMatrix=64..75}] run tp @s ^0 ^0.03333334 ^0
execute if entity @s[scores={AsaMatrix=76..}] run function asa_animator:reus/anim/flying_jump/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model

# 敵の方向を向く
execute if entity @s[scores={AsaMatrix=1..34}] at @s run function asa_animator:reus/manager/rotate
execute if entity @s[scores={AsaMatrix=28}] run function asa_animator:reus/anim/flying_jump/events/set_pos
execute if entity @s[scores={AsaMatrix=36..55}] at @s run function asa_animator:reus/anim/flying_jump/events/offset

execute if entity @s[scores={AsaMatrix=1}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=35}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7

execute if entity @s[scores={AsaMatrix=56}] positioned ^ ^ ^1 run function asa_animator:reus/anim/jump/events/damage

execute if entity @s[scores={AsaMatrix=56..}] at @s if block ~ ~-0.2 ~ #asa_animator:no_collision at @s run function asa_animator:zinogre/manager/check_ground
execute if entity @s[scores={AsaMatrix=56..}] at @s unless block ~ ~ ~ #asa_animator:no_collision at @s run tp @s ~ ~0.1 ~ ~ ~