# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:magara/anim/flying_move_forward/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:magara/anim/flying_move_forward/keyframes/0
execute if entity @s[scores={AsaMatrix=1..6}] run tp @s ^0 ^0.2166667 ^0
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:magara/anim/flying_move_forward/keyframes/1
execute if entity @s[scores={AsaMatrix=7..14}] run tp @s ^0 ^-0.075 ^0
execute if entity @s[scores={AsaMatrix=15}] run function asa_animator:magara/anim/flying_move_forward/keyframes/2
execute if entity @s[scores={AsaMatrix=15..20}] run tp @s ^0 ^-0.1166667 ^0
execute if entity @s[scores={AsaMatrix=21..}] run function asa_animator:magara/anim/flying_move_forward/end
execute as @e[type=armor_stand,tag=MagaraParts] run function #asa_matrix:animate
function asa_animator:magara/model

# 移動
    execute at @s run function asa_animator:magara/manager/rotate
    execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:magara/anim/flying_move_forward/events/pos/set_pos
    execute if entity @s[scores={AsaMatrix=2..14}] run function asa_animator:magara/anim/flying_move_forward/events/pos/offset

# 演出
    execute if entity @s[scores={AsaMatrix=6}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.5
