# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:brachyr/anim/rage/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:brachyr/anim/rage/keyframes/0
execute if entity @s[scores={AsaMatrix=1..7}] run tp @s ^0 ^0.02857143 ^-0.01428571 ~1 ~
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:brachyr/anim/rage/keyframes/1
execute if entity @s[scores={AsaMatrix=8..15}] run tp @s ^0 ^0.0125 ^-0.0125 ~-1 ~
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:brachyr/anim/rage/keyframes/2
execute if entity @s[scores={AsaMatrix=16..25}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:brachyr/anim/rage/keyframes/3
execute if entity @s[scores={AsaMatrix=26..28}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:brachyr/anim/rage/keyframes/4
execute if entity @s[scores={AsaMatrix=29..33}] run tp @s ^0 ^-0.12 ^0.04
execute if entity @s[scores={AsaMatrix=34}] run function asa_animator:brachyr/anim/rage/keyframes/5
execute if entity @s[scores={AsaMatrix=34..40}] run tp @s ^0 ^0.08571429 ^-0.02857143
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:brachyr/anim/rage/keyframes/6
execute if entity @s[scores={AsaMatrix=41..45}] run tp @s ^0 ^-0.12 ^0.04
execute if entity @s[scores={AsaMatrix=46}] run function asa_animator:brachyr/anim/rage/keyframes/7
execute if entity @s[scores={AsaMatrix=46..52}] run tp @s ^0 ^0.08571429 ^-0.02857143
execute if entity @s[scores={AsaMatrix=53}] run function asa_animator:brachyr/anim/rage/keyframes/8
execute if entity @s[scores={AsaMatrix=53..57}] run tp @s ^0 ^-0.12 ^0.04
execute if entity @s[scores={AsaMatrix=58}] run function asa_animator:brachyr/anim/rage/keyframes/9
execute if entity @s[scores={AsaMatrix=58..62}] run tp @s ^0 ^0.12 ^-0.04
execute if entity @s[scores={AsaMatrix=63}] run function asa_animator:brachyr/anim/rage/keyframes/10
execute if entity @s[scores={AsaMatrix=63..66}] run tp @s ^0 ^-0.15 ^0.05
execute if entity @s[scores={AsaMatrix=67}] run function asa_animator:brachyr/anim/rage/keyframes/11
execute if entity @s[scores={AsaMatrix=67..70}] run tp @s ^0 ^0.15 ^-0.05
execute if entity @s[scores={AsaMatrix=71}] run function asa_animator:brachyr/anim/rage/keyframes/12
execute if entity @s[scores={AsaMatrix=71..73}] run tp @s ^0 ^-0.2 ^0.06666667
execute if entity @s[scores={AsaMatrix=74}] run function asa_animator:brachyr/anim/rage/keyframes/13
execute if entity @s[scores={AsaMatrix=74..76}] run tp @s ^0 ^0.2 ^-0.06666667
execute if entity @s[scores={AsaMatrix=77}] run function asa_animator:brachyr/anim/rage/keyframes/14
execute if entity @s[scores={AsaMatrix=77..79}] run tp @s ^0 ^-0.2 ^0.06666667
execute if entity @s[scores={AsaMatrix=80}] run function asa_animator:brachyr/anim/rage/keyframes/15
execute if entity @s[scores={AsaMatrix=80..82}] run tp @s ^0 ^0.2 ^-0.06666667
execute if entity @s[scores={AsaMatrix=83}] run function asa_animator:brachyr/anim/rage/keyframes/16
execute if entity @s[scores={AsaMatrix=83..85}] run tp @s ^0 ^-0.2 ^0.06666667
execute if entity @s[scores={AsaMatrix=86}] run function asa_animator:brachyr/anim/rage/keyframes/17
execute if entity @s[scores={AsaMatrix=86..88}] run tp @s ^0 ^0.2 ^-0.06666667
execute if entity @s[scores={AsaMatrix=89}] run function asa_animator:brachyr/anim/rage/keyframes/18
execute if entity @s[scores={AsaMatrix=89..91}] run tp @s ^0 ^-0.2 ^0.06666667
execute if entity @s[scores={AsaMatrix=92}] run function asa_animator:brachyr/anim/rage/keyframes/19
execute if entity @s[scores={AsaMatrix=92..94}] run tp @s ^0 ^0.2 ^-0.06666667
execute if entity @s[scores={AsaMatrix=95}] run function asa_animator:brachyr/anim/rage/keyframes/20
execute if entity @s[scores={AsaMatrix=95..97}] run tp @s ^0 ^-0.2 ^0.06666667
execute if entity @s[scores={AsaMatrix=98}] run function asa_animator:brachyr/anim/rage/keyframes/21
execute if entity @s[scores={AsaMatrix=98..100}] run tp @s ^0 ^0.2 ^-0.06666667
execute if entity @s[scores={AsaMatrix=101}] run function asa_animator:brachyr/anim/rage/keyframes/22
execute if entity @s[scores={AsaMatrix=101..103}] run tp @s ^0 ^-0.2 ^0.06666667
execute if entity @s[scores={AsaMatrix=104}] run function asa_animator:brachyr/anim/rage/keyframes/23
execute if entity @s[scores={AsaMatrix=104..110}] run tp @s ^0 ^0.08571429 ^-0.02857143
execute if entity @s[scores={AsaMatrix=111}] run function asa_animator:brachyr/anim/rage/keyframes/24
execute if entity @s[scores={AsaMatrix=111..120}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=121}] run function asa_animator:brachyr/anim/rage/keyframes/25
execute if entity @s[scores={AsaMatrix=121..130}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=131}] run function asa_animator:brachyr/anim/rage/keyframes/26
execute if entity @s[scores={AsaMatrix=131..135}] run tp @s ^0 ^-0.12 ^0.04
execute if entity @s[scores={AsaMatrix=136}] run function asa_animator:brachyr/anim/rage/keyframes/27
execute if entity @s[scores={AsaMatrix=136..138}] run tp @s ^0 ^0.1333333 ^0.06666667
execute if entity @s[scores={AsaMatrix=139}] run function asa_animator:brachyr/anim/rage/keyframes/28
execute if entity @s[scores={AsaMatrix=139..148}] run tp @s ^0 ^0.01 ^-0.02
execute if entity @s[scores={AsaMatrix=149}] run function asa_animator:brachyr/anim/rage/keyframes/29
execute if entity @s[scores={AsaMatrix=149..163}] run tp @s ^0 ^0.02 ^-0.01333333
execute if entity @s[scores={AsaMatrix=164}] run function asa_animator:brachyr/anim/rage/keyframes/30
execute if entity @s[scores={AsaMatrix=164..178}] run tp @s ^0 ^-0.02666667 ^-0.01333333
execute if entity @s[scores={AsaMatrix=179}] run function asa_animator:brachyr/anim/rage/keyframes/31
execute if entity @s[scores={AsaMatrix=179..185}] run tp @s ^0 ^-0.007142857 ^0.02857143
execute if entity @s[scores={AsaMatrix=186}] run function asa_animator:brachyr/anim/rage/keyframes/32
execute if entity @s[scores={AsaMatrix=186..193}] run tp @s ^0 ^-0.00625 ^0.025
execute if entity @s[scores={AsaMatrix=194..}] run function asa_animator:brachyr/anim/rage/end
execute as @e[type=armor_stand,tag=BrachyRParts] run function #asa_matrix:animate
function asa_animator:brachyr/model

execute if entity @s[scores={AsaMatrix=33}] positioned ^ ^ ^3 run function asa_animator:brachyr/anim/rage/events/punch
execute if entity @s[scores={AsaMatrix=45}] positioned ^ ^ ^3 run function asa_animator:brachyr/anim/rage/events/punch
execute if entity @s[scores={AsaMatrix=57}] positioned ^ ^ ^3 run function asa_animator:brachyr/anim/rage/events/punch
execute if entity @s[scores={AsaMatrix=66}] positioned ^ ^ ^3 run function asa_animator:brachyr/anim/rage/events/punch
execute if entity @s[scores={AsaMatrix=73}] positioned ^ ^ ^3 run function asa_animator:brachyr/anim/rage/events/punch
execute if entity @s[scores={AsaMatrix=79}] positioned ^ ^ ^3 run function asa_animator:brachyr/anim/rage/events/punch
execute if entity @s[scores={AsaMatrix=85}] positioned ^ ^ ^3 run function asa_animator:brachyr/anim/rage/events/punch
execute if entity @s[scores={AsaMatrix=91}] positioned ^ ^ ^3 run function asa_animator:brachyr/anim/rage/events/punch
execute if entity @s[scores={AsaMatrix=97}] positioned ^ ^ ^3 run function asa_animator:brachyr/anim/rage/events/punch
execute if entity @s[scores={AsaMatrix=103}] positioned ^ ^ ^3 run function asa_animator:brachyr/anim/rage/events/punch
execute if entity @s[scores={AsaMatrix=135}] positioned ^ ^ ^3 run function asa_animator:brachyr/anim/rage/events/punch
execute if entity @s[scores={AsaMatrix=135..140}] run function asa_animator:brachyr/anim/rage/events/rage
execute if entity @s[scores={AsaMatrix=135..140}] as @e[distance=0..20,type=armor_stand,tag=BrachyRParts] at @s positioned ~ ~1.4 ~ run particle poof ~ ~ ~ 1 1 1 0 30
execute if entity @s[scores={AsaMatrix=137}] run function asa_animator:brachyr/manager/model/change_to_rage

execute if entity @s[scores={AsaMatrix=33..103}] positioned ^ ^ ^3 run particle crimson_spore ~ ~ ~ 1 0 1 1 100
execute if entity @s[scores={AsaMatrix=33..103}] positioned ^ ^ ^3 run particle lava ~ ~ ~ 1 0 1 1 10

execute if entity @s[scores={AsaMatrix=16..20}] as @e[distance=0..10,type=armor_stand,tag=BrachyRParts,tag=HeadU] at @s positioned ~ ~1.4 ~ run particle flash ~ ~ ~ 0 0 0 0 1
execute if entity @s[scores={AsaMatrix=16}] run playsound entity.blaze.death master @a ~ ~ ~ 2 0.8
execute if entity @s[scores={AsaMatrix=16}] run playsound entity.blaze.death master @a ~ ~ ~ 2 0.7

execute if entity @s[scores={AsaMatrix=149..186}] as @e[distance=0..10,type=armor_stand,tag=BrachyRParts,tag=HeadU] at @s positioned ~ ~1.4 ~ run particle flash ~ ~ ~ 0 0 0 0 1
execute if entity @s[scores={AsaMatrix=149}] run playsound entity.blaze.death master @a ~ ~ ~ 2 0.6
execute if entity @s[scores={AsaMatrix=149}] run playsound entity.blaze.death master @a ~ ~ ~ 2 0.5
execute if entity @s[scores={AsaMatrix=149}] run playsound entity.iron_golem.death master @a ~ ~ ~ 2 0.5

execute if entity @s[scores={AsaMatrix=155}] positioned ^ ^ ^3 run function asa_animator:brachyr/manager/bomb/red/set
execute if entity @s[scores={AsaMatrix=155..180}] positioned ^ ^ ^3 run function asa_animator:brachyr/anim/rage/events/set

execute if entity @s[scores={AsaMatrix=140..}] run particle crimson_spore ~ ~2 ~ 2 2 2 1 100