# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:teo/anim/bomb_step/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:teo/anim/bomb_step/keyframes/0
execute if entity @s[scores={AsaMatrix=1..8}] run tp @s ^0 ^0.0125 ^0
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:teo/anim/bomb_step/keyframes/1
execute if entity @s[scores={AsaMatrix=9..16}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:teo/anim/bomb_step/keyframes/2
execute if entity @s[scores={AsaMatrix=17..21}] run tp @s ^0 ^-0.02 ^0
execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:teo/anim/bomb_step/keyframes/3
execute if entity @s[scores={AsaMatrix=22..26}] run tp @s ^0 ^0.8 ^0
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:teo/anim/bomb_step/keyframes/4
execute if entity @s[scores={AsaMatrix=27..34}] run tp @s ^0 ^-0.5 ^0
execute if entity @s[scores={AsaMatrix=35}] run function asa_animator:teo/anim/bomb_step/keyframes/5
execute if entity @s[scores={AsaMatrix=35..37}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=38}] run function asa_animator:teo/anim/bomb_step/keyframes/6
execute if entity @s[scores={AsaMatrix=38..47}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=48..}] run function asa_animator:teo/anim/bomb_step/end
execute as @e[type=armor_stand,tag=TeoParts] run function #asa_matrix:animate
function asa_animator:teo/model

execute if entity @s[scores={AsaMatrix=..20}] run function asa_animator:teo/manager/rotate
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:teo/manager/model/change_to_open
execute if entity @s[scores={AsaMatrix=44}] run function asa_animator:teo/manager/model/change_to_normal
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:teo/anim/step_b/events/pos/set_pos
execute if entity @s[scores={AsaMatrix=22..34}] run function asa_animator:teo/anim/step_b/events/pos/offset

execute if entity @s[scores={AsaMatrix=21}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:teo/manager/particle/step
execute if entity @s[scores={AsaMatrix=34}] run function asa_animator:teo/manager/particle/step

execute if entity @s[scores={AsaMatrix=21}] run particle flame ^ ^3 ^4 1 1 1 1 30 force
execute if entity @s[scores={AsaMatrix=21}] positioned ^ ^ ^4 run function asa_animator:teo/manager/bomb/set_bomb
execute if entity @s[scores={AsaMatrix=22}] positioned ^ ^ ^8 run function asa_animator:teo/manager/bomb/set_bomb
execute if entity @s[scores={AsaMatrix=24}] positioned ^ ^ ^12 run function asa_animator:teo/manager/bomb/set_bomb
execute if entity @s[scores={AsaMatrix=27}] rotated ~30 ~ positioned ^ ^ ^4 run function asa_animator:teo/manager/bomb/set_bomb
execute if entity @s[scores={AsaMatrix=25}] rotated ~30 ~ positioned ^ ^ ^9 run function asa_animator:teo/manager/bomb/set_bomb
execute if entity @s[scores={AsaMatrix=28}] rotated ~30 ~ positioned ^ ^ ^14 run function asa_animator:teo/manager/bomb/set_bomb
execute if entity @s[scores={AsaMatrix=23}] rotated ~-30 ~ positioned ^ ^ ^4 run function asa_animator:teo/manager/bomb/set_bomb
execute if entity @s[scores={AsaMatrix=26}] rotated ~-30 ~ positioned ^ ^ ^7 run function asa_animator:teo/manager/bomb/set_bomb
execute if entity @s[scores={AsaMatrix=29}] rotated ~-30 ~ positioned ^ ^ ^11 run function asa_animator:teo/manager/bomb/set_bomb
