# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:brachyr/anim/punch_turn_r/start
execute if score @s AsaMatrix matches 1 run function asa_animator:brachyr/anim/punch_turn_r/keyframes/0
execute if score @s AsaMatrix matches 1..9 run tp @s ^0 ^0.02222222 ^-0.05555556
execute if score @s AsaMatrix matches 10 run function asa_animator:brachyr/anim/punch_turn_r/keyframes/1
execute if score @s AsaMatrix matches 10..21 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 22 run function asa_animator:brachyr/anim/punch_turn_r/keyframes/2
execute if score @s AsaMatrix matches 22..30 run tp @s ^0 ^0.01111111 ^-0.01111111
execute if score @s AsaMatrix matches 31 run function asa_animator:brachyr/anim/punch_turn_r/keyframes/3
execute if score @s AsaMatrix matches 31..40 run tp @s ^0 ^0 ^-0.015
execute if score @s AsaMatrix matches 41 run function asa_animator:brachyr/anim/punch_turn_r/keyframes/4
execute if score @s AsaMatrix matches 41..45 run tp @s ^0 ^-0.08000001 ^0.15
execute if score @s AsaMatrix matches 46 run function asa_animator:brachyr/anim/punch_turn_r/keyframes/5
execute if score @s AsaMatrix matches 46..49 run tp @s ^0 ^0.1 ^0.05
execute if score @s AsaMatrix matches 50 run function asa_animator:brachyr/anim/punch_turn_r/keyframes/6
execute if score @s AsaMatrix matches 50..64 run tp @s ^0 ^-0.02666667 ^-0.01333333
execute if score @s AsaMatrix matches 65 run function asa_animator:brachyr/anim/punch_turn_r/keyframes/7
execute if score @s AsaMatrix matches 65..78 run tp @s ^0 ^0.007142857 ^-0.03571429
execute if score @s AsaMatrix matches 79.. run function asa_animator:brachyr/anim/punch_turn_r/end
execute as @e[type=armor_stand,tag=BrachyRParts] run function #asa_matrix:animate
function asa_animator:brachyr/model

execute if score @s AsaMatrix matches 21 run playsound block.grass.step master @a ~ ~ ~ 2 0.5

execute if score @s AsaMatrix matches 22..36 run function asa_animator:brachyr/manager/rotate
execute if score @s AsaMatrix matches 22..32 if entity @e[distance=0..5,tag=BrachyAttackTarget] at @s run tp @s ^ ^ ^-0.5
execute if score @s AsaMatrix matches 36..41 unless entity @e[distance=0..4,tag=BrachyAttackTarget] at @s run tp @s ^ ^ ^1

execute if score @s AsaMatrix matches 45 positioned ^ ^ ^3 run function asa_animator:brachyr/anim/punch_r/events/damage
execute unless predicate asa_animator:brachyr/combo if score @s AsaMatrix matches 54 run function asa_animator:brachyr/manager/cancel_animation

execute if score @s AsaMatrix matches 65.. run function asa_animator:brachyr/manager/ground