# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:zinogre/anim/forwardstep/start
execute if score @s AsaMatrix matches 1 run function asa_animator:zinogre/anim/forwardstep/keyframes/0
execute if score @s AsaMatrix matches 1..10 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 11 run function asa_animator:zinogre/anim/forwardstep/keyframes/1
execute if score @s AsaMatrix matches 11..15 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 16 run function asa_animator:zinogre/anim/forwardstep/keyframes/2
execute if score @s AsaMatrix matches 16..20 run tp @s ^0 ^0.05 ^0.8
execute if score @s AsaMatrix matches 21 run function asa_animator:zinogre/anim/forwardstep/keyframes/3
execute if score @s AsaMatrix matches 21..25 run tp @s ^0 ^0 ^0.4
execute if score @s AsaMatrix matches 26.. run function asa_animator:zinogre/anim/forwardstep/end
execute as @e[type=armor_stand,tag=ZinogreParts] run function #asa_matrix:animate
function asa_animator:zinogre/model

execute if score @s AsaMatrix matches 0..15 run function asa_animator:zinogre/manager/rotate
execute if score @s AsaMatrix matches 16 run playsound entity.player.attack.sweep master @a ~ ~ ~ 2 0.8

execute if block ~ ~-1 ~ #asa_animator:no_collision run function asa_animator:zinogre/manager/check_ground
execute unless block ~ ~ ~ #asa_animator:no_collision run tp @s ~ ~0.5 ~ ~ ~