# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:ruko/anim/start_fly/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:ruko/anim/start_fly/keyframes/0
execute if entity @s[scores={AsaMatrix=1..7}] run tp @s ^0 ^0 ^-0.02857143
execute if entity @s[scores={AsaMatrix=8}] run function asa_animator:ruko/anim/start_fly/keyframes/1
execute if entity @s[scores={AsaMatrix=8..12}] run tp @s ^0 ^0.1 ^0.04
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:ruko/anim/start_fly/keyframes/2
execute if entity @s[scores={AsaMatrix=13..18}] run tp @s ^0 ^0.3333333 ^0
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:ruko/anim/start_fly/keyframes/3
execute if entity @s[scores={AsaMatrix=19..30}] run tp @s ^0 ^0.125 ^0
execute if entity @s[scores={AsaMatrix=31..}] run function asa_animator:ruko/anim/start_fly/end
execute as @e[type=armor_stand,tag=RukoParts] run function #asa_matrix:animate
function asa_animator:ruko/model

execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:ruko/manager/particle/step
execute if entity @s[scores={AsaMatrix=18}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7

execute if entity @s[scores={AsaMatrix=7}] if entity @a[distance=..6] as @a[distance=..6] run function mh_dp:player/knockback/start_wind

execute if entity @s[scores={AsaMatrix=7}] run tag @s add IsFlying