# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:teo/anim/flying_tackle_end/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:teo/anim/flying_tackle_end/keyframes/0
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^0 ^-0.006666667 ^0.01333333 ~7 ~
execute if entity @s[scores={AsaMatrix=6..15}] run tp @s ^0 ^-0.006666667 ^0.01333333 ~1 ~
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:teo/anim/flying_tackle_end/keyframes/1
execute if entity @s[scores={AsaMatrix=16..20}] run tp @s ^0 ^0.04 ^-0.04
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:teo/anim/flying_tackle_end/keyframes/2
execute if entity @s[scores={AsaMatrix=21..35}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:teo/anim/flying_tackle_end/keyframes/3
execute if entity @s[scores={AsaMatrix=36..50}] run tp @s ^0 ^-0.006666667 ^0
execute if entity @s[scores={AsaMatrix=51..}] run function asa_animator:teo/anim/flying_tackle_end/end
execute as @e[type=armor_stand,tag=TeoParts] run function #asa_matrix:animate
function asa_animator:teo/model

execute if entity @s[scores={AsaMatrix=..10}] at @s if entity @e[type=marker,tag=TeoMoveRotate] rotated as @e[type=marker,tag=TeoMoveRotate] run tp @s ^ ^ ^0.1

execute if entity @s[scores={AsaMatrix=20..35}] run playsound entity.hoglin.angry master @a ~ ~ ~ 2 0.9
execute if entity @s[scores={AsaMatrix=20..35}] run playsound entity.hoglin.angry master @a ~ ~ ~ 2 1.1
execute if entity @s[scores={AsaMatrix=20..35}] run playsound entity.polar_bear.warning master @a ~ ~ ~ 3 0.7