# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:brachyr/anim/raging_set_bomb/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:brachyr/anim/raging_set_bomb/keyframes/0
execute if entity @s[scores={AsaMatrix=1..8}] run tp @s ^0 ^0 ^0 ~0.5 ~
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:brachyr/anim/raging_set_bomb/keyframes/1
execute if entity @s[scores={AsaMatrix=9..18}] run tp @s ^0 ^0 ^0 ~-0.5 ~
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:brachyr/anim/raging_set_bomb/keyframes/2
execute if entity @s[scores={AsaMatrix=19..24}] run tp @s ^0 ^0 ^-0.05
execute if entity @s[scores={AsaMatrix=25}] run function asa_animator:brachyr/anim/raging_set_bomb/keyframes/3
execute if entity @s[scores={AsaMatrix=25..34}] run tp @s ^0 ^0 ^-0.03
execute if entity @s[scores={AsaMatrix=35}] run function asa_animator:brachyr/anim/raging_set_bomb/keyframes/4
execute if entity @s[scores={AsaMatrix=35..37}] run tp @s ^0 ^-0.05833333 ^0.15
execute if entity @s[scores={AsaMatrix=38}] run function asa_animator:brachyr/anim/raging_set_bomb/keyframes/5
execute if entity @s[scores={AsaMatrix=38..41}] run tp @s ^0 ^-0.04375 ^0.08750001
execute if entity @s[scores={AsaMatrix=42}] run function asa_animator:brachyr/anim/raging_set_bomb/keyframes/6
execute if entity @s[scores={AsaMatrix=42..46}] run tp @s ^0 ^-0.02 ^0
execute if entity @s[scores={AsaMatrix=47}] run function asa_animator:brachyr/anim/raging_set_bomb/keyframes/7
execute if entity @s[scores={AsaMatrix=47..55}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=56}] run function asa_animator:brachyr/anim/raging_set_bomb/keyframes/8
execute if entity @s[scores={AsaMatrix=56..70}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=71}] run function asa_animator:brachyr/anim/raging_set_bomb/keyframes/9
execute if entity @s[scores={AsaMatrix=71..83}] run tp @s ^0 ^0.01153846 ^0
execute if entity @s[scores={AsaMatrix=84}] run function asa_animator:brachyr/anim/raging_set_bomb/keyframes/10
execute if entity @s[scores={AsaMatrix=84..100}] run tp @s ^0 ^0.01764706 ^-0.01176471
execute if entity @s[scores={AsaMatrix=101..}] run function asa_animator:brachyr/anim/raging_set_bomb/end
execute as @e[type=armor_stand,tag=BrachyRParts] run function #asa_matrix:animate
function asa_animator:brachyr/model

execute if entity @s[scores={AsaMatrix=1..18}] if predicate asa_animator:random/020 as @e[distance=0..10,type=armor_stand,tag=BrachyRParts,tag=HeadU] at @s run particle spit ~ ~1.4 ~ 0.1 0.1 0.1 0 1
execute if entity @s[scores={AsaMatrix=9}] run playsound block.honey_block.break master @a ~ ~ ~ 2 0.5

execute if entity @s[scores={AsaMatrix=41}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.5

execute if entity @s[scores={AsaMatrix=55..84}] as @e[distance=0..10,type=armor_stand,tag=BrachyRParts,tag=HeadU] at @s positioned ~ ~1.4 ~ run particle flash ~ ~ ~ 0 0 0 0 1
execute if entity @s[scores={AsaMatrix=55}] run playsound entity.blaze.death master @a ~ ~ ~ 2 0.6
execute if entity @s[scores={AsaMatrix=55}] run playsound entity.blaze.death master @a ~ ~ ~ 2 0.5
execute if entity @s[scores={AsaMatrix=55}] run playsound entity.iron_golem.death master @a ~ ~ ~ 2 0.5

execute if entity @s[scores={AsaMatrix=55}] run function asa_animator:brachyr/manager/bomb/red/set
execute if entity @s[scores={AsaMatrix=60}] rotated ~ ~ run function asa_animator:brachyr/anim/raging_set_bomb/events/set_0
execute if entity @s[scores={AsaMatrix=65}] rotated ~30 ~ run function asa_animator:brachyr/anim/raging_set_bomb/events/set_1
execute if entity @s[scores={AsaMatrix=70}] rotated ~60 ~ run function asa_animator:brachyr/anim/raging_set_bomb/events/set_2
execute if entity @s[scores={AsaMatrix=75}] rotated ~90 ~ run function asa_animator:brachyr/anim/raging_set_bomb/events/set_3
execute if entity @s[scores={AsaMatrix=80}] rotated ~120 ~ run function asa_animator:brachyr/anim/raging_set_bomb/events/set_4