# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:zinogre/anim/hand_r_to_l/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:zinogre/anim/hand_r_to_l/keyframes/0
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^0 ^0.1 ^-0.04
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:zinogre/anim/hand_r_to_l/keyframes/1
execute if entity @s[scores={AsaMatrix=6..8}] run tp @s ^0 ^0.1666667 ^0.06666667
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:zinogre/anim/hand_r_to_l/keyframes/2
execute if entity @s[scores={AsaMatrix=9..11}] run tp @s ^0 ^0.03333334 ^0
execute if entity @s[scores={AsaMatrix=12}] run function asa_animator:zinogre/anim/hand_r_to_l/keyframes/3
execute if entity @s[scores={AsaMatrix=12..15}] run tp @s ^0 ^0.07499999 ^0
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:zinogre/anim/hand_r_to_l/keyframes/4
execute if entity @s[scores={AsaMatrix=16..17}] run tp @s ^0 ^-0.8 ^0
execute if entity @s[scores={AsaMatrix=18}] run function asa_animator:zinogre/anim/hand_r_to_l/keyframes/5
execute if entity @s[scores={AsaMatrix=18..19}] run tp @s ^0 ^0.55 ^0.025
execute if entity @s[scores={AsaMatrix=20}] run function asa_animator:zinogre/anim/hand_r_to_l/keyframes/6
execute if entity @s[scores={AsaMatrix=20..22}] run tp @s ^0 ^-0.3 ^0.01666667
execute if entity @s[scores={AsaMatrix=23}] run function asa_animator:zinogre/anim/hand_r_to_l/keyframes/7
execute if entity @s[scores={AsaMatrix=23..31}] run tp @s ^0 ^0 ^0 ~0.5 ~
execute if entity @s[scores={AsaMatrix=32..}] run function asa_animator:zinogre/anim/hand_r_to_l/end
execute as @e[type=armor_stand,tag=ZinogreParts] run function #asa_matrix:animate
function asa_animator:zinogre/model

# 移動
    execute if entity @s[scores={AsaMatrix=1..8}] run function asa_animator:zinogre/manager/rotate_fast
    execute if entity @s[scores={AsaMatrix=1..8}] at @s unless entity @e[tag=ZinogreAttackTarget,distance=0..5.5] run tp @s ^ ^ ^0.6 ~ ~
    execute if entity @s[scores={AsaMatrix=9}] at @s run function asa_animator:zinogre/anim/hand_l_start/events/pos/set_pos
    execute if entity @s[scores={AsaMatrix=10..17}] at @s run function asa_animator:zinogre/anim/hand_l_start/events/pos/offset

# 演出
    execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:zinogre/manager/particle/step
    execute if entity @s[scores={AsaMatrix=18}] run function asa_animator:zinogre/manager/particle/step

# 攻撃
    execute if entity @s[scores={AsaMatrix=18}] at @s positioned ^1 ^ ^6 run function asa_animator:zinogre/anim/hand_l_start/events/damage

# 高度調整
    execute if entity @s[scores={AsaMatrix=22..}] if block ~ ~0.5 ~ #asa_animator:no_collision run function asa_animator:zinogre/manager/check_ground
    execute if entity @s[scores={AsaMatrix=22..}] unless block ~ ~0.7 ~ #asa_animator:no_collision run tp @s ~ ~0.1 ~ ~ ~