# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:brachyr/anim/jump/start
execute if score @s AsaMatrix matches 1 run function asa_animator:brachyr/anim/jump/keyframes/0
execute if score @s AsaMatrix matches 1..5 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 6 run function asa_animator:brachyr/anim/jump/keyframes/1
execute if score @s AsaMatrix matches 6..11 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 12 run function asa_animator:brachyr/anim/jump/keyframes/2
execute if score @s AsaMatrix matches 12..17 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 18 run function asa_animator:brachyr/anim/jump/keyframes/3
execute if score @s AsaMatrix matches 18..23 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 24 run function asa_animator:brachyr/anim/jump/keyframes/4
execute if score @s AsaMatrix matches 24..29 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 30 run function asa_animator:brachyr/anim/jump/keyframes/5
execute if score @s AsaMatrix matches 30..35 run tp @s ^0 ^-0.06666667 ^-0.08333334
execute if score @s AsaMatrix matches 36 run function asa_animator:brachyr/anim/jump/keyframes/6
execute if score @s AsaMatrix matches 36..44 run tp @s ^0 ^-0.01111111 ^-0.03333334
execute if score @s AsaMatrix matches 45 run function asa_animator:brachyr/anim/jump/keyframes/7
execute if score @s AsaMatrix matches 45..50 run tp @s ^0 ^0.6666667 ^0
execute if score @s AsaMatrix matches 51 run function asa_animator:brachyr/anim/jump/keyframes/8
execute if score @s AsaMatrix matches 51..56 run tp @s ^0 ^0.6666667 ^0
execute if score @s AsaMatrix matches 57 run function asa_animator:brachyr/anim/jump/keyframes/9
execute if score @s AsaMatrix matches 57..62 run tp @s ^0 ^-0.5 ^0
execute if score @s AsaMatrix matches 63 run function asa_animator:brachyr/anim/jump/keyframes/10
execute if score @s AsaMatrix matches 63..68 run tp @s ^0 ^-0.7166666 ^0.1333333
execute if score @s AsaMatrix matches 69 run function asa_animator:brachyr/anim/jump/keyframes/11
execute if score @s AsaMatrix matches 69..76 run tp @s ^0 ^-0.0125 ^0.0125
execute if score @s AsaMatrix matches 77 run function asa_animator:brachyr/anim/jump/keyframes/12
execute if score @s AsaMatrix matches 77..88 run tp @s ^0 ^0 ^0.01666667
execute if score @s AsaMatrix matches 89 run function asa_animator:brachyr/anim/jump/keyframes/13
execute if score @s AsaMatrix matches 89..102 run tp @s ^0 ^-0.007142857 ^-0.02142857
execute if score @s AsaMatrix matches 103.. run function asa_animator:brachyr/anim/jump/end
execute as @e[type=armor_stand,tag=BrachyRParts] run function #asa_matrix:animate
function asa_animator:brachyr/model

execute if score @s AsaMatrix matches 1 run playsound block.grass.step master @a ~ ~ ~ 2 0.5
execute if score @s AsaMatrix matches 44 run function asa_animator:brachyr/manager/particle/jump
execute if score @s AsaMatrix matches 68 run function asa_animator:brachyr/manager/particle/jump

execute if score @s AsaMatrix matches 1..44 run function asa_animator:brachyr/manager/rotate
execute if score @s AsaMatrix matches 44 run function asa_animator:brachyr/anim/jump/events/pos/set_pos
execute if score @s AsaMatrix matches 45..68 run function asa_animator:brachyr/anim/jump/events/pos/offset
execute if score @s AsaMatrix matches 69 positioned ^ ^ ^3 run function asa_animator:brachyr/anim/jump/events/damage_n
execute unless entity @s[tag=Phase2] unless entity @s[tag=!ActiveArmL,tag=!ActiveArmL] if score @s AsaMatrix matches 75 positioned ^ ^ ^3 run function asa_animator:brachyr/anim/jump/events/damage_bomb
execute if score @s AsaMatrix matches 69..85 if entity @s[tag=Phase2] run function asa_animator:brachyr/anim/jump/events/set