# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:zinogre/anim/hand_2/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:zinogre/anim/hand_2/keyframes/0
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^0 ^0.16 ^0
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:zinogre/anim/hand_2/keyframes/1
execute if entity @s[scores={AsaMatrix=6..10}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:zinogre/anim/hand_2/keyframes/2
execute if entity @s[scores={AsaMatrix=11..15}] run tp @s ^0 ^-0.22 ^0
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:zinogre/anim/hand_2/keyframes/3
execute if entity @s[scores={AsaMatrix=16..18}] run tp @s ^0 ^0.1 ^0
execute if entity @s[scores={AsaMatrix=19}] run function asa_animator:zinogre/anim/hand_2/keyframes/4
execute if entity @s[scores={AsaMatrix=19..25}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=26}] run function asa_animator:zinogre/anim/hand_2/keyframes/5
execute if entity @s[scores={AsaMatrix=26..30}] run tp @s ^0 ^0.16 ^0
execute if entity @s[scores={AsaMatrix=31}] run function asa_animator:zinogre/anim/hand_2/keyframes/6
execute if entity @s[scores={AsaMatrix=31..35}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=36}] run function asa_animator:zinogre/anim/hand_2/keyframes/7
execute if entity @s[scores={AsaMatrix=36..40}] run tp @s ^0 ^-0.22 ^0
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:zinogre/anim/hand_2/keyframes/8
execute if entity @s[scores={AsaMatrix=41..43}] run tp @s ^0 ^0.1 ^0
execute if entity @s[scores={AsaMatrix=44}] run function asa_animator:zinogre/anim/hand_2/keyframes/9
execute if entity @s[scores={AsaMatrix=44..55}] run tp @s ^0 ^0 ^0 ~0.1 ~
execute if entity @s[scores={AsaMatrix=56}] run function asa_animator:zinogre/anim/hand_2/keyframes/10
execute if entity @s[scores={AsaMatrix=56..70}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=71..}] run function asa_animator:zinogre/anim/hand_2/end
execute as @e[type=armor_stand,tag=ZinogreParts] run function #asa_matrix:animate
function asa_animator:zinogre/model

execute if entity @s[scores={AsaMatrix=0..8}] run function asa_animator:zinogre/manager/rotate_fast
execute if entity @s[scores={AsaMatrix=0..10}] at @s unless entity @e[tag=ZinogreAttackTarget,distance=0..4] run tp @s ^ ^ ^0.8 ~ ~
execute if entity @s[scores={AsaMatrix=15}] at @s positioned ^-2 ^ ^3 run function asa_animator:zinogre/anim/hand_2/events/damage

execute if entity @s[scores={AsaMatrix=25..33}] run function asa_animator:zinogre/manager/rotate_fast
execute if entity @s[scores={AsaMatrix=25..35}] at @s unless entity @e[tag=ZinogreAttackTarget,distance=0..4] run tp @s ^ ^ ^0.8 ~ ~
execute if entity @s[scores={AsaMatrix=40}] at @s positioned ^2 ^ ^3 run function asa_animator:zinogre/anim/hand_2/events/damage

execute if block ~ ~-1 ~ #asa_animator:no_collision run function asa_animator:zinogre/manager/check_ground
execute unless block ~ ~ ~ #asa_animator:no_collision run tp @s ~ ~0.5 ~ ~ ~