# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:nazuti/anim/move_back/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:nazuti/anim/move_back/keyframes/0
execute if entity @s[scores={AsaMatrix=1..3}] run tp @s ^0 ^-0.06666667 ^-0.4
execute if entity @s[scores={AsaMatrix=4}] run function asa_animator:nazuti/anim/move_back/keyframes/1
execute if entity @s[scores={AsaMatrix=4..6}] run tp @s ^0 ^0 ^-0.4
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:nazuti/anim/move_back/keyframes/2
execute if entity @s[scores={AsaMatrix=7..12}] run tp @s ^0 ^0.01666667 ^-0.4
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:nazuti/anim/move_back/keyframes/3
execute if entity @s[scores={AsaMatrix=13..15}] run tp @s ^0 ^-0.03333334 ^-0.3
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:nazuti/anim/move_back/keyframes/4
execute if entity @s[scores={AsaMatrix=16..25}] run tp @s ^0 ^0.02 ^-0.1
execute if entity @s[scores={AsaMatrix=26..}] run function asa_animator:nazuti/anim/move_back/end
execute as @e[type=armor_stand,tag=NazutiParts] run function #asa_matrix:animate
function asa_animator:nazuti/model

execute if entity @s[scores={AsaMatrix=6}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=15}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7

execute at @s positioned ~ ~5 ~ run tp @s ~ ~ ~
execute at @s positioned ~ ~5 ~ run function asa_animator:zinogre/manager/check_ground
function asa_animator:nazuti/manager/rotate