# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:reus/anger/bjb/start
execute if score @s AsaMatrix matches 1 run function asa_animator:reus/anger/bjb/keyframes/0
execute if score @s AsaMatrix matches 1..4 run tp @s ^0 ^0 ^-0.025
execute if score @s AsaMatrix matches 5 run function asa_animator:reus/anger/bjb/keyframes/1
execute if score @s AsaMatrix matches 5..20 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 21 run function asa_animator:reus/anger/bjb/keyframes/2
execute if score @s AsaMatrix matches 21..29 run tp @s ^0 ^0.5555556 ^-0.6555555
execute if score @s AsaMatrix matches 30 run function asa_animator:reus/anger/bjb/keyframes/3
execute if score @s AsaMatrix matches 30..37 run tp @s ^0 ^-0.3125 ^-0.0625
execute if score @s AsaMatrix matches 38.. run function asa_animator:reus/anger/bjb/end
execute as @e[type=armor_stand,tag=ReusParts] run function #asa_matrix:animate
function asa_animator:reus/model
execute if score @s AsaMatrix matches 21 run tag @s add IsFlying

# 敵を向く
execute if score @s AsaMatrix matches 1..8 run function asa_animator:reus/manager/rotate_fast
# 発射位置決定
execute if score @s AsaMatrix matches 8 at @e[tag=ReusAttackTarget,limit=1] run summon marker ~ ~ ~ {Tags:["ReusBreathTarget"]}

# ブレス発射
execute if score @s AsaMatrix matches 23 positioned ^ ^3 ^5 facing entity @e[type=marker,tag=ReusBreathTarget,limit=1] feet run function asa_animator:reus/normal/breath/effect/attack

# 効果音
execute if score @s AsaMatrix matches 29 run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7