# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:tiga/anim_anger/dash/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:tiga/anim_anger/dash/keyframes/0
execute if entity @s[scores={AsaMatrix=1..1}] run tp @s ^0 ^-0.1 ^0
execute if entity @s[scores={AsaMatrix=2}] run function asa_animator:tiga/anim_anger/dash/keyframes/1
execute if entity @s[scores={AsaMatrix=2..4}] run tp @s ^0 ^0.06666667 ^0
execute if entity @s[scores={AsaMatrix=5}] run function asa_animator:tiga/anim_anger/dash/keyframes/2
execute if entity @s[scores={AsaMatrix=5..6}] run tp @s ^0 ^-0.05 ^0
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:tiga/anim_anger/dash/keyframes/3
execute if entity @s[scores={AsaMatrix=7..8}] run tp @s ^0 ^-0.05 ^0
execute if entity @s[scores={AsaMatrix=9}] run function asa_animator:tiga/anim_anger/dash/keyframes/4
execute if entity @s[scores={AsaMatrix=9..10}] run tp @s ^0 ^0.1 ^0
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:tiga/anim_anger/dash/keyframes/5
execute if entity @s[scores={AsaMatrix=11..13}] run tp @s ^0 ^-0.03333334 ^0
execute if entity @s[scores={AsaMatrix=14..}] run function asa_animator:tiga/anim/dash/end
execute as @e[type=armor_stand,tag=TigaParts] run function #asa_matrix:animate
function asa_animator:tiga/model

execute at @s run tp @s ^ ^ ^0.85
execute at @s positioned ~ ~5 ~ run tp @s ~ ~ ~
execute at @s positioned ~ ~5 ~ run function asa_animator:zinogre/manager/check_ground
function asa_animator:tiga/anim/dash/events/damage

particle block grass_block ~ ~0.3 ~ 1 0 1 0 5
execute if entity @s[scores={AsaMatrix=1}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.5
execute if entity @s[scores={AsaMatrix=8}] run playsound entity.hoglin.step master @a ~ ~ ~ 2 0.5

# 回転
execute if entity @s[tag=!DashSpin,tag=!DashBite] positioned ^ ^ ^6 if entity @e[distance=0..5,type=marker,tag=TigaDashTarget] run scoreboard players set #mhdp_tiga_dash_count AsaMatrix 2
execute if entity @s[tag=DashBite] positioned ^ ^ ^6 if entity @e[distance=0..5,type=marker,tag=TigaDashTarget] run scoreboard players set #mhdp_tiga_dash_count AsaMatrix 0
execute if entity @s[tag=DashSpin] positioned ^ ^ ^12 if entity @e[distance=0..5,type=marker,tag=TigaDashTarget] run scoreboard players set #mhdp_tiga_dash_count AsaMatrix 0
execute if entity @e[distance=0..5,type=marker,tag=TigaDashTarget] run kill @e[distance=0..5,type=marker,tag=TigaDashTarget]