# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:diablos/anim/anger/dash_stop/start
execute if score @s AsaMatrix matches 1 run function asa_animator:diablos/anim/anger/dash_stop/keyframes/0
execute if score @s AsaMatrix matches 1..6 run tp @s ^0 ^0.05 ^0.5
execute if score @s AsaMatrix matches 7 run function asa_animator:diablos/anim/anger/dash_stop/keyframes/1
execute if score @s AsaMatrix matches 7..12 run tp @s ^0 ^-0.06666667 ^0.25
execute if score @s AsaMatrix matches 13 run function asa_animator:diablos/anim/anger/dash_stop/keyframes/2
execute if score @s AsaMatrix matches 13..26 run tp @s ^0 ^0 ^0.03571429
execute if score @s AsaMatrix matches 27 run function asa_animator:diablos/anim/anger/dash_stop/keyframes/3
execute if score @s AsaMatrix matches 27..30 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 31 run function asa_animator:diablos/anim/anger/dash_stop/keyframes/4
execute if score @s AsaMatrix matches 31..43 run tp @s ^0 ^0.007692308 ^0.03846154
execute if score @s AsaMatrix matches 44.. run function asa_animator:diablos/anim/normal/dash_stop/end
execute as @e[type=armor_stand,tag=DiablosParts] run function #asa_matrix:animate
function asa_animator:diablos/model

# 高度調整
execute at @s positioned ~ ~1 ~ run function asa_animator:zinogre/manager/check_ground
execute at @s unless block ~ ~ ~ #asa_animator:no_collision at @s run tp @s ~ ~0.5 ~ ~ ~

# 攻撃
execute if score @s AsaMatrix matches 1..24 if entity @e[type=!armor_stand,type=!marker,distance=0..5] run function asa_animator:diablos/anim/normal/dash/events/damage

execute if score @s AsaMatrix matches 1..24 run playsound block.grass.step master @a ~ ~ ~ 3 0.8
execute if score @s AsaMatrix matches 1..24 run particle block sand ~ ~0.5 ~ 1 0 1 0 3