# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:nazuti/anim/counter_move/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:nazuti/anim/counter_move/keyframes/0
execute if entity @s[scores={AsaMatrix=1..3}] run tp @s ^0 ^-0.06666667 ^-0.4
execute if entity @s[scores={AsaMatrix=4}] run function asa_animator:nazuti/anim/counter_move/keyframes/1
execute if entity @s[scores={AsaMatrix=4..6}] run tp @s ^0 ^0 ^-0.2
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:nazuti/anim/counter_move/keyframes/2
execute if entity @s[scores={AsaMatrix=7..12}] run tp @s ^0 ^0.01666667 ^-0.2
execute if entity @s[scores={AsaMatrix=13}] run function asa_animator:nazuti/anim/counter_move/keyframes/3
execute if entity @s[scores={AsaMatrix=13..15}] run tp @s ^0 ^-0.03333334 ^-0.2
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:nazuti/anim/counter_move/keyframes/4
execute if entity @s[scores={AsaMatrix=16..21}] run tp @s ^0 ^0.01666667 ^-0.1
execute if entity @s[scores={AsaMatrix=22}] run function asa_animator:nazuti/anim/counter_move/keyframes/5
execute if entity @s[scores={AsaMatrix=22..24}] run tp @s ^0 ^-0.03333334 ^-0.1
execute if entity @s[scores={AsaMatrix=25}] run function asa_animator:nazuti/anim/counter_move/keyframes/6
execute if entity @s[scores={AsaMatrix=25..32}] run tp @s ^0 ^0.025 ^-0.1
execute if entity @s[scores={AsaMatrix=33..}] run function asa_animator:nazuti/anim/counter_move/end
execute as @e[type=armor_stand,tag=NazutiParts] run function #asa_matrix:animate
function asa_animator:nazuti/model

execute if entity @s[scores={AsaMatrix=1}] if predicate asa_animator:random/050 run tag @s add IsMoveRight
execute if entity @s[tag=IsMoveRight,scores={AsaMatrix=..24}] at @s run tp @s ~ ~ ~ ~3 ~
execute if entity @s[tag=!IsMoveRight,scores={AsaMatrix=..24}] at @s run tp @s ~ ~ ~ ~-3 ~

execute if entity @s[scores={AsaMatrix=3}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=12}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=21}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7

execute at @s positioned ~ ~5 ~ run tp @s ~ ~ ~
execute at @s positioned ~ ~5 ~ run function asa_animator:zinogre/manager/check_ground

execute if entity @s[scores={AsaMatrix=4}] run function asa_animator:nazuti/manager/model/stealth_lucent
execute if entity @s[scores={AsaMatrix=10}] run function asa_animator:nazuti/manager/model/stealth_invisible
