# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:diablos/anim/anger/short_dash/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:diablos/anim/anger/short_dash/keyframes/0
execute if entity @s[scores={AsaMatrix=1..6}] run tp @s ^0 ^0.03333334 ^-0.3333333
execute if entity @s[scores={AsaMatrix=7}] run function asa_animator:diablos/anim/anger/short_dash/keyframes/1
execute if entity @s[scores={AsaMatrix=7..15}] run tp @s ^0 ^-0.08888889 ^-0.2222222
execute if entity @s[scores={AsaMatrix=16}] run function asa_animator:diablos/anim/anger/short_dash/keyframes/2
execute if entity @s[scores={AsaMatrix=16..20}] run tp @s ^0 ^0 ^-0.06000004
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:diablos/anim/anger/short_dash/keyframes/3
execute if entity @s[scores={AsaMatrix=21..23}] run tp @s ^0 ^0.1666667 ^1.433333
execute if entity @s[scores={AsaMatrix=24}] run function asa_animator:diablos/anim/anger/short_dash/keyframes/4
execute if entity @s[scores={AsaMatrix=24..26}] run tp @s ^0 ^-0.1666667 ^1.333333
execute if entity @s[scores={AsaMatrix=27}] run function asa_animator:diablos/anim/anger/short_dash/keyframes/5
execute if entity @s[scores={AsaMatrix=27..28}] run tp @s ^0 ^0.25 ^2
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:diablos/anim/anger/short_dash/keyframes/6
execute if entity @s[scores={AsaMatrix=29..31}] run tp @s ^0 ^-0.1666667 ^1.333333
execute if entity @s[scores={AsaMatrix=32}] run function asa_animator:diablos/anim/anger/short_dash/keyframes/7
execute if entity @s[scores={AsaMatrix=32..40}] run tp @s ^0 ^0 ^0.07777776
execute if entity @s[scores={AsaMatrix=41}] run function asa_animator:diablos/anim/anger/short_dash/keyframes/8
execute if entity @s[scores={AsaMatrix=41..41}] run tp @s ^0 ^0 ^0.1000004
execute if entity @s[scores={AsaMatrix=42}] run function asa_animator:diablos/anim/anger/short_dash/keyframes/9
execute if entity @s[scores={AsaMatrix=42..50}] run tp @s ^0 ^0.06666667 ^-0.03333335
execute if entity @s[scores={AsaMatrix=51..}] run function asa_animator:diablos/anim/normal/short_dash/end
execute as @e[type=armor_stand,tag=DiablosParts] run function #asa_matrix:animate
function asa_animator:diablos/model

execute if entity @s[scores={AsaMatrix=1..15}] run function asa_animator:diablos/manager/rotate

execute if entity @s[scores={AsaMatrix=21..}] at @s if block ~ ~-0.2 ~ #asa_animator:no_collision at @s run function asa_animator:zinogre/manager/check_ground
execute if entity @s[scores={AsaMatrix=41..}] at @s unless block ~ ~ ~ #asa_animator:no_collision at @s run tp @s ~ ~0.1 ~ ~ ~

execute if entity @s[scores={AsaMatrix=1}] run playsound block.grass.step master @a ~ ~ ~ 2 0.8

execute if entity @s[scores={AsaMatrix=21..39}] run particle block sand ~ ~0.5 ~ 1 0.5 1 0 5
execute if entity @s[scores={AsaMatrix=32..37}] run playsound block.grass.step master @a ~ ~ ~ 2 0.8

execute if entity @s[scores={AsaMatrix=21}] run playsound entity.iron_golem.step master @a ~ ~ ~ 3 0.7
execute if entity @s[scores={AsaMatrix=26}] run playsound entity.iron_golem.step master @a ~ ~ ~ 3 0.7
execute if entity @s[scores={AsaMatrix=31}] run playsound entity.iron_golem.step master @a ~ ~ ~ 3 0.7

execute if entity @s[scores={AsaMatrix=21..35}] run function asa_animator:diablos/anim/normal/short_dash/events/damage