# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:diablos/anim/anger/dive_jump/start
execute if score @s AsaMatrix matches 1 run function asa_animator:diablos/anim/anger/dive_jump/keyframes/0
execute if score @s AsaMatrix matches 1..5 run tp @s ^0 ^1 ^0.6
execute if score @s AsaMatrix matches 6 run function asa_animator:diablos/anim/anger/dive_jump/keyframes/1
execute if score @s AsaMatrix matches 6..10 run tp @s ^0 ^1 ^0.6
execute if score @s AsaMatrix matches 11 run function asa_animator:diablos/anim/anger/dive_jump/keyframes/2
execute if score @s AsaMatrix matches 11..15 run tp @s ^0 ^0.1 ^0.6
execute if score @s AsaMatrix matches 16 run function asa_animator:diablos/anim/anger/dive_jump/keyframes/3
execute if score @s AsaMatrix matches 16..25 run tp @s ^0 ^ ^0.6
execute if score @s AsaMatrix matches 26 run function asa_animator:diablos/anim/anger/dive_jump/keyframes/4
execute if score @s AsaMatrix matches 26..35 run tp @s ^0 ^ ^0.6
execute if score @s AsaMatrix matches 36 run function asa_animator:diablos/anim/anger/dive_jump/keyframes/5
execute if score @s AsaMatrix matches 36..50 run tp @s ^0 ^0 ^0.5 ~-3 ~
execute if score @s AsaMatrix matches 51 run function asa_animator:diablos/anim/anger/dive_jump/keyframes/6
execute if score @s AsaMatrix matches 51..65 run tp @s ^0 ^0 ^0.3 ~-1 ~
execute if score @s AsaMatrix matches 66 run function asa_animator:diablos/anim/anger/dive_jump/keyframes/7
execute if score @s AsaMatrix matches 66..80 run tp @s ^0 ^0 ^0.2 ~2 ~
execute if score @s AsaMatrix matches 81 run function asa_animator:diablos/anim/anger/dive_jump/keyframes/8
execute if score @s AsaMatrix matches 81..90 run tp @s ^0 ^0 ^0.1 ~1 ~
execute if score @s AsaMatrix matches 91 run function asa_animator:diablos/anim/anger/dive_jump/keyframes/9
execute if score @s AsaMatrix matches 91..110 run tp @s ^0 ^0 ^0.05 ~0.2 ~
execute if score @s AsaMatrix matches 111.. run function asa_animator:diablos/anim/anger/dive_jump/end
execute as @e[type=armor_stand,tag=DiablosParts] run function #asa_matrix:animate
function asa_animator:diablos/model

# 攻撃
execute if score @s AsaMatrix matches 2 as @e[type=armor_stand,tag=DiablosParts] run function asa_animator:diablos/anim/normal/dive/events/change_to_normal
execute if score @s AsaMatrix matches 1..90 if entity @e[type=!armor_stand,type=!marker,distance=0..5] run function asa_animator:diablos/anim/anger/dive_jump/events/damage

# 位置決定
execute if score @s AsaMatrix matches 15 run function asa_animator:diablos/anim/anger/dive_jump/events/pos/set_pos

# 位置オフセット
execute if score @s AsaMatrix matches 16..35 run function asa_animator:diablos/anim/anger/dive_jump/events/pos/offset

# 効果音
execute if score @s AsaMatrix matches 1 run playsound entity.wither.break_block master @a ~ ~ ~ 3 1
execute if score @s AsaMatrix matches 1 run particle explosion_emitter ~ ~ ~ 0 0 0 0 1 force
execute if score @s AsaMatrix matches 35..90 run playsound block.grass.step master @a ~ ~ ~ 3 0.8
execute if score @s AsaMatrix matches 35..90 run particle block sand ~ ~0.5 ~ 1 0 1 0 3

execute if score @s AsaMatrix matches 35.. at @s positioned ~ ~5 ~ run tp @s ~ ~ ~
execute if score @s AsaMatrix matches 35.. at @s positioned ~ ~5 ~ run function asa_animator:zinogre/manager/check_ground
execute if score @s AsaMatrix matches 35..95 at @s run tp @s ~ ~-0.3 ~