# This function was generated by ArmorstandAnimator
scoreboard players add @s AsaMatrix 1
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:ruko/anim/claw_c_r/start
execute if entity @s[scores={AsaMatrix=1}] run function asa_animator:ruko/anim/claw_c_r/keyframes/0
execute if entity @s[scores={AsaMatrix=1..5}] run tp @s ^0 ^-0.02 ^0 ~-1 ~
execute if entity @s[scores={AsaMatrix=6}] run function asa_animator:ruko/anim/claw_c_r/keyframes/1
execute if entity @s[scores={AsaMatrix=6..10}] run tp @s ^0 ^0.06 ^0
execute if entity @s[scores={AsaMatrix=11}] run function asa_animator:ruko/anim/claw_c_r/keyframes/2
execute if entity @s[scores={AsaMatrix=11..13}] run tp @s ^0 ^0 ^0
execute if entity @s[scores={AsaMatrix=14}] run function asa_animator:ruko/anim/claw_c_r/keyframes/3
execute if entity @s[scores={AsaMatrix=14..16}] run tp @s ^0 ^-0.03333334 ^0.03333334 ~1 ~
execute if entity @s[scores={AsaMatrix=17}] run function asa_animator:ruko/anim/claw_c_r/keyframes/4
execute if entity @s[scores={AsaMatrix=17..20}] run tp @s ^0 ^-0.025 ^0.025 ~1 ~
execute if entity @s[scores={AsaMatrix=21}] run function asa_animator:ruko/anim/claw_c_r/keyframes/5
execute if entity @s[scores={AsaMatrix=21..28}] run tp @s ^0 ^-0.0125 ^0 ~1 ~
execute if entity @s[scores={AsaMatrix=29}] run function asa_animator:ruko/anim/claw_c_r/keyframes/6
execute if entity @s[scores={AsaMatrix=29..45}] run tp @s ^0 ^0.005882353 ^-0.01176471
execute if entity @s[scores={AsaMatrix=46..}] run function asa_animator:ruko/anim/claw_c_r/end
execute as @e[type=armor_stand,tag=RukoParts] run function #asa_matrix:animate
function asa_animator:ruko/model

execute if entity @s[scores={AsaMatrix=1}] run playsound entity.ender_dragon.flap master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=5}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=28}] run playsound block.grass.step master @a ~ ~ ~ 2 0.7
execute if entity @s[scores={AsaMatrix=1..10}] run function asa_animator:ruko/manager/rotate_fast
execute if entity @s[scores={AsaMatrix=1..10}] if entity @s[tag=RukoAttackTarget,distance=..7] at @s run tp @s ^ ^ ^-0.5
execute if entity @s[scores={AsaMatrix=1..10}] unless entity @s[tag=RukoAttackTarget,distance=..15] at @s run tp @s ^ ^ ^0.3

execute if entity @s[scores={AsaMatrix=14..20}] unless entity @s[tag=RukoAttackTarget,distance=..7] at @s run tp @s ^ ^ ^0.7

execute if entity @s[scores={AsaMatrix=28}] if score #mhdp_ruko_claw_count AsaMatrix matches 1.. run function asa_animator:ruko/anim/claw_c_r/events/change

execute if entity @s[scores={AsaMatrix=17}] run playsound item.trident.throw master @a ~ ~ ~ 2 1.2
execute if entity @s[scores={AsaMatrix=18}] positioned ^ ^1 ^4.5 run function asa_animator:ruko/anim/claw_l/events/damage
execute if entity @s[scores={AsaMatrix=19}] positioned ^-1 ^1 ^4.5 run function asa_animator:ruko/anim/claw_l/events/damage
execute if entity @s[scores={AsaMatrix=20}] positioned ^-2 ^1 ^4.5 run function asa_animator:ruko/anim/claw_l/events/damage

execute at @s if block ~ ~-0.1 ~ #asa_animator:no_collision at @s run function asa_animator:zinogre/manager/check_ground
execute at @s unless block ~ ~0.1 ~ #asa_animator:no_collision at @s run tp @s ~ ~0.1 ~ ~ ~

execute if entity @s[scores={AsaMatrix=1}] if score #mhdp_ruko_lv AsaMatrix matches 1.. run playsound entity.evoker.cast_spell master @a ~ ~ ~ 3 1
execute if entity @s[scores={AsaMatrix=1..10}] if score #mhdp_ruko_lv AsaMatrix matches 1.. run function asa_animator:ruko/manager/particle/pull
execute if entity @s[scores={AsaMatrix=1..10}] if score #mhdp_ruko_lv AsaMatrix matches 1.. as @a[distance=5..16] unless entity @s[scores={MhdpTAvoid=1..}] unless entity @s[scores={MhdpTDamage=1..}] at @s facing entity @e[type=armor_stand,tag=RukoRoot] feet rotated ~ 0 positioned ^ ^ ^0.1 rotated as @s run function asa_animator:ruko/anim/g_flying_press/events/move